SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_PRODUCAO_GUSA] AS

SELECT
    'MIB' AS SERVIDOR,
    GETDATE() AS ATUALIZACAO,
    E115CES.NUMTIC AS [N° TIQUETE],
    E115CES.SEQENT AS [SEQ. TIQUETE],
    E115CES.USU_TIPTIC AS [COD. TIPO. TIQUETE],

    CASE E115CES.USU_TIPTIC
        WHEN '1' THEN 'ENTRADA MATERIAL'
        WHEN '2' THEN 'SAIDA PRODUTO'
        WHEN '3' THEN 'ENTRADA PRODUCAO'
        WHEN '4' THEN 'ENTRADA CARVAO'
        WHEN '5' THEN 'ENTRADA MATERIAL ALMOXARIFADO'
        WHEN '6' THEN 'SAIDA VEICULO PARA MANUTENCAO'
    END AS [TIPO TIQUETE],

    Convert(varchar(10), E115CES.DATENT,103) AS [DATA ENTRADA],
    CAST(E115CES.HORENT/ 60 AS VARCHAR) + ':' +
    RIGHT('0' + CAST(E115CES.HORENT % 60 AS VARCHAR), 2) AS [HORA ENTRADA],
    E115CES.USUENT AS [USUARIO ENTRADA TIQUETE],
    E.NOMUSU AS [NOME USUARIO ENTRADA],
    E115CES.USUSAI AS [USUARIO SAIDA TIQUETE],
    S.NOMUSU AS [NOME USUARIO SAIDA],
    Convert(varchar(10), E115CES.DATSAI,103) AS [DATA SAIDA],
    CAST(E115CES.HORSAI/ 60 AS VARCHAR) + ':' +
    RIGHT('0' + CAST(E115CES.HORSAI % 60 AS VARCHAR), 2) AS [HORA SAIDA],
    E115CES.SITCES AS [COD. SITUACAO TIQUETE],

    CASE E115CES.SITCES
        WHEN '1' THEN 'DIGITADA'
        WHEN '2' THEN 'FECHADA'
        WHEN '3' THEN 'CANCELADA'
    END AS [SITUACAO TIQUETE],

    E115CES.PLAVEI AS [PLACA CAVALO],
    E115CES.CODFOR AS [COD. FORNECEDOR],
    E095FOR.APEFOR AS [NOME FORNECEDOR],
    E115CES.CODTRA AS [COD. TRANSPORTADORA],
    E073TRA.NOMTRA AS [NOME TRANSPORTADORA],
    E115CES.NOMMOT AS [NOME MOTORISTA],
    E115CES.PESENC AS [PESO ENTRADA],
    E115CES.PESSAI AS [PESO SAIDA],
    E115PRO.bruinf AS [PESO LIQUIDO],
    E115PRO.codpro AS [COD. PRODUTO],
    E075PRO.DESPRO AS [DESCRICAO PRODUTO],
    E115CES.USU_NUMLOT AS [CODIGO LOTE],
    E115CES.OBSEMB AS [OBSERVACAO TIQUETE]

FROM SAPIENS.SAPIENS.E115CES WITH (NOLOCK)

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK)
ON E115CES.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK)
ON E115CES.CODEMP = E070FIL.CODEMP
AND E115CES.CODFIL = E070FIL.CODFIL

LEFT OUTER JOIN SAPIENS.SAPIENS.E095FOR WITH (NOLOCK)
ON E115CES.CODFOR = E095FOR.CODFOR

LEFT OUTER JOIN SAPIENS.SAPIENS.E073TRA WITH (NOLOCK)
ON E115CES.CODTRA = E073TRA.CODTRA

LEFT OUTER JOIN SAPIENS.SAPIENS.E115PRO WITH (NOLOCK)
ON E115CES.CODEMP = E115PRO.CODEMP  
AND E115CES.CODFIL = E115PRO.CODFIL
AND E115CES.DATENT = E115PRO.DATENT  
AND E115CES.SEQENT = E115PRO.SEQENT

LEFT OUTER JOIN SAPIENS.SAPIENS.E075PRO WITH (NOLOCK)
ON E075PRO.CODEMP = E115PRO.CODEMP 
AND E075PRO.CODPRO = E115PRO.CODPRO 

LEFT OUTER JOIN SAPIENS.SAPIENS.R999USU E WITH (NOLOCK)
ON E115CES.USUENT = E.CODUSU

LEFT OUTER JOIN SAPIENS.SAPIENS.R999USU S WITH (NOLOCK)
ON E115CES.USUSAI = S.CODUSU

WHERE E070EMP.CODEMP = 5
AND E070FIL.CODFIL = 1
AND E115CES.DATENT >= '01/01/2026'
--AND ((E115CES.SITCES = '1') OR (E115CES.SITCES = '2'))
AND E115CES.ORICES = 4
AND E115CES.USU_TIPTIC = 3
AND E115PRO.codpro IN ('80000001')

GO