SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_PRODUÇÃO] 
AS WITH _ALIMENTAÇÃO AS (
SELECT
 ALIMENTACAO.DATAREF AS 'DATA'
 ,PLANTA.IDEMPRESA AS 'ID EMPRESA'
 ,ALIMENTACAO.IDPLANTA AS 'ID PLANTA'
 ,UPPER(PLANTA.DESCRICAO) AS 'PLANTA'
 ,UPPER(EMPRESA.DESCRICAO) AS 'EMPRESA'
 ,ALIMENTACAO.IDPLANTATURNO AS 'ID TURNO'
 ,UPPER(PLANTATURNO.DESCRICAO) AS 'TURNO'
 ,ALIMENTACAOPRODUTO.IDGRUPOMATERIAL AS 'ID GRUPO MATERIAL'
 ,UPPER(GRUPOMATERIAL.DESCRICAO) AS 'GRUPO MATERIAL'
 ,SUM(ALIMENTACAOPRODUTO.VALOR * ((100-ISNULL(ALIMENTACAOPRODUTO.UMIDADE,0))/100)) '#PRODUÇÃO'
 ,SUM((ALIMENTACAO.Alimentacao * ((100-isnull(ALIMENTACAO.umidade,0))/100))+(ALIMENTACAO.AlimentacaoFino * ((100-isnull(ALIMENTACAO.umidadeFino,0))/100))) '#ALIMENTAÇÃO TN'
 ,MAX(PlantaHorasProgramadas.Horas) '#HORAS PROGRAMADAS'

FROM RajaMine.dbo.ALIMENTACAO WITH (NOLOCK)

INNER JOIN RajaMine.dbo.PLANTA WITH (NOLOCK)
  ON ALIMENTACAO.IDPLANTA = PLANTA.ID
INNER JOIN RajaMine.dbo.PLANTATURNO WITH (NOLOCK)
  ON ALIMENTACAO.IDPLANTATURNO = PLANTATURNO.ID
INNER JOIN RajaMine.dbo.EMPRESA WITH (NOLOCK)
  ON PLANTA.IDEMPRESA = EMPRESA.ID
INNER JOIN RajaMine.dbo.ALIMENTACAOPRODUTO WITH (NOLOCK)
  ON ALIMENTACAOPRODUTO.IDALIMENTACAO = ALIMENTACAO.ID

LEFT JOIN RajaMine.dbo.GRUPOMATERIAL
  ON ALIMENTACAOPRODUTO.IDGRUPOMATERIAL = GRUPOMATERIAL.ID

LEFT JOIN RajaMine.dbo.PlantaHorasProgramadas WITH (NOLOCK)
ON ALIMENTACAO.IDPLANTATURNO = PlantaHorasProgramadas.IdPlantaTurno
AND PLANTA.IDEMPRESA = PlantaHorasProgramadas.IdEmpresa
AND ALIMENTACAO.DATAREF = PlantaHorasProgramadas.Data

--WHERE DATAREF = '2021-05-10'
--AND PLANTA.IDEMPRESA = 3

GROUP BY 
ALIMENTACAO.DATAREF 
 ,PLANTA.IDEMPRESA 
 ,ALIMENTACAO.IDPLANTA
 ,PLANTA.DESCRICAO 
 ,EMPRESA.DESCRICAO 
 ,ALIMENTACAO.IDPLANTATURNO
 ,PLANTATURNO.DESCRICAO 
 ,ALIMENTACAOPRODUTO.IDGRUPOMATERIAL 
 ,GRUPOMATERIAL.DESCRICAO ),

_AMOSTRAS AS (
SELECT

AMOSTRA.IdEmpresa 'ID EMPRESA'
,UPPER(EMPRESA.DESCRICAO) 'EMPRESA'
,AMOSTRA.DATA 'DATA'
,AMOSTRA.IDPLANTATURNO 'ID TURNO'
,AMOSTRA.IDPLANTA 'ID PLANTA'
,MATERIAL.IDGRUPOMATERIAL 'ID GRUPO MATERIAL'
,SUM(ISNULL(AMOSTRA.MASSA, 0)) '#VOLUME'
,SUM(ISNULL(AMOSTRA.MASSA, 0) * ISNULL(AMOSTRA.EL1, 0))/SUM(ISNULL(AMOSTRA.MASSA, 0)) '#FERRO'
,SUM(ISNULL(AMOSTRA.MASSA, 0) * ISNULL(AMOSTRA.EL2, 0))/SUM(ISNULL(AMOSTRA.MASSA, 0))  '#SIO2'
,SUM(ISNULL(AMOSTRA.MASSA, 0) * ISNULL(AMOSTRA.EL3, 0))/SUM(ISNULL(AMOSTRA.MASSA, 0))  '#FÓSFORO'
,SUM(ISNULL(AMOSTRA.MASSA, 0) * ISNULL(AMOSTRA.EL4, 0))/SUM(ISNULL(AMOSTRA.MASSA, 0))  '#MANGANÊS'
FROM RajaMine.dbo.AMOSTRA WITH (NOLOCK)
INNER JOIN RajaMine.dbo.PILHA WITH (NOLOCK)
ON AMOSTRA.IDPILHA = PILHA.ID 
INNER JOIN RajaMine.dbo.EMPRESA WITH (NOLOCK) ON AMOSTRA.IDEMPRESA = EMPRESA.ID
LEFT JOIN RajaMine.dbo.MATERIAL WITH (NOLOCK) ON AMOSTRA.IDMATERIAL = MATERIAL.ID

WHERE AMOSTRA.REPROCESSAMENTO = 'N'


GROUP BY 
AMOSTRA.IDEMPRESA
,EMPRESA.DESCRICAO 
,AMOSTRA.DATA
,AMOSTRA.IDPLANTATURNO
,AMOSTRA.IDPLANTA 
,MATERIAL.IDGRUPOMATERIAL )


SELECT 
GETDATE() AS 'ATUALIZACAO',
CONCAT_WS('-',_ALIMENTAÇÃO.[ID EMPRESA],_ALIMENTAÇÃO.[ID PLANTA], _ALIMENTAÇÃO.[ID TURNO],_ALIMENTAÇÃO.[ID GRUPO MATERIAL],FORMAT(_ALIMENTAÇÃO.DATA,'yyyymmdd')) 'KEY ITEM',
CONCAT_WS('-',_ALIMENTAÇÃO.[ID EMPRESA],_ALIMENTAÇÃO.[ID PLANTA], _ALIMENTAÇÃO.[ID TURNO],CONVERT(varchar(8), _ALIMENTAÇÃO.DATA, 112)) 'KEY PLANTA TURNO',
_ALIMENTAÇÃO.*,

_AMOSTRAS.[#FERRO],

_ALIMENTAÇÃO.#PRODUÇÃO*(_AMOSTRAS.[#FERRO]/100) '#VOLUME FERRO',
_AMOSTRAS.[#SIO2],
_ALIMENTAÇÃO.#PRODUÇÃO*(_AMOSTRAS.[#SIO2]/100) '#VOLUME SIO2',
_AMOSTRAS.[#FÓSFORO],
_ALIMENTAÇÃO.#PRODUÇÃO*(_AMOSTRAS.[#FÓSFORO]/100) '#VOLUME FÓSFORO',
_AMOSTRAS.[#MANGANÊS],
_ALIMENTAÇÃO.#PRODUÇÃO*(_AMOSTRAS.[#MANGANÊS]/100) '#VOLUME MANGANÊS'
FROM _ALIMENTAÇÃO

LEFT JOIN _AMOSTRAS

ON _ALIMENTAÇÃO.[ID EMPRESA] = _AMOSTRAS.[ID EMPRESA]
AND _ALIMENTAÇÃO.DATA = _AMOSTRAS.DATA
AND _ALIMENTAÇÃO.[ID PLANTA] = _AMOSTRAS.[ID PLANTA]
AND _ALIMENTAÇÃO.[ID TURNO] = _AMOSTRAS.[ID TURNO]
AND _ALIMENTAÇÃO.[ID GRUPO MATERIAL] = _AMOSTRAS.[ID GRUPO MATERIAL]
GO