SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_RATEIO_CSC_CPA] AS

SELECT  
    'MIB' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E501TCP.CODEMP AS [COD. EMPRESA],
    NOMEMP AS [NOME EMPRESA],
    E501TCP.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL], 
    UPPER(LEFT(DATENAME(MONTH, DATGER), 3)) AS MES, 
    FORMAT(DATGER, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE CPA] 
FROM SAPIENS.SAPIENS.E501TCP WITH (NOLOCK) 

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK) 
ON E501TCP.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK) 
ON E501TCP.CODEMP = E070FIL.CODEMP
AND E501TCP.CODFIL = E070FIL.CODFIL

WHERE DATGER >= '2025-01-01'

GROUP BY 
    E501TCP.CODEMP,
    NOMEMP,
    E501TCP.CODFIL,
    NOMFIL,
    DATENAME(month, DATGER),
	  FORMAT(DATGER, 'yyyy-MM'),
    MONTH(DATGER) -- Agrupar pelo número também garante a ordem correta

UNION ALL

SELECT  
    'MML' AS SERVIDOR,
    GETDATE() AS ATUALIZACAO,
    E501TCP.CODEMP AS [COD. EMPRESA],
    NOMEMP AS [NOME EMPRESA],
    E501TCP.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(MONTH, DATGER), 3)) AS MES, 
    FORMAT(DATGER, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE CPA] 
FROM [SQLMML].[Sapiens_Prod].[dbo].[E501TCP] WITH (NOLOCK)
 
LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK) 
ON E501TCP.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070FIL] WITH (NOLOCK) 
ON E501TCP.CODEMP = E070FIL.CODEMP
AND E501TCP.CODFIL = E070FIL.CODFIL

WHERE DATGER >= '2025-01-01'

GROUP BY 
    E501TCP.CODEMP,
    NOMEMP,
    E501TCP.CODFIL,
    NOMFIL,
    DATENAME(month, DATGER),
	  FORMAT(DATGER, 'yyyy-MM'),
    MONTH(DATGER) -- Agrupar pelo número também garante a ordem correta
GO