SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_OS_TEMPO] 
AS SELECT
CONCAT_WS('-',ORDSERV.CODEMP,ORDSERV.CODFIL,ORDSERV.CODORD ) 'KEY OS'
,ORDSERV.CODEMP 'COD EMPRESA'
,ORDSERV.CODORD 'COD OS'
,ORDSERV.CODFIL 'COD FILIAL'
,ORDSERV.TAG 'TAG OS'
,ISNULL(ORDSERV.HHPRE, 0) '#HH PREVISTO'   /*RESUMO GERENCIAL - TEMPO PREVISTO DE MÃO-DE-OBRA*/
,ISNULL((SELECT
SUM(ISNULL(CAST(OXF.DATHORFIM - OXF.DATHORINI AS FLOAT), 0) * 24)
FROM Engeman.Engeman.ORDXFUN OXF WITH (NOLOCK)
WHERE OXF.CODORD = ORDSERV.CODORD
AND OXF.CODEMP = ORDSERV.CODEMP
AND OXF.PREVISTO = 'R')
, 0) '#HH REAL'  /*RESUMO GERENCIAL - TEMPO REAL DE MÃO-DE-OBRA*/
,ISNULL(CAST(ORDSERV.MAQFUNPRE - ORDSERV.MAQPARPRE AS FLOAT) * 24, 0) '#TEMPO PARADA PREVISTO' /*RESUMO GERENCIAL - TEMPO PREVISTO DE APLIC. PARADA*/
,ISNULL((SELECT
SUM(CAST(OXP.MAQFUN - OXP.MAQPAR AS FLOAT)) * 24
FROM Engeman.Engeman.ORDXPAR OXP WITH (NOLOCK)
WHERE OXP.CODORD = ORDSERV.CODORD
AND OXP.CODEMP = ORDSERV.CODEMP)
, 0)+ISNULL(CAST(ORDSERV.MAQFUN - ORDSERV.MAQPAR AS FLOAT) * 24, 0) '#TEMPO PARADA REAL' /*RESUMO GERENCIAL - TEMPO REAL DE APLIC. PARADA*/
,ISNULL(ORDSERV.HORINTPRE, 0) '#TEMPO PREVISTO INTERFERÊNCIA' /*RESUMO GERENCIAL - TEMPO PREVISTO DE INTERFERÊNCIA*/
,ISNULL(ORDSERV.HORINTREA, 0) '#TEMPO REAL INTERFERÊNCIA' /*RESUMO GERENCIAL - TEMPO REAL DE INTERFERÊNCIA*/


FROM Engeman.Engeman.ORDSERV WITH (NOLOCK)
GO