SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_EQUIPAMENTOS_ENGEMAN] 
AS SELECT DISTINCT
'MIB' AS 'SERVIDOR',
CONCAT('MIB-',APLIC.CODAPL) 'COD EQUIPAMENTO',
UPPER(APLIC.DESCRICAO) 'EQUIPAMENTO',
Equipamento.Id 'ID RAJAMINE',
UPPER(Equipamento.Descricao) 'EQUIPAMENTO RAJAMNINE',
UPPER(APLIC.MODELO) 'MODELO',
APLIC.TAG 'TAG',
TIPAPLIC.DESCRICAO 'TIPO',
APLIC.CODCEN 'COD CR',
UPPER(CENCUS.DESCRICAO) 'CENTRO DE CUSTO',
APLIC.VALORCOMPRA '#VALOR COMPRA',
CAST(APLIC.DATAQU AS DATE) 'DATA AQUISIÇÃO',
DATEDIFF(YEAR,APLIC.DATAQU, GETDATE()) + CASE WHEN (MONTH(APLIC.DATAQU) > MONTH(GETDATE()) OR (MONTH(APLIC.DATAQU) = MONTH(GETDATE()) AND DAY(APLIC.DATAQU) > DAY(GETDATE()))) THEN -1 ELSE 0 END AS 'IDADE APLICAÇÃO',
CONCAT_WS('-','MIB',APLIC.CODEMP,APLIC.CODFIL) 'KEY FILIAL',


--CASE 
--WHEN CHARINDEX('PIPA',TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
--WHEN CHARINDEX('MOTONIVELADORA', TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
--
--ELSE 'SIM' END AS 'PRINCIPAIS',
--
--CASE 
--WHEN CHARINDEX('CAMINHÃO',TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('MOTONIVELADORA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('ESCAVADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('CARREGADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--ELSE 'NÃO' END AS 'CONTROLA'

CASE 
WHEN CHARINDEX('MUNCK',TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
WHEN CHARINDEX('PIPA',TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
WHEN CHARINDEX('MOTONIVELADORA', TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'

WHEN CHARINDEX('BROOKS',TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
WHEN CHARINDEX('CAMINHÃO',TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
WHEN CHARINDEX('ESCAVADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
WHEN CHARINDEX('CARREGADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'

ELSE 'NÃO' END AS 'PRINCIPAIS'





FROM Engeman.Engeman.APLIC WITH (NOLOCK)

LEFT JOIN Engeman.Engeman.TIPAPLIC WITH (NOLOCK)
ON APLIC.CODTIPAPL = TIPAPLIC.CODTIPAPL

LEFT JOIN Engeman.Engeman.CENCUS  WITH (NOLOCK)
ON APLIC.CODCEN = CENCUS.CODCEN

LEFT JOIN Engeman.Engeman.MODDES ON APLIC.CODMOD = MODDES.CODMOD

LEFT JOIN EQUIPAMENTOS_ENGEMAN_X_RAJAMINE WITH (NOLOCK)
ON APLIC.CODAPL = EQUIPAMENTOS_ENGEMAN_X_RAJAMINE.[ID ENGEMAN]
AND 'MIB' = EQUIPAMENTOS_ENGEMAN_X_RAJAMINE.[SERVIDOR]

LEFT JOIN  RajaMine.dbo.Equipamento WITH (NOLOCK)
ON EQUIPAMENTOS_ENGEMAN_X_RAJAMINE.[ID RAJAMINE] =  Equipamento.Id --COLLATE Latin1_General_CI_AS

--WHERE APLIC.ATIVO = 'S'


UNION ALL


SELECT DISTINCT
'MML' AS 'SERVIDOR',
CONCAT('MML-',APLIC.CODAPL) 'COD EQUIPAMENTO',
UPPER(APLIC.DESCRICAO) 'EQUIPAMENTO',
Equipamento.Id 'ID RAJAMINE',
UPPER(Equipamento.Descricao) 'EQUIPAMENTO RAJAMNINE',
UPPER(APLIC.MODELO) 'MODELO',
APLIC.TAG 'TAG',
TIPAPLIC.DESCRICAO 'TIPO',
APLIC.CODCEN 'COD CR',
UPPER(CENCUS.DESCRICAO) 'CENTRO DE CUSTO',
APLIC.VALORCOMPRA '#VALOR COMPRA',
CAST(APLIC.DATAQU AS DATE) 'DATA AQUISIÇÃO',
DATEDIFF(YEAR,APLIC.DATAQU, GETDATE()) + CASE WHEN (MONTH(APLIC.DATAQU) > MONTH(GETDATE()) OR (MONTH(APLIC.DATAQU) = MONTH(GETDATE()) AND DAY(APLIC.DATAQU) > DAY(GETDATE()))) THEN -1 ELSE 0 END AS 'IDADE APLICAÇÃO',
CONCAT_WS('-','MML',APLIC.CODEMP,APLIC.CODFIL) 'KEY FILIAL',

--CASE 
--WHEN CHARINDEX('PIPA',TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
--WHEN CHARINDEX('MOTONIVELADORA', TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
--
--ELSE 'SIM' END AS 'PRINCIPAIS',
--
--CASE 
--WHEN CHARINDEX('CAMINHÃO',TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('MOTONIVELADORA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('ESCAVADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('CARREGADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
--ELSE 'NÃO' END AS 'CONTROLA'

CASE 
WHEN CHARINDEX('MUNCK',TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
WHEN CHARINDEX('PIPA',TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'
WHEN CHARINDEX('MOTONIVELADORA', TIPAPLIC.DESCRICAO) > 0 THEN 'NÃO'

WHEN CHARINDEX('BROOKS',TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
WHEN CHARINDEX('CAMINHÃO',TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
WHEN CHARINDEX('ESCAVADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'
WHEN CHARINDEX('CARREGADEIRA', TIPAPLIC.DESCRICAO) > 0 THEN 'SIM'

ELSE 'NÃO' END AS 'PRINCIPAIS'

FROM [SQLMML].[ENGEMAN].[engeman].[APLIC] WITH (NOLOCK)

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[TIPAPLIC] WITH (NOLOCK)
ON APLIC.CODTIPAPL = TIPAPLIC.CODTIPAPL

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CENCUS]  WITH (NOLOCK)
ON APLIC.CODCEN = CENCUS.CODCEN

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[MODDES] ON APLIC.CODMOD = MODDES.CODMOD

LEFT JOIN EQUIPAMENTOS_ENGEMAN_X_RAJAMINE WITH (NOLOCK)
ON APLIC.CODAPL = EQUIPAMENTOS_ENGEMAN_X_RAJAMINE.[ID ENGEMAN]
AND 'MML' = EQUIPAMENTOS_ENGEMAN_X_RAJAMINE.[SERVIDOR]

LEFT JOIN  RajaMine.dbo.Equipamento WITH (NOLOCK)
ON EQUIPAMENTOS_ENGEMAN_X_RAJAMINE.[ID RAJAMINE] =  Equipamento.Id --COLLATE Latin1_General_CI_AS

--WHERE APLIC.ATIVO = 'S'
GO