SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_RATEIO_CSC_NFS] AS

SELECT 
    'MIB' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E140NFV.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E140NFV.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATEMI), 3)) AS MES, 
    FORMAT(DATEMI, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE NFS] 
FROM SAPIENS.SAPIENS.E140NFV WITH (NOLOCK)  

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK) 
ON E140NFV.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK) 
ON E140NFV.CODEMP = E070FIL.CODEMP
AND E140NFV.CODFIL = E070FIL.CODFIL

WHERE DATEMI >= '01/01/2025'
GROUP BY 
    E140NFV.CODEMP,
    NOMEMP,
    E140NFV.CODFIL,
    NOMFIL,
    DATENAME(month, DATEMI),
    FORMAT(DATEMI, 'yyyy-MM'),
    MONTH(DATEMI) -- Agrupar pelo número também garante a ordem correta

UNION ALL

SELECT 
    'MML' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E140NFV.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E140NFV.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATEMI), 3)) AS MES, 
    FORMAT(DATEMI, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE NFS] 
FROM [SQLMML].[Sapiens_Prod].[dbo].[E140NFV] WITH (NOLOCK) 

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK) 
ON E140NFV.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070FIL] WITH (NOLOCK) 
ON E140NFV.CODEMP = E070FIL.CODEMP
AND E140NFV.CODFIL = E070FIL.CODFIL
  
WHERE DATEMI >= '01/01/2025'
GROUP BY 
    E140NFV.CODEMP,
    NOMEMP,
    E140NFV.CODFIL,
    NOMFIL,
    DATENAME(month, DATEMI),
    FORMAT(DATEMI, 'yyyy-MM'),
    MONTH(DATEMI) -- Agrupar pelo número também garante a ordem correta

GO