SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_CALENDÁRIO] 
AS SELECT
ROW_NUMBER() OVER (ORDER BY _DATA.DATA)  'ID',
CAST(_DATA.DATA AS DATE) 'DATA',

CONVERT(CHAR(6), DATEADD(MONTH,-1,_DATA.DATA), 112) 'PERÍODO ANTERIOR',
FORMAT (_DATA.DATA, 'dd/MM/yy') 'DATA REDUZIDA',
CONCAT_WS('/',
RIGHT(CAST(CAST(_DATA.DATA AS DATE) AS VARCHAR),2),
SUBSTRING(CAST(CAST(_DATA.DATA AS DATE) AS VARCHAR),6,2),
LEFT(CAST(CAST(_DATA.DATA AS DATE) AS VARCHAR),4)) 'DATA TEXTO',
CONCAT_WS('-',IIF(MONTH(DATA)<10,CAST(CONCAT('0',MONTH(DATA)) AS VARCHAR),CAST(MONTH(DATA) AS VARCHAR)),
IIF(DATEPART(DAY,_DATA.DATA)<10,CAST(CONCAT('0',DATEPART(DAY,_DATA.DATA)) AS VARCHAR),CAST(DATEPART(DAY,_DATA.DATA) AS VARCHAR))) 'MÊS DIA',
IIF(CONVERT(CHAR(6), _DATA.DATA, 112) = CONVERT(CHAR(6), DATEADD(MONTH,-1,GETDATE()), 112),'SIM', 'NÃO') 'MÊS ANTERIOR',
DATEPART(DAY,_DATA.DATA) 'DIA DO MÊS',
CONVERT(CHAR(6), DATA, 112) 'PERÍODO',
EOMONTH(DATA) 'FIM DO MÊS',
IIF(CAST(_DATA.DATA AS DATE) =CAST(GETDATE() AS DATE),'SIM','NÃO') 'HOJE',
CONCAT(DATEPART(QUARTER, _DATA.DATA),'º TRIMESTRE') 'TRIMESTRE',
CONCAT_WS('-',YEAR(_DATA.DATA),IIF(DATEPART(WK,_DATA.DATA)<10,CONCAT('0',CAST(DATEPART(WK,DATA) AS VARCHAR)),CAST(DATEPART(WK,_DATA.DATA) AS VARCHAR))) 'SEMANA DO ANO',
CONCAT(CONCAT(DATEPART(QUARTER, _DATA.DATA),'º TRI '),RIGHT(CAST(YEAR(DATA) AS VARCHAR),2)) 'TRIMESTRE ANO',
CONCAT(RIGHT(CAST(YEAR(DATA) AS VARCHAR),2),DATEPART(QUARTER, _DATA.DATA)) 'TRI ANO',
CAST(DATEADD(month, DATEDIFF(month, 0, DATA), 0) AS DATE) 'INÍCIO DO MÊS',
YEAR(DATA) 'ANO',
IIF(YEAR(DATA)=YEAR(GETDATE()),'SIM','NÃO') 'ANO PRESENTE',

IIF(YEAR(DATA)<=(YEAR(GETDATE())-3),'NÃO',
IIF(YEAR(DATA)>=(YEAR(GETDATE())+2),'NÃO',
'SIM')) 'ANO FILTRO',

MONTH(DATA) 'MÊS NUMÉRICO',
CASE MONTH(DATA) 
WHEN 1 THEN 'JANEIRO' 
WHEN 2 THEN 'FEVEREIRO' 
WHEN 3 THEN 'MARÇO' 
WHEN 4 THEN 'ABRIL' 
WHEN 5 THEN 'MAIO'
WHEN 6 THEN 'JUNHO'
WHEN 7 THEN 'JULHO'
WHEN 8 THEN 'AGOSTO'
WHEN 9 THEN 'SETEMBRO'
WHEN 10 THEN 'OUTUBRO'
WHEN 11 THEN 'NOVEMBRO'
WHEN 12 THEN 'DEZEMBRO'
ELSE NULL END AS 'MÊS',
CASE MONTH(DATA) 
WHEN 1 THEN 'JAN' 
WHEN 2 THEN 'FEV' 
WHEN 3 THEN 'MAR' 
WHEN 4 THEN 'ABR' 
WHEN 5 THEN 'MAI'
WHEN 6 THEN 'JUN'
WHEN 7 THEN 'JUL'
WHEN 8 THEN 'AGO'
WHEN 9 THEN 'SET'
WHEN 10 THEN 'OUT'
WHEN 11 THEN 'NOV'
WHEN 12 THEN 'DEZ'
ELSE NULL END AS 'MÊS ABREVIADO',
CONCAT_WS('-',
CASE MONTH(DATA) 
WHEN 1 THEN 'JAN' 
WHEN 2 THEN 'FEV' 
WHEN 3 THEN 'MAR' 
WHEN 4 THEN 'ABR' 
WHEN 5 THEN 'MAI'
WHEN 6 THEN 'JUN'
WHEN 7 THEN 'JUL'
WHEN 8 THEN 'AGO'
WHEN 9 THEN 'SET'
WHEN 10 THEN 'OUT'
WHEN 11 THEN 'NOV'
WHEN 12 THEN 'DEZ'
ELSE NULL END, RIGHT(CAST(YEAR(DATA) AS VARCHAR),2)) 'MÊS ANO ABREVIADO',
CONCAT_WS('-', RIGHT(CAST(YEAR(DATA) AS VARCHAR),2),
CASE MONTH(DATA) 
WHEN 1 THEN 'JAN' 
WHEN 2 THEN 'FEV' 
WHEN 3 THEN 'MAR' 
WHEN 4 THEN 'ABR' 
WHEN 5 THEN 'MAI'
WHEN 6 THEN 'JUN'
WHEN 7 THEN 'JUL'
WHEN 8 THEN 'AGO'
WHEN 9 THEN 'SET'
WHEN 10 THEN 'OUT'
WHEN 11 THEN 'NOV'
WHEN 12 THEN 'DEZ'
ELSE NULL END) 'ANO MÊS ABREVIADO',


CASE 
WHEN CAST(DATEADD(month, DATEDIFF(month, 0, DATA), 0) AS DATE)  = CAST(DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0) AS DATE) THEN 'PRESENTE'
WHEN CAST(DATEADD(month, DATEDIFF(month, 0, DATA), 0) AS DATE) <  CAST(DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0) AS DATE) THEN 'PASSADO'
WHEN CAST(DATEADD(month, DATEDIFF(month, 0, DATA), 0) AS DATE)  > CAST(DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0) AS DATE) THEN 'FUTURO'
ELSE 'VERIFICAR' END AS 'MÊS PRESENTE',



CASE 
WHEN CAST(DATA AS DATE) = CAST( GETDATE() AS DATE) THEN 'PRESENTE'
WHEN CAST(DATA AS DATE) < CAST( GETDATE() AS DATE) THEN 'PASSADO'
WHEN CAST(DATA AS DATE) > CAST( GETDATE() AS DATE) THEN 'FUTURO'
ELSE 'VERIFICAR' END AS 'QUANDO'

FROM(
SELECT  TOP (DATEDIFF(DAY, '20060101', DATEADD(YEAR,5, GETDATE())) + 1)
        DATA= DATEADD(DAY, ROW_NUMBER() OVER(ORDER BY a.object_id) - 1, '20100101')
FROM    sys.all_objects a
        CROSS JOIN sys.all_objects b) _DATA
GO