SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_NFE_CSC_EDOCS] AS

SELECT 
    'MIB' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E440NFC.CODEMP AS [COD.EMPRESA - NFE], 
    E440NFC.CODFOR AS [COD. FORNECEDOR - NFE], 
    E095FOR.NOMFOR AS [NOME FORNECEDOR - NFE],
    CGCCPF AS [CGC FORNECEDOR - NFE], 
    NUMNFC AS [N° NOTA FISCAL - NFE], 
    CODSNF AS [COD. SERIE - NFE], 
    DATENT AS [DATA ENTRADA - NFE], 
    E440NFC.DATEMI AS [DATA EMISSAO - NFE],  
    TNSPRO AS [TRANSACAO PRODUTO - NFE], 
    TNSSER AS [TRANSACAO SERVICO - NFE], 
    VLRLIQ AS [VALOR LIQUIDO - NFE], 
    NUMLOT AS [N° LOTE CONTABIL - NFE], 
    SITNFC AS [SITUACAO - NFE], 
    N.SEQFIL AS [CGC EMPRESA/FILIAL - REC], 
    N.NUMNFE AS [N° NFE - REC], 
    N.TOTNFE AS [VALOR NFE - REC], 
    N.DATEMI AS [DATA EMISSAO - REC], 
    N.CNPEMI AS [CGC FORNECEDOR - REC], 
    N.NOMEMI AS [NOME FORNECEDOR - REC]

FROM SAPIENS.SAPIENS.E440NFC (NOLOCK)

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP (NOLOCK)
ON E440NFC.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL (NOLOCK)
ON E440NFC.CODEMP = E070FIL.CODEMP
AND E440NFC.CODFIL = E070FIL.CODFIL

LEFT OUTER JOIN SAPIENS.SAPIENS.E095FOR (NOLOCK)
ON E440NFC.CODFOR = E095FOR.CODFOR

LEFT OUTER JOIN EDOCS.DBO.N130NFE N (NOLOCK)
ON E070FIL.NUMCGC = N.SEQFIL
AND E440NFC.NUMNFC = N.NUMNFE
AND E095FOR.CGCCPF = N.CNPEMI

WHERE E440NFC.DATEMI >= '2026-01-01'
--E440NFC.NUMNFC = 39510
--AND E095FOR.CGCCPF = '8185361000161'  
--AND E440NFC.DATEMI = '2018/03/29'

GO