SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_PRODUÇÃO_METAS_MATERIAL] AS

SELECT
CONCAT_WS('-',PLANTA.IDEMPRESA,PLANTA.ID,PLANTATURNO.ID,PLANTAXPLANTAHORASPROGRAMADASMATERIAL.IDMATERIAL,CONVERT(varchar(8), PLANTAHORASPROGRAMADAS.DATA, 112)) 'KEY ITEM'
,CONCAT_WS('-',PLANTA.IDEMPRESA,PLANTA.ID,PLANTATURNO.ID,CONVERT(varchar(8), PLANTAHORASPROGRAMADAS.DATA, 112)) 'KEY PLANTA TURNO'
,PLANTAHORASPROGRAMADAS.DATA 'DATA'
,PLANTA.ID 'ID PLANTA'
,UPPER(PLANTA.DESCRICAO) 'PLANTA'
,PLANTA.IDEMPRESA 'ID EMPRESA'
,UPPER(EMPRESA.DESCRICAO)  'EMPRESA'
,PLANTATURNO.ID 'ID TURNO'
,UPPER(PLANTATURNO.DESCRICAO) 'TURNO'
,PLANTAXPLANTAHORASPROGRAMADASMATERIAL.IDMATERIAL 'ID MATERIAL'
,UPPER(MATERIAL.DESCRICAO) 'MATERIAL'
,MATERIAL.IDGRUPOMATERIAL 'ID GRUPO MATERIAL'
,UPPER(GRUPOMATERIAL.DESCRICAO) 'GRUPO MATERIAL'
,PLANTAHORASPROGRAMADAS.HORAS '#HORAS PROGRAMADAS'
,PLANTATURNOMETA.METADF '#DF'
,PLANTATURNOMETA.METAIU  '#IU'
,PLANTATURNOMETA.METARE '#RE'
,PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100 '#RECUPERAÇÃO PCT'
,PLANTAXPLANTAHORASPROGRAMADAS.METAALIMENTACAO*ISNULL((PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100),1) '#META ALIMENTAÇÃO'
, _MEDIA_METAS.[META ALIMENTAÇÃO MÉDIA]*ISNULL((PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100),1) '#META ALIMENTAÇÃO MÉDIA'
,PLANTAXPLANTAHORASPROGRAMADAS.METAPRODUCAO*ISNULL((PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100),1) '#META PRODUÇÃO'
,_MEDIA_METAS.[META PRODUÇÃO MÉDIA]*ISNULL((PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100),1) '#META PRODUÇÃO MÉDIA'
,PLANTAXPLANTAHORASPROGRAMADAS.METAALIMENTACAOHORA*ISNULL((PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100),1) '#META ALIMENTAÇÃO HORA'
,PLANTATURNOMETA.PRODUCAOHORA*ISNULL((PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100),1) '#META PRODUÇÃO HORA TURNO'
,PLANTATURNOMETA.ALIMENTACAOHORA*ISNULL((PLANTAXPLANTAHORASPROGRAMADASMATERIAL.PERCENTUALRECUPERACAO/100),1) '#META ALIMENTAÇÃO HORA TURNO'




,_MEDIA_METAS.[META PRODUÇÃO MÉDIA]/COUNT(*) OVER (PARTITION BY CONCAT_WS('-',PLANTA.IDEMPRESA,PLANTA.ID,PLANTATURNO.ID,CONVERT(varchar(8), PLANTAHORASPROGRAMADAS.DATA, 112))) '#META PRODUÇÃO MÉDIA TOTAL'
,_MEDIA_METAS.[META ALIMENTAÇÃO MÉDIA]/COUNT(*) OVER (PARTITION BY CONCAT_WS('-',PLANTA.IDEMPRESA,PLANTA.ID,PLANTATURNO.ID,CONVERT(varchar(8), PLANTAHORASPROGRAMADAS.DATA, 112))) '#META ALIMENTAÇÃO MÉDIA TOTAL'
,PLANTAXPLANTAHORASPROGRAMADAS.METAALIMENTACAO/COUNT(*) OVER (PARTITION BY CONCAT_WS('-',PLANTA.IDEMPRESA,PLANTA.ID,PLANTATURNO.ID,CONVERT(varchar(8), PLANTAHORASPROGRAMADAS.DATA, 112))) '#META ALIMNETAÇÃO TOTAL'
,PLANTAXPLANTAHORASPROGRAMADAS.METAPRODUCAO/COUNT(*) OVER (PARTITION BY CONCAT_WS('-',PLANTA.IDEMPRESA,PLANTA.ID,PLANTATURNO.ID,CONVERT(varchar(8), PLANTAHORASPROGRAMADAS.DATA, 112))) '#META PRODUÇÃO TOTAL'

FROM RajaMine.dbo.PLANTA WITH (NOLOCK)

LEFT JOIN RajaMine.dbo.EMPRESA WITH (NOLOCK)
ON PLANTA.IDEMPRESA = EMPRESA.ID


LEFT  JOIN RajaMine.dbo.PLANTAXPLANTAHORASPROGRAMADAS WITH (NOLOCK)
  ON PLANTA.ID = PLANTAXPLANTAHORASPROGRAMADAS.IDPLANTA 

LEFT  JOIN RajaMine.dbo.PLANTAXPLANTAHORASPROGRAMADASMATERIAL  WITH (NOLOCK)
  ON  PLANTAXPLANTAHORASPROGRAMADAS.ID = PLANTAXPLANTAHORASPROGRAMADASMATERIAL.IDPLANTAXPLANTAHORASPROGRAMADAS

LEFT JOIN RajaMine.dbo.MATERIAL  WITH (NOLOCK) 
ON PLANTAXPLANTAHORASPROGRAMADASMATERIAL.IDMATERIAL = MATERIAL.ID

LEFT JOIN RajaMine.dbo.GRUPOMATERIAL  WITH (NOLOCK) 
ON MATERIAL.IDGRUPOMATERIAL = GRUPOMATERIAL.ID 

LEFT JOIN RajaMine.dbo.PLANTAHORASPROGRAMADAS WITH (NOLOCK)
  ON PLANTAXPLANTAHORASPROGRAMADAS.IDPLANTAHORASPROGRAMADAS = PLANTAHORASPROGRAMADAS.ID

LEFT JOIN RajaMine.dbo.PLANTATURNO  WITH (NOLOCK)
  ON PLANTAHORASPROGRAMADAS.IDPLANTATURNO = PLANTATURNO.ID

LEFT JOIN RajaMine.dbo.PLANTATURNOMETA WITH (NOLOCK)
  ON PLANTATURNOMETA.IDPLANTATURNO = PLANTATURNO.ID




LEFT JOIN (


SELECT
php.idempresa 'ID EMPRESA',
php.IDPLANTATURNO 'ID TURNO'
,CAST(DATEADD(month, DATEDIFF(month, 0, php.Data), 0) AS DATE) 'MÊS'

 ,AVG(ppp.MetaProducao) 'META PRODUÇÃO MÉDIA'
 ,AVG(ppp.MetaAlimentacao) 'META ALIMENTAÇÃO MÉDIA'
FROM RajaMine.dbo.PlantaHorasProgramadas php WITH (NOLOCK)
INNER JOIN RajaMine.dbo.PlantaxPlantaHorasProgramadas ppp WITH (NOLOCK)
  ON php.Id = ppp.IdPlantaHorasProgramadas


GROUP BY CAST(DATEADD(month, DATEDIFF(month, 0, php.Data), 0) AS DATE)
        ,php.idempresa
        ,php.IDPLANTATURNO )


_MEDIA_METAS 


ON CAST(DATEADD(month, DATEDIFF(month, 0,PLANTAHORASPROGRAMADAS.DATA), 0) AS DATE) = _MEDIA_METAS.MÊS
AND PLANTA.IDEMPRESA = _MEDIA_METAS.[ID EMPRESA]
AND PLANTATURNO.ID = _MEDIA_METAS.[ID TURNO]
GO