SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_SERVIÇOS_OS] 
AS SELECT
  CONCAT_WS('-','MIB',REGSERV.CODORD) 'COD OS'
 ,CONCAT_WS('-','MIB',REGSERV.CODREGSER) 'COD REGISTRO SERVIÇO'
 ,REGSERV.DESCRICAO 'DESCRIÇÃO REGISTRO SERVIÇO'
 ,CONCAT_WS('-','MIB',SERVICO.CODSER) 'COD SERVIÇO'
 ,COALESCE(SERVICO.DESCRICAO, 'NÃO IDENTIFICADO') 'SERVIÇO'
 ,COALESCE(CAUSA.DESCRICAO, 'NÃO IDENTIFICADO')  'CAUSA SERVIÇO'
 ,COALESCE(DEFEITO.DESCRICAO, 'NÃO IDENTIFICADO') 'DEFEITO SERVIÇO'


FROM Engeman.Engeman.REGSERV WITH (NOLOCK)

LEFT JOIN Engeman.Engeman.SERVICO WITH (NOLOCK)
ON REGSERV.CODSER = SERVICO.CODSER

INNER JOIN Engeman.Engeman.ORDSERV WITH (NOLOCK)
ON REGSERV.CODORD = ORDSERV.CODORD

LEFT JOIN Engeman.Engeman.CAUSA  WITH (NOLOCK)
  ON REGSERV.CODCAU = CAUSA.CODCAU
LEFT JOIN Engeman.Engeman.DEFEITO  WITH (NOLOCK)
  ON REGSERV.CODDEF = DEFEITO.CODDEF

WHERE YEAR(ORDSERV.DATGER) >=2024

UNION ALL

SELECT
  CONCAT_WS('-','MML',REGSERV.CODORD) 'COD OS'
 ,CONCAT_WS('-','MML',REGSERV.CODREGSER) 'COD REGISTRO SERVIÇO'
 ,REGSERV.DESCRICAO 'DESCRIÇÃO REGISTRO SERVIÇO'
 ,CONCAT_WS('-','MML',SERVICO.CODSER) 'COD SERVIÇO'
 ,COALESCE(SERVICO.DESCRICAO, 'NÃO IDENTIFICADO') 'SERVIÇO'
 ,COALESCE(CAUSA.DESCRICAO, 'NÃO IDENTIFICADO')  'CAUSA SERVIÇO'
 ,COALESCE(DEFEITO.DESCRICAO, 'NÃO IDENTIFICADO') 'DEFEITO SERVIÇO'


FROM [SQLMML].[ENGEMAN].[engeman].[REGSERV] WITH (NOLOCK)

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[SERVICO] WITH (NOLOCK)
ON REGSERV.CODSER = SERVICO.CODSER

INNER JOIN [SQLMML].[ENGEMAN].[engeman].[ORDSERV] WITH (NOLOCK)
ON REGSERV.CODORD = ORDSERV.CODORD

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CAUSA]  WITH (NOLOCK)
  ON REGSERV.CODCAU = CAUSA.CODCAU
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[DEFEITO]  WITH (NOLOCK)
  ON REGSERV.CODDEF = DEFEITO.CODDEF

WHERE YEAR(ORDSERV.DATGER) >=2024
GO