SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE   VIEW [dbo].[INAT_VW_DESPESAS_CRS] 
AS SELECT 
'MIB' AS 'SERVIDOR',

*,
IIF([DESCONSIDERAR CONTA] ='SIM', NULL, 
 CASE 
        WHEN CHARINDEX('VARIAÇÃO MONETÁRIA  CRÉDITOS DECORRENTES DE AÇÃO JUDICIAL EXCLUSÃO DO ICMS DA BASE DE CÁLCULO DO PIS/COFINS CONF. PROCESSO 0001058-94.2015.4.01.3800', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('ESTORNO DESCONTO SOBRE', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('ENCERRAMENTO DO EXERC', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('CRÉDITOS EXTEMPORÂNEOS', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('ALF CRÉDITOS', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('REFERENTE A TRANSFERENCIA DE CUSTO MINÉRIO', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('REFERENTE A ZERAMENTO DE CUSTO MINÉRIO', [HISTÓRICO]) > 0 THEN NULL
        ELSE [#MOVIMENTO] -- OU OUTRO VALOR PADRÃO CASO NENHUMA CONDIÇÃO SEJA ATENDIDA
    END) '#MOVIMENTO AJUSTADO'

FROM (

SELECT 

CONCAT_WS('-','MIB',E640LCT.CODEMP,E640RAT.CODCCU)  'KEY CR SENIOR',
CONCAT_WS('-','MIB',E640LCT.CODEMP)'COD EMPRESA SENIOR',
UPPER(E070EMP.SIGEMP) 'EMPRESA SENIOR',
E640RAT.CODCCU 'COD CR SENIOR',
UPPER(DESCCU) 'CENTRO RESULTADO SENIOR',
E640RAT.CTARED 'COD CONTA CONTÁBIL',
UPPER(DESCTA) 'CONTA CONTÁBIL',
CAST(E640LCT.DATLCT  AS DATE) 'DATA LANCAMENTO',
IIF( DEBCRE = 'D', 'DÉBITO', 'CRÉDITO') 'TIPO CD',
IIF( DEBCRE = 'D',-1,1)* VLRRAT '#MOVIMENTO',
E640LCT.SITLCT 'COD SITUAÇÃO',
E640LCT.NUMLCT 'SEQUÊNCIA LANÇAMENTO',
CASE LEFT(CLACCU, 2)
WHEN 21 THEN 'ADM'
WHEN 22 THEN 'LAVRA'
WHEN 23 THEN 'PRODUÇÃO'
WHEN 24 THEN 'OFICINA'
WHEN 25 THEN 'M. AMBIENTE' ELSE 'OUTROS'
END 'CLASSIFICAÇÃO'
,E640LCT.SITLCT 'SITUAÇÃO',

TRIM(UPPER(CONCAT(E046HPD.DESHPD,' ',E640LCT.CPLLCT))) 'HISTÓRICO' ,
VW_PLANO_DE_CONTAS.[GRUPO 1],
VW_PLANO_DE_CONTAS.[GRUPO 2],
VW_PLANO_DE_CONTAS.[GRUPO 3],
VW_PLANO_DE_CONTAS.[GRUPO 4],

IIF(CONTAS_DESCONSIDERADAS.[COD CONTA CONTÁBIL] IS NOT NULL, 'SIM','NÃO') 'DESCONSIDERAR CONTA'
 
FROM SAPIENS.SAPIENS.E640LCT  WITH (NOLOCK)
  
LEFT JOIN SAPIENS.SAPIENS.E046HPD  WITH (NOLOCK)
ON E640LCT.CODHPD = E046HPD.CODHPD
 
INNER JOIN SAPIENS.SAPIENS.E640RAT  WITH (NOLOCK)
ON E640LCT.CODEMP = E640RAT.CODEMP
AND E640LCT.NUMLCT = E640RAT.NUMLCT
 
INNER JOIN SAPIENS.SAPIENS.E045PLA  WITH (NOLOCK)
ON E640RAT.CODEMP = E045PLA.CODEMP
AND E640RAT.CTARED = E045PLA.CTARED
 
INNER JOIN SAPIENS.SAPIENS.E044CCU  WITH (NOLOCK)
ON E640RAT.CODEMP = E044CCU.CODEMP
AND E640RAT.CODCCU = E044CCU.CODCCU


LEFT JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK)
ON E640LCT.CODEMP = E070EMP.CODEMP

LEFT JOIN VW_PLANO_DE_CONTAS 
ON E640LCT.CODEMP = VW_PLANO_DE_CONTAS.[COD EMPRESA]
AND E640RAT.CTARED = VW_PLANO_DE_CONTAS.[COD REDUZIDA]
AND 'MIB' = VW_PLANO_DE_CONTAS.[SERVIDOR]

LEFT JOIN CONTAS_DESCONSIDERADAS (NOLOCK)
ON E640LCT.CODEMP = CONTAS_DESCONSIDERADAS.[COD EMPRESA]
AND E640LCT.NUMLCT = CONTAS_DESCONSIDERADAS.[COD CONTA CONTÁBIL]
AND 'MIB' = CONTAS_DESCONSIDERADAS.[SERVIDOR]

WHERE E070EMP.CODEMP = 1
AND LEFT(CLACCU, 2) IN( 22, 24)
AND YEAR(E640LCT.DATLCT) >= 2023

) _MIB


UNION ALL

SELECT 
'MML' AS 'SERVIDOR',
*,
IIF([DESCONSIDERAR CONTA] ='SIM', NULL, 
CASE 
        WHEN CHARINDEX('QUE SE TRANSFERE ENCERRAMENTO DO EXERCICIO.', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('AJUSTE DE TRANSFERÊNCIA CUSTO DE MINÉRIO', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('ZERAMENTO DE CUSTO DE MINÉRIO', [HISTÓRICO]) > 0 THEN NULL
        ELSE [#MOVIMENTO]  -- OU OUTRO VALOR PADRÃO CASO NENHUMA CONDIÇÃO SEJA ATENDIDA
    END) '#MOVIMENTO AJUSTADO'

FROM (

SELECT 

CONCAT_WS('-','MML',E640LCT.CODEMP,E640RAT.CODCCU)  'KEY CR SENIOR',
CONCAT_WS('-','MML',E640LCT.CODEMP)'COD EMPRESA SENIOR',
UPPER(E070EMP.SIGEMP) 'EMPRESA SENIOR',
E640RAT.CODCCU 'COD CR SENIOR',
UPPER(DESCCU) 'CENTRO RESULTADO SENIOR',
E640RAT.CTARED 'COD CONTA CONTÁBIL',
UPPER(DESCTA) 'CONTA CONTÁBIL',
CAST(E640LCT.DATLCT  AS DATE) 'DATA LANCAMENTO',
IIF( DEBCRE = 'D', 'DÉBITO', 'CRÉDITO') 'TIPO CD',
IIF( DEBCRE = 'D',-1,1)* VLRRAT '#MOVIMENTO',
E640LCT.SITLCT 'COD SITUAÇÃO',
E640LCT.NUMLCT 'SEQUÊNCIA LANÇAMENTO',

CASE LEFT(CLACCU,2)
WHEN 11 THEN 'ADM'
WHEN 15 THEN 'PRODUCAO'
WHEN 17 THEN 'APOIO'
WHEN 21 THEN 'ADM'
WHEN 22 THEN 'COMERCIAL'
WHEN 23 THEN 'SUPRIMENTOS'
WHEN 24 THEN 'LAVRA'
WHEN 25 THEN 'PRODUCAO'
WHEN 26 THEN 'OFICINA'
WHEN 27 THEN 'MINERIO' ELSE 'OUTROS'
END 'CLASSIFICAÇÃO'




,E640LCT.SITLCT 'SITUAÇÃO',

TRIM(UPPER(CONCAT(E046HPD.DESHPD,' ',E640LCT.CPLLCT))) 'HISTÓRICO' ,
VW_PLANO_DE_CONTAS.[GRUPO 1],
VW_PLANO_DE_CONTAS.[GRUPO 2],
VW_PLANO_DE_CONTAS.[GRUPO 3],
VW_PLANO_DE_CONTAS.[GRUPO 4],

IIF(CONTAS_DESCONSIDERADAS.[COD CONTA CONTÁBIL] IS NOT NULL, 'SIM','NÃO') 'DESCONSIDERAR CONTA'
 
FROM [SQLMML].[Sapiens_Prod].[dbo].[E640LCT] WITH (NOLOCK)
  
LEFT JOIN [SQLMML].[Sapiens_Prod].[dbo].[E046HPD]  WITH (NOLOCK)
ON E640LCT.CODHPD = E046HPD.CODHPD
 
INNER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E640RAT] WITH (NOLOCK)
ON E640LCT.CODEMP = E640RAT.CODEMP
AND E640LCT.NUMLCT = E640RAT.NUMLCT
 
INNER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E045PLA]  WITH (NOLOCK)
ON E640RAT.CODEMP = E045PLA.CODEMP
AND E640RAT.CTARED = E045PLA.CTARED
 
INNER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E044CCU]  WITH (NOLOCK)
ON E640RAT.CODEMP = E044CCU.CODEMP
AND E640RAT.CODCCU = E044CCU.CODCCU


LEFT JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP]  WITH (NOLOCK)
ON E640LCT.CODEMP = E070EMP.CODEMP

LEFT JOIN VW_PLANO_DE_CONTAS  WITH (NOLOCK)
ON E640LCT.CODEMP = VW_PLANO_DE_CONTAS.[COD EMPRESA]
AND E640RAT.CTARED = VW_PLANO_DE_CONTAS.[COD REDUZIDA]
AND 'MML' = VW_PLANO_DE_CONTAS.[SERVIDOR]

LEFT JOIN CONTAS_DESCONSIDERADAS WITH (NOLOCK)
ON E640LCT.CODEMP = CONTAS_DESCONSIDERADAS.[COD EMPRESA]
AND E640LCT.NUMLCT = CONTAS_DESCONSIDERADAS.[COD CONTA CONTÁBIL]
AND 'MML' = CONTAS_DESCONSIDERADAS.[SERVIDOR]

WHERE E070EMP.CODEMP = 1
AND LEFT(CLACCU, 2) IN( 24, 26)
AND YEAR(E640LCT.DATLCT) >= 2023
) _MML


UNION ALL

SELECT 
'MIB' AS 'SERVIDOR',

*,
IIF([DESCONSIDERAR CONTA] ='SIM', NULL, 
CASE 
        WHEN [CONTA CONTÁBIL] = 'ENERGIA ELÉTRICA' AND CHARINDEX('REQUISIÇÕES DE MATERIAIS PARA PRODUÇÃO', [HISTÓRICO]) > 0 THEN NULL
        WHEN [CONTA CONTÁBIL] = 'ENERGIA ELÉTRICA' AND CHARINDEX('VLR REF ESTORNO DE REQUISIÇÕES', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('ESTORNO DESCONTO SOBRE', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('BAIXA DE REQUISIÇÕES NA PRODUÇÃO DA OP  DO PRODUTO  EM', [HISTÓRICO]) > 0 AND [CONTA CONTÁBIL] = 'ENERGIA ELÉTRICA' THEN NULL
        WHEN CHARINDEX('VLR REF CUSTO DE PRODUÇÃO', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('ZERAMENTO DE CUSTO', [HISTÓRICO]) > 0 THEN NULL
        WHEN CHARINDEX('VLR. REF. BAIXA DE REQUISIÇÕES NA PRODUÇÃO DA OP   DO PRODUTO', [HISTÓRICO]) > 0 THEN NULL
        WHEN [HISTÓRICO] IN (
            'QUE SE TRANSFERE ENCERRAMENTO DO EXERCICIO.',
            'TRANSFERENCIA DE ATIVO EM ANDAMENTO P/ ATIVO FIXO',
            'SALDO TRANSFERE IMOBILIZADO EM ANDAMENTO PARA ATIVO FIXO',
            'TRANSFERENCIA CONSTRUÇÃO EM ANDAMENTO PARA ATIVO FIXO.',
            'TRANSFERENCIA DE IMOBILIZADO EM ANDAMENTO PARA ATIVO FIXO.',
            'CUSTO PRODUTO PRODUZIDO NESTE MÊS.',
            'ENERGIA CONSUMIDA NO MÊS'
        ) THEN 0
        ELSE [#MOVIMENTO]
    END) '#MOVIMENTO AJUSTADO'

FROM (

SELECT 

CONCAT_WS('-','MIB',E640LCT.CODEMP,E640RAT.CODCCU)  'KEY CR SENIOR',
CONCAT_WS('-','MIB',E640LCT.CODEMP)'COD EMPRESA SENIOR',
UPPER(E070EMP.SIGEMP) 'EMPRESA SENIOR',
E640RAT.CODCCU 'COD CR SENIOR',
UPPER(DESCCU) 'CENTRO RESULTADO SENIOR',
E640RAT.CTARED 'COD CONTA CONTÁBIL',
UPPER(DESCTA) 'CONTA CONTÁBIL',
CAST(E640LCT.DATLCT  AS DATE) 'DATA LANCAMENTO',
IIF( DEBCRE = 'D', 'DÉBITO', 'CRÉDITO') 'TIPO CD',
IIF( DEBCRE = 'D',-1,1)* VLRRAT '#MOVIMENTO',
E640LCT.SITLCT 'COD SITUAÇÃO',
E640LCT.NUMLCT 'SEQUÊNCIA LANÇAMENTO',
CASE LEFT(CLACCU, 2)
WHEN 11 THEN 'ADM'
WHEN 12 THEN 'PRODUÇÃO'
WHEN 13 THEN 'TERMOELÉTRICA'
WHEN 14 THEN 'PELOTIZAÇÃO'
WHEN 15 THEN 'OXIGENIO'
WHEN 16 THEN 'TRASNPORTE INTERNO' ELSE 'OUTROS'
END 'CLASSIFICAÇÃO'

,E640LCT.SITLCT 'SITUAÇÃO',

TRIM(UPPER(CONCAT(E046HPD.DESHPD,' ',E640LCT.CPLLCT))) 'HISTÓRICO' ,
VW_PLANO_DE_CONTAS.[GRUPO 1],
VW_PLANO_DE_CONTAS.[GRUPO 2],
VW_PLANO_DE_CONTAS.[GRUPO 3],
VW_PLANO_DE_CONTAS.[GRUPO 4],

IIF(CONTAS_DESCONSIDERADAS.[COD CONTA CONTÁBIL] IS NOT NULL, 'SIM','NÃO') 'DESCONSIDERAR CONTA'
 
FROM SAPIENS.SAPIENS.E640LCT  WITH (NOLOCK)
  
LEFT JOIN SAPIENS.SAPIENS.E046HPD  WITH (NOLOCK)
ON E640LCT.CODHPD = E046HPD.CODHPD
 
INNER JOIN SAPIENS.SAPIENS.E640RAT  WITH (NOLOCK)
ON E640LCT.CODEMP = E640RAT.CODEMP
AND E640LCT.NUMLCT = E640RAT.NUMLCT
 
INNER JOIN SAPIENS.SAPIENS.E045PLA  WITH (NOLOCK)
ON E640RAT.CODEMP = E045PLA.CODEMP
AND E640RAT.CTARED = E045PLA.CTARED
 
INNER JOIN SAPIENS.SAPIENS.E044CCU  WITH (NOLOCK)
ON E640RAT.CODEMP = E044CCU.CODEMP
AND E640RAT.CODCCU = E044CCU.CODCCU


LEFT JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK)
ON E640LCT.CODEMP = E070EMP.CODEMP

LEFT JOIN VW_PLANO_DE_CONTAS 
ON E640LCT.CODEMP = VW_PLANO_DE_CONTAS.[COD EMPRESA]
AND E640RAT.CTARED = VW_PLANO_DE_CONTAS.[COD REDUZIDA]
AND 'MIB' = VW_PLANO_DE_CONTAS.[SERVIDOR]

LEFT JOIN CONTAS_DESCONSIDERADAS (NOLOCK)
ON E640LCT.CODEMP = CONTAS_DESCONSIDERADAS.[COD EMPRESA]
AND E640LCT.NUMLCT = CONTAS_DESCONSIDERADAS.[COD CONTA CONTÁBIL]
AND 'MIB' = CONTAS_DESCONSIDERADAS.[SERVIDOR]

WHERE E070EMP.CODEMP = 5
AND LEFT(CLACCU, 2) =16
AND YEAR(E640LCT.DATLCT) >= 2023
) _FERGUMINAS
GO