SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_RATEIO_CSC_OCP] AS

SELECT  
    'MIB' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E420OCP.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E420OCP.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATGER), 3)) AS MES, 
    FORMAT(DATGER, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE OCP] 
FROM SAPIENS.SAPIENS.E420OCP WITH (NOLOCK) 

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK) 
ON E420OCP.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK) 
ON E420OCP.CODEMP = E070FIL.CODEMP
AND E420OCP.CODFIL = E070FIL.CODFIL
 
WHERE DATGER >= '01/01/2025'
GROUP BY 
    E420OCP.CODEMP,
    NOMEMP,
    E420OCP.CODFIL,
    NOMFIL,
    DATENAME(month, DATGER),
	  FORMAT(DATGER, 'yyyy-MM'),
    MONTH(DATGER) -- Agrupar pelo número também garante a ordem correta

UNION ALL

SELECT  
    'MML' AS SERVIDOR,
    GETDATE() AS ATUALIZACAO,
    E420OCP.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E420OCP.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATGER), 3)) AS MES, 
    FORMAT(DATGER, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE OCP] 
FROM [SQLMML].[Sapiens_Prod].[dbo].[E420OCP] WITH (NOLOCK) 

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK) 
ON E420OCP.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070FIL] WITH (NOLOCK) 
ON E420OCP.CODEMP = E070FIL.CODEMP
AND E420OCP.CODFIL = E070FIL.CODFIL

WHERE DATGER >= '01/01/2025'
GROUP BY 
    E420OCP.CODEMP,
    NOMEMP,
    E420OCP.CODFIL,
    NOMFIL,
    DATENAME(month, DATGER),
	  FORMAT(DATGER, 'yyyy-MM'),
    MONTH(DATGER) -- Agrupar pelo número também garante a ordem correta

GO