SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_PRODUÇÃO_PARADAS] 
AS -- =============================================
-- TABELAS UTILIZADAS:
--   - PLANTAOCORRENCIA: OCORRÊNCIAS REGISTRADAS NA PLANTA
--   - PLANTA: DADOS DAS PLANTAS/UNIDADES
--   - PLANTAEQUIPAMENTO: EQUIPAMENTOS DA PLANTA
--   - PLANTATURNO: TURNOS DE TRABALHO
--   - PLANTATIPOOCORRENCIA: TIPOS DE OCORRÊNCIA
--   - PLANTACLASSEOCORRENCIA: CLASSES DE OCORRÊNCIA
--   - PLANTAOCORRENCIAXLINHA: RELACIONAMENTO OCORRÊNCIA X LINHA
--   - LINHA: LINHAS DE PRODUÇÃO
-- =============================================

SELECT 
PLANTA.IDEMPRESA 'ID EMPRESA',
    UPPER(EMPRESA.DESCRICAO) 'EMPRESA',
    PLANTA.ID 'ID PLANTA',
    UPPER(PLANTA.DESCRICAO) 'PLANTA',
    PLANTATURNO.ID 'ID TURNO',
    UPPER(PLANTATURNO.DESCRICAO) 'TURNO',
    PLANTAEQUIPAMENTO.ID 'ID EQUIPAMENTO',
        UPPER(PLANTAEQUIPAMENTO.DESCRICAO) 'EQUIPAMENTO',

PLANTAOCORRENCIA.DATAREF 'DATA REFERÊNCIA',
PLANTAOCORRENCIA.DataInicio 'DATA INÍCIO',
PLANTAOCORRENCIA.DataFim 'DATA FIM',
PLANTAOCORRENCIA.DataCadastro 'DATA CADASTRO',
PLANTAOCORRENCIA.DataAlteracao 'DATA ALTERAÇÃO',


    PLANTACLASSEOCORRENCIA.ID 'ID CLASSE OCORRÊNCIA',
    UPPER(PLANTACLASSEOCORRENCIA.DESCRICAO) 'CLASSE OCORRÊNCIA',
    UPPER(PLANTATIPOOCORRENCIA.DESCRICAO) 'TIPO OCORRÊNCIA',

    UPPER(LINHA.DESCRICAO) 'LINHA',
    UPPER(PLANTAOCORRENCIA.OBSERVACAO) 'OBSERVAÇÃO',
    CAST(PLANTAOCORRENCIA.SEGUNDOSOCORRENCIASINDICE/60.0*(LINHA.PERCENTUAL/100.0) AS FLOAT) '#MINUTOS IMPACTO',
    PLANTAOCORRENCIA.SEGUNDOS/60.0 '#MINUTOS'
   

FROM RajaMine.dbo.PLANTAOCORRENCIA WITH (NOLOCK)

INNER JOIN RajaMine.dbo.PLANTA WITH (NOLOCK)
    ON PLANTA.ID = PLANTAOCORRENCIA.IDPLANTA

LEFT JOIN RajaMine.dbo.EMPRESA WITH (NOLOCK)
ON PLANTA.IDEMPRESA = EMPRESA.ID 

INNER JOIN RajaMine.dbo.PLANTATIPOOCORRENCIA WITH (NOLOCK)
    ON PLANTATIPOOCORRENCIA.ID = PLANTAOCORRENCIA.IDPLANTATIPOOCORRENCIA

LEFT OUTER JOIN RajaMine.dbo.PLANTACLASSEOCORRENCIA WITH (NOLOCK)
    ON PLANTACLASSEOCORRENCIA.ID = PLANTATIPOOCORRENCIA.IDPLANTACLASSEOCORRENCIA

INNER JOIN RajaMine.dbo.PLANTAEQUIPAMENTO WITH (NOLOCK)
    ON PLANTAEQUIPAMENTO.ID = PLANTAOCORRENCIA.IDPLANTAEQUIPAMENTO

INNER JOIN RajaMine.dbo.PLANTATURNO WITH (NOLOCK)
    ON PLANTATURNO.ID = PLANTAOCORRENCIA.IDPLANTATURNO

INNER JOIN RajaMine.dbo.PLANTAOCORRENCIAXLINHA WITH (NOLOCK)
    ON PLANTAOCORRENCIA.ID = PLANTAOCORRENCIAXLINHA.IDPLANTAOCORRENCIA 

INNER JOIN RajaMine.dbo.LINHA WITH (NOLOCK)
    ON LINHA.ID = PLANTAOCORRENCIAXLINHA.IDLINHA

WHERE PLANTAOCORRENCIA.DATAREF >= '01/01/2021' 
   
GO