SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_PLANO_DE_CONTAS] 
AS SELECT DISTINCT 
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',E045PLA.codemp ) 'KEY EMPRESA',
CONCAT_WS('-','MIB',E045PLA.codemp, E045PLA.clacta ) 'KEY CONTA CONTÁBIL',
E045PLA.codemp 'COD EMPRESA',
E045PLA.ctared 'COD REDUZIDA',
E045PLA.NATCTA 'NATUREZA CONTA',
E045PLA.clacta 'COD CONTA CONTÁBIL',
MAX(UPPER(descta)) 'CONTA CONTÁBIL',
_GRUPO_1.[COD GRUPO 1] 'COD GRUPO 1',
_GRUPO_1.[GRUPO 1],
_GRUPO_2.[COD GRUPO 2] 'COD GRUPO 2',
_GRUPO_2.[GRUPO 2],
_GRUPO_3.[COD GRUPO 3] 'COD GRUPO 3',
_GRUPO_3.[GRUPO 3],
_GRUPO_4.[COD GRUPO 4] 'COD GRUPO 4',
_GRUPO_4.[GRUPO 4],
_GRUPO_5.[COD GRUPO 5] 'COD GRUPO 5',
_GRUPO_5.[GRUPO 5]
FROM SAPIENS.SAPIENS.E045PLA  WITH (NOLOCK)
--111102001

LEFT JOIN (SELECT DISTINCT codemp, clacta 'COD GRUPO 1', MAX(UPPER(descta)) 'GRUPO 1' FROM SAPIENS.SAPIENS.E045PLA  GROUP BY clacta,codemp) _GRUPO_1
ON LEFT(e045pla.clacta,6) = _GRUPO_1.[COD GRUPO 1]
AND e045pla.codemp = _GRUPO_1.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 2',MAX(UPPER(descta)) 'GRUPO 2' FROM SAPIENS.SAPIENS.E045PLA GROUP BY clacta,codemp) _GRUPO_2
ON LEFT(e045pla.clacta,4) = _GRUPO_2.[COD GRUPO 2]
AND e045pla.codemp = _GRUPO_2.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 3',MAX(UPPER(descta)) 'GRUPO 3' FROM SAPIENS.SAPIENS.E045PLA GROUP BY clacta,codemp) _GRUPO_3
ON LEFT(e045pla.clacta,3) = _GRUPO_3.[COD GRUPO 3]
AND e045pla.codemp = _GRUPO_3.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 4',MAX(UPPER(descta)) 'GRUPO 4' FROM SAPIENS.SAPIENS.E045PLA GROUP BY clacta,codemp) _GRUPO_4
ON LEFT(e045pla.clacta,2) = _GRUPO_4.[COD GRUPO 4]
AND e045pla.codemp = _GRUPO_4.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 5',MAX(UPPER(descta)) 'GRUPO 5' FROM SAPIENS.SAPIENS.E045PLA GROUP BY clacta,codemp) _GRUPO_5
ON LEFT(e045pla.clacta,1) = _GRUPO_5.[COD GRUPO 5]
AND e045pla.codemp = _GRUPO_5.codemp


WHERE anasin = 'A'


GROUP BY 
E045PLA.NATCTA,
e045pla.codemp,
E045PLA.ctared,
E045PLA.clacta, 
	[COD GRUPO 1], 
	[GRUPO 1], 
	[COD GRUPO 2], 
	[GRUPO 2],
	[COD GRUPO 3], 
	[GRUPO 3], 
	[COD GRUPO 4], 
	[GRUPO 4],
  [COD GRUPO 5], 
	[GRUPO 5]



UNION ALL

SELECT DISTINCT 
'MML' AS 'SERVIDOR',
CONCAT_WS('-','MML',E045PLA.codemp ) 'KEY EMPRESA',
CONCAT_WS('-','MML',E045PLA.codemp, E045PLA.clacta ) 'KEY CONTA CONTÁBIL',
E045PLA.codemp 'COD EMPRESA',
E045PLA.ctared 'COD REDUZIDA',
E045PLA.NATCTA 'NATUREZA CONTA',
E045PLA.clacta 'COD CONTA CONTÁBIL',
MAX(UPPER(descta)) 'CONTA CONTÁBIL',
_GRUPO_1.[COD GRUPO 1] 'COD GRUPO 1',
_GRUPO_1.[GRUPO 1],
_GRUPO_2.[COD GRUPO 2] 'COD GRUPO 2',
_GRUPO_2.[GRUPO 2],
_GRUPO_3.[COD GRUPO 3] 'COD GRUPO 3',
_GRUPO_3.[GRUPO 3],
_GRUPO_4.[COD GRUPO 4] 'COD GRUPO 4',
_GRUPO_4.[GRUPO 4],
_GRUPO_5.[COD GRUPO 5] 'COD GRUPO 5',
_GRUPO_5.[GRUPO 5]
FROM [SQLMML].[Sapiens_Prod].[dbo].[E045PLA]  WITH (NOLOCK)
--111102001

LEFT JOIN (SELECT DISTINCT codemp, clacta 'COD GRUPO 1', MAX(UPPER(descta)) 'GRUPO 1' FROM [SQLMML].[Sapiens_Prod].[dbo].[E045PLA]  GROUP BY clacta,codemp) _GRUPO_1
ON LEFT(e045pla.clacta,6) = _GRUPO_1.[COD GRUPO 1]
AND e045pla.codemp = _GRUPO_1.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 2',MAX(UPPER(descta)) 'GRUPO 2' FROM [SQLMML].[Sapiens_Prod].[dbo].[E045PLA] GROUP BY clacta,codemp) _GRUPO_2
ON LEFT(e045pla.clacta,4) = _GRUPO_2.[COD GRUPO 2]
AND e045pla.codemp = _GRUPO_2.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 3',MAX(UPPER(descta)) 'GRUPO 3' FROM [SQLMML].[Sapiens_Prod].[dbo].[E045PLA] GROUP BY clacta,codemp) _GRUPO_3
ON LEFT(e045pla.clacta,3) = _GRUPO_3.[COD GRUPO 3]
AND e045pla.codemp = _GRUPO_3.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 4',MAX(UPPER(descta)) 'GRUPO 4' FROM [SQLMML].[Sapiens_Prod].[dbo].[E045PLA] GROUP BY clacta,codemp) _GRUPO_4
ON LEFT(e045pla.clacta,2) = _GRUPO_4.[COD GRUPO 4]
AND e045pla.codemp = _GRUPO_4.codemp

LEFT JOIN (SELECT DISTINCT codemp,clacta 'COD GRUPO 5',MAX(UPPER(descta)) 'GRUPO 5' FROM [SQLMML].[Sapiens_Prod].[dbo].[E045PLA] GROUP BY clacta,codemp) _GRUPO_5
ON LEFT(e045pla.clacta,1) = _GRUPO_5.[COD GRUPO 5]
AND e045pla.codemp = _GRUPO_5.codemp


WHERE anasin = 'A'


GROUP BY 
E045PLA.NATCTA,
e045pla.codemp,
E045PLA.ctared,
E045PLA.clacta, 
	[COD GRUPO 1], 
	[GRUPO 1], 
	[COD GRUPO 2], 
	[GRUPO 2],
	[COD GRUPO 3], 
	[GRUPO 3], 
	[COD GRUPO 4], 
	[GRUPO 4],
  [COD GRUPO 5], 
	[GRUPO 5]
GO

EXEC sys.sp_addextendedproperty N'MS_Description', N'Documentação Movimento Contábil', 'SCHEMA', N'dbo', 'VIEW', N'VW_PLANO_DE_CONTAS'
GO