SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_RATEIO_CSC_TES] AS

SELECT  
    'MIB' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E600MCC.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E600MCC.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATMOV), 3)) AS MES, 
    FORMAT(DATMOV, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE TES] 
FROM SAPIENS.SAPIENS.E600MCC WITH (NOLOCK) 

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK) 
ON E600MCC.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK) 
ON E600MCC.CODEMP = E070FIL.CODEMP
AND E600MCC.CODFIL = E070FIL.CODFIL
 
WHERE DATMOV >= '01/01/2025'
  AND SITMCC = 'A'
  AND CODTNS IN ('90661','90617','90619','90649','90658','90659','90699')
GROUP BY 
    E600MCC.CODEMP,
    NOMEMP,
    E600MCC.CODFIL,
    NOMFIL,
    DATENAME(month, DATMOV),
	  FORMAT(DATMOV, 'yyyy-MM'),
    MONTH(DATMOV) -- Agrupar pelo número também garante a ordem correta

UNION ALL

SELECT  
    'MML' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E600MCC.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E600MCC.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATMOV), 3)) AS MES, 
    FORMAT(DATMOV, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE TES] 
FROM [SQLMML].[Sapiens_Prod].[dbo].[E600MCC] WITH (NOLOCK)

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK) 
ON E600MCC.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070FIL] WITH (NOLOCK) 
ON E600MCC.CODEMP = E070FIL.CODEMP
AND E600MCC.CODFIL = E070FIL.CODFIL
  
WHERE DATMOV >= '01/01/2025'
  AND SITMCC = 'A'
  AND CODTNS IN ('90661','90617','90619','90649','90658','90659','90699')
GROUP BY 
    E600MCC.CODEMP,
    NOMEMP,
    E600MCC.CODFIL,
    NOMFIL,
    DATENAME(month, DATMOV),
	  FORMAT(DATMOV, 'yyyy-MM'),
    MONTH(DATMOV) -- Agrupar pelo número também garante a ordem correta

GO