SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_REGISTROS_SERVIÇOS] AS

SELECT 
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',ORDSERV.CODORD) 'COD OS'
,ORDXFUN.CODEMP 'COD EMPRESA'
,CONCAT_WS('-','MML',ORDXFUN.CODREGFUN) 'ID REGISTRO FUNCIONÁRIO'
,ORDXFUN.CODFUN 'COD FUNCIONÁRIO SERVIÇO'
,UPPER(FUNC.NOME) 'FUNCIONÁRIO SERVIÇO'
,ORDXFUN.DATHORINI 'DATA INÍCIO'
,ORDXFUN.DATHORFIM 'DATA FIM'
,ISNULL(CAST(ORDXFUN.DATHORFIM  - ORDXFUN.DATHORINI AS FLOAT) * 24, 0) '#HORAS SERVIÇO'
,ISNULL(
    RIGHT('00' + CAST(DATEDIFF(MINUTE, ORDXFUN.DATHORINI, ORDXFUN.DATHORFIM) / 60 AS VARCHAR), 2)
    + ':' +
    RIGHT('00' + CAST(DATEDIFF(MINUTE, ORDXFUN.DATHORINI, ORDXFUN.DATHORFIM) % 60 AS VARCHAR), 2)
, '00:00') AS '#TEMPO SERVIÇO'
,ORDXFUN.HEXTRA '#HORA EXTRA'
,ORDXFUN.VENDA_HORA '#VENDA HORA'
,ISNULL(CAST(ORDXFUN.DATHORFIM  - ORDXFUN.DATHORINI AS FLOAT) * 24, 0)* ORDXFUN.VENDA_HORA '#VENDA HORAS SERVIÇO'



FROM Engeman.Engeman.ORDXFUN  WITH (NOLOCK)

LEFT JOIN Engeman.Engeman.FUNC WITH (NOLOCK)
ON  ORDXFUN.CODFUN = FUNC.CODFUN

LEFT JOIN  Engeman.Engeman.ORDSERV WITH (NOLOCK)

ON  ORDXFUN.CODORD = ORDSERV.CODORD 
AND ORDXFUN.CODEMP = ORDSERV.CODEMP 

--WHERE ORDXFUN.CODREGFUN = '87034'

UNION ALL


SELECT 
'MML' AS 'SERVIDOR',
CONCAT_WS('-','MML',ORDSERV.CODORD) 'COD OS'
,ORDXFUN.CODEMP 'COD EMPRESA'
,CONCAT_WS('-','MML',ORDXFUN.CODREGFUN) 'ID REGISTRO FUNCIONÁRIO'
,ORDXFUN.CODFUN 'COD FUNCIONÁRIO SERVIÇO'
,UPPER(FUNC.NOME) 'FUNCIONÁRIO SERVIÇO'
,ORDXFUN.DATHORINI 'DATA INÍCIO'
,ORDXFUN.DATHORFIM 'DATA FIM'
,ISNULL(CAST(ORDXFUN.DATHORFIM  - ORDXFUN.DATHORINI AS FLOAT) * 24, 0) '#HORAS SERVIÇO'
,ISNULL(
    RIGHT('00' + CAST(DATEDIFF(MINUTE, ORDXFUN.DATHORINI, ORDXFUN.DATHORFIM) / 60 AS VARCHAR), 2)
    + ':' +
    RIGHT('00' + CAST(DATEDIFF(MINUTE, ORDXFUN.DATHORINI, ORDXFUN.DATHORFIM) % 60 AS VARCHAR), 2)
, '00:00') AS '#TEMPO SERVIÇO'
,ORDXFUN.HEXTRA '#HORA EXTRA'
,ORDXFUN.VENDA_HORA '#VENDA HORA'
,ISNULL(CAST(ORDXFUN.DATHORFIM  - ORDXFUN.DATHORINI AS FLOAT) * 24, 0)* ORDXFUN.VENDA_HORA '#VENDA HORAS SERVIÇO'



FROM [SQLMML].[ENGEMAN].[engeman].[ORDXFUN]  WITH (NOLOCK)

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] WITH (NOLOCK)
ON  ORDXFUN.CODFUN = FUNC.CODFUN

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[ORDSERV] WITH (NOLOCK)

ON  ORDXFUN.CODORD = ORDSERV.CODORD 
AND ORDXFUN.CODEMP = ORDSERV.CODEMP 
GO