SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_COLETA_PONTO_APLICAÇÃO] AS 

SELECT
'MIB' AS 'SERVIDOR',
  a.CODEMP 'COD EMPRESA'
 ,f.RAZSOC AS 'FILIAL'
 ,a.TAG AS 'TAG EQUIPAMENTO'
 ,a.DESCRICAO AS 'EQUIPAMENTO'
 ,UPPER(p.DESCRICAO) AS 'PONTO CONTROLE'
 ,CONVERT(NUMERIC(18, 0), p.NUMHIS) AS 'MAX COLETAS'
 ,CONVERT(NUMERIC(18, 0), p.PERHIS) AS 'PER HISTÓRICO'
 ,CONVERT(NUMERIC(18, 2), p.VIRREL) AS 'VIRADA RELÓGIO'
 ,u.TAG AS [Unidade]
 --,CONVERT(NUMERIC(18, 2), p.ACUMULADO) AS '#ACUMULADO'
 ,CAST(c.DATHOR AS DATE) AS 'DATA'
 ,c.DATHOR AS 'DATA HORA'
 ,CONVERT(
  NUMERIC(18, 2),
  (
  CONVERT(
  NUMERIC(18, 2),
  (
  c.VALOR
  - (
  ISNULL((SELECT
      SUM(tm_total.NOVO - tm_total.ANTIGO)
    FROM Engeman.Engeman.TROCAMED tm_total WITH (NOLOCK)
    WHERE tm_total.TIPO = 'T'
    AND tm_total.CODAPL = a.CODAPL
    AND tm_total.CODPONACU = p.CODPONACU)
  ,
  0
  )
  - ISNULL((SELECT
      SUM(tm_antes.NOVO - tm_antes.ANTIGO)
    FROM Engeman.Engeman.TROCAMED tm_antes WITH (NOLOCK)
    WHERE tm_antes.TIPO = 'T'
    AND tm_antes.DATHOR < c.DATHOR
    AND tm_antes.CODAPL = a.CODAPL
    AND tm_antes.CODPONACU = p.CODPONACU)
  ,
  0
  )
  )
  )
  + (p.VIRREL + 1)
  )
  % CONVERT(NUMERIC(18, 2), (p.VIRREL + 1))
  )
  ) AS '#VALOR'
FROM Engeman.Engeman.APLIC a WITH (NOLOCK)
INNER JOIN Engeman.Engeman.FILIAL f WITH (NOLOCK)
  ON f.CODFIL = a.CODFIL
INNER JOIN Engeman.Engeman.PONCONACU p WITH (NOLOCK)
  ON p.CODAPL = a.CODAPL
INNER JOIN Engeman.Engeman.COLACU c WITH (NOLOCK)
  ON c.CODAPL = p.CODAPL
    AND c.CODPONACU = p.CODPONACU
INNER JOIN Engeman.Engeman.UNIDADE u WITH (NOLOCK)
  ON u.CODUNI = p.CODUNI
WHERE CAST(c.DATHOR AS DATE) >= '2025-01-01'


UNION ALL



SELECT
'MML' AS 'SERVIDOR',
  a.CODEMP 'COD EMPRESA'
 ,f.RAZSOC AS 'FILIAL'
 ,a.TAG AS 'TAG EQUIPAMENTO'
 ,a.DESCRICAO AS 'EQUIPAMENTO'
 ,UPPER(p.DESCRICAO) AS 'PONTO CONTROLE'
 ,CONVERT(NUMERIC(18, 0), p.NUMHIS) AS 'MAX COLETAS'
 ,CONVERT(NUMERIC(18, 0), p.PERHIS) AS 'PER HISTÓRICO'
 ,CONVERT(NUMERIC(18, 2), p.VIRREL) AS 'VIRADA RELÓGIO'
 ,u.TAG AS [Unidade]
 --,CONVERT(NUMERIC(18, 2), p.ACUMULADO) AS '#ACUMULADO'
 ,CAST(c.DATHOR AS DATE) AS 'DATA'
 ,c.DATHOR AS 'DATA HORA'
 ,CONVERT(
  NUMERIC(18, 2),
  (
  CONVERT(
  NUMERIC(18, 2),
  (
  c.VALOR
  - (
  ISNULL((SELECT
      SUM(tm_total.NOVO - tm_total.ANTIGO)
    FROM [SQLMML].[ENGEMAN].[engeman].TROCAMED tm_total WITH (NOLOCK)
    WHERE tm_total.TIPO = 'T'
    AND tm_total.CODAPL = a.CODAPL
    AND tm_total.CODPONACU = p.CODPONACU)
  ,
  0
  )
  - ISNULL((SELECT
      SUM(tm_antes.NOVO - tm_antes.ANTIGO)
    FROM [SQLMML].[ENGEMAN].[engeman].TROCAMED tm_antes WITH (NOLOCK)
    WHERE tm_antes.TIPO = 'T'
    AND tm_antes.DATHOR < c.DATHOR
    AND tm_antes.CODAPL = a.CODAPL
    AND tm_antes.CODPONACU = p.CODPONACU)
  ,
  0
  )
  )
  )
  + (p.VIRREL + 1)
  )
  % CONVERT(NUMERIC(18, 2), (p.VIRREL + 1))
  )
  ) AS '#VALOR'
FROM [SQLMML].[ENGEMAN].[engeman].APLIC a WITH (NOLOCK)
INNER JOIN [SQLMML].[ENGEMAN].[engeman].FILIAL f WITH (NOLOCK)
  ON f.CODFIL = a.CODFIL
INNER JOIN [SQLMML].[ENGEMAN].[engeman].PONCONACU p WITH (NOLOCK)
  ON p.CODAPL = a.CODAPL
INNER JOIN [SQLMML].[ENGEMAN].[engeman].COLACU c WITH (NOLOCK)
  ON c.CODAPL = p.CODAPL
    AND c.CODPONACU = p.CODPONACU
INNER JOIN [SQLMML].[ENGEMAN].[engeman].UNIDADE u WITH (NOLOCK)
  ON u.CODUNI = p.CODUNI
WHERE CAST(c.DATHOR AS DATE) >= '2025-01-01'


GO