SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_RATEIO_CSC_NFE] AS

SELECT 
    'MIB' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E440NFC.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E440NFC.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATENT), 3)) AS MES, 
    FORMAT(DATENT, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE NFE] 
FROM SAPIENS.SAPIENS.E440NFC WITH (NOLOCK) 

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK) 
ON E440NFC.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK) 
ON E440NFC.CODEMP = E070FIL.CODEMP
AND E440NFC.CODFIL = E070FIL.CODFIL
 
WHERE DATENT >= '01/01/2025'
GROUP BY 
    E440NFC.CODEMP,
    NOMEMP,
    E440NFC.CODFIL,
    NOMFIL,
    DATENAME(month, DATENT),
	  FORMAT(DATENT, 'yyyy-MM'),
    MONTH(DATENT) -- Agrupar pelo número também garante a ordem correta

UNION ALL

SELECT 
    'MML' AS SERVIDOR,
    GETDATE() AS ATUALIZACAO,
    E440NFC.CODEMP AS [COD. EMPRESA], 
    NOMEMP AS [NOME EMPRESA],
    E440NFC.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL],
    UPPER(LEFT(DATENAME(month, DATENT), 3)) AS MES, 
    FORMAT(DATENT, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE NFE] 
FROM [SQLMML].[Sapiens_Prod].[dbo].[E440NFC] WITH (NOLOCK)

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK) 
ON E440NFC.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070FIL] WITH (NOLOCK) 
ON E440NFC.CODEMP = E070FIL.CODEMP
AND E440NFC.CODFIL = E070FIL.CODFIL
  
WHERE DATENT >= '01/01/2025'
GROUP BY 
    E440NFC.CODEMP,
    NOMEMP,
    E440NFC.CODFIL,
    NOMFIL,
    DATENAME(month, DATENT),
	  FORMAT(DATENT, 'yyyy-MM'),
    MONTH(DATENT) -- Agrupar pelo número também garante a ordem correta

GO