SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_ORDENS_SERVIÇO] 
AS SELECT 


'MIB' AS 'SERVIDOR',
CASE CONCAT_WS('-',ORDSERV.CODEMP,ORDSERV.CODFIL)
WHEN '1-1'THEN 'PLANTA' 
WHEN '1-2'THEN 'LAVRA'
WHEN '2-4'THEN 'PLANTA'
WHEN '2-7'THEN 'TRANSPORTE INTERNO'
WHEN '3-5'THEN 'PLANTA' 
WHEN '3-6'THEN 'PLANTA' 

ELSE 'VERIFICAR' END 'OPERAÇÃO',
CONCAT_WS('-',Equipamento.Id,UPPER(Equipamento.Descricao)) 'KEY EQUIPAMENTO',
Equipamento.Id AS 'ID EQUIPAMENTO RJM',
UPPER(Equipamento.Descricao) AS 'EQUIPAMENTO',
CONCAT_WS('-','MIB',ORDSERV.CODEMP,ORDSERV.CODFIL,ORDSERV.CODORD ) 'KEY OS',
CONCAT_WS('-','MIB',ORDSERV.CODORD) 'COD OS',
CONCAT_WS('-','MIB',ORDSERV.CODEMP) 'COD EMPRESA',
EMPRESA.NOMFAN 'EMPRESA',
CONCAT_WS('-','MIB',ORDSERV.CODFIL) 'COD FILIAL',
CONCAT_WS('-','MIB',FILIAL.CODFIL)  'TAG FILIAL', /*##Cód. Filial,Branch Code,Cód. Sucursal##*/
CONCAT_WS('-','MIB',SOLICITACAO.CODSOL) 'COD SOLICITAÇÃO',
SOLICITACAO.IdentificadorUnicoRaja 'ID SOLICITAÇÃO RAJAMINE', 
IIF(SOLICITACAO.IdentificadorUnicoRaja IS NULL , 'NÃO VINCULADA', 'VINCULADA') 'OS VINCULADA',
IIF(ORDSERV.STATORD='A' , 'ABERTA',
IIF(ORDSERV.STATORD='C' , 'CANCELADA',
IIF(ORDSERV.STATORD='F' , 'FECHADA','VERIFICAR!'))) AS  'STATUS OS', /*##Status O.S,W.O. Status,Status O.T##*/
ORDSERV.TAG 'TAG OS', /*##Cód O.S,W.O. Code,Cód O.T##*/
CONCAT_WS('-','MIB',APLIC.TAG) 'TAG APLICAÇÃO', /*##Cód. Aplicação,Asset Code,Cód. Aplicación##*/
CONCAT_WS('-','MIB',APLIC.CODAPL) 'COD APLICAÇÃO',
UPPER(APLIC.DESCRICAO) 'APLICAÇÃO', /*##Aplicação,Asset,Aplicación##*/
CONCAT_WS('-','MIB',CLIENTE.CODCLI)	'COD CLIENTE', /*##Cód. Cliente,Customer Code,Cód. Cliente##*/
UPPER(CLIENTE.RAZSOC) 'CLIENTE', /*##Cliente,Customer,Cliente##*/
CONCAT_WS('-','MIB',CENCUS.CODCEN) 'COD CR',
CENCUS.TAG 'TAG CR', /*##Cód. Centro de Custos,Cost Center Code,Cód. Centro de Costos##*/
UPPER(CENCUS.DESCRICAO) 'CENTRO DE RESULTADO', /*##Centro de Custos,Cost Center,Centro de Costos##*/
CONCAT_WS('-','MIB',SETEXE.CODSET) 'COD SETOR',
SETEXE.TAG 'TAG SETOR', /*##Cód. Setor Executante,Performing Department Code,Cód. Sector Ejecutante##*/
UPPER(SETEXE.DESCRICAO) 'SETOR', /*##Setor Executante,Performing Department,Sector Ejecutante##*/
CONCAT_WS('-','MIB',TIPMANUT.CODTIPMAN) 'COD TIPO MANUTENÇÃO',
TIPMANUT.TAG 'TAG TIPO MANUTENÇÃO', /*##Cód. Tipo Manutenção,Maintenance Type Code,Cód. Tipo Mantenimiento##*/
UPPER(TIPMANUT.DESCRICAO) 'TIPO MANUTENÇÃO', /*##Tipo Manutenção,Maintenance Type,Tipo Mantenimiento##*/
CONCAT_WS('-','MIB',ORDSERV.CODCON) 'COD CONTA CONTÁBIL',
CONTABIL.DESCRICAO 'CONTA CONTÁBIL',
CONCAT_WS('-','MIB',SOLICITANTE.CODFUN) 'COD SOLICITANTE',
CASE WHEN SOLICITANTE.TAG IS NULL THEN CONTATOS.NOME ELSE SOLICITANTE.NOME END 'SOLICITANTE',
CONCAT_WS('-','MIB',RESPONSAVEL.CODFUN) 'COD RESPONSÁVAL',
COALESCE(RESPONSAVEL.NOME,'NÃO INDICADO') 'RESPONSÁVEL',
MOTATRA.DESCRICAO 'MOTIVO ATRASO',
--DATAS 
ORDSERV.MAQPAR 'HORA MÁQUINA PARADA',
ORDSERV.MAQFUN 'HORA MÁQUINA FUNCIONANDO',
ISNULL(CAST(ORDSERV.MAQFUN - ORDSERV.MAQPAR AS FLOAT) * 24, 0) '#TEMPO PARADA FÍSICA',
ORDSERV.DATALT  'DATA ALTERAÇÃO',             --Data de Alteração
ORDSERV.DATCAN  'DATA CANCELAMENTO',             --Data cancelamento
ORDSERV.DATENT 'DATA ENTREGA PREVISTA',             --Data da entrega prevista
ORDSERV.DATENT_ORIGINAL 'DATA ENTREGA ORIGINAL',             --Data da entrega Original
ORDSERV.DATFEC  'DATA FECHAMENTO',             --Data de fechamento
ORDSERV.DATGER  'DATA GERAÇÃO',             --Data da geração
ORDSERV.DATPRO  'DATA PROGRAMADA',             --Data Programada
ORDSERV.DATPRO_ORIGINAL  'DATA PROGRAMADA ORIGINAL',             --Data programada original
ORDSERV.DATREC  'DATA RECEBIMENTO',             --Data de recebimento
VW_EQUIPAMENTOS_ENGEMAN.PRINCIPAIS


--,CASE 
--WHEN CHARINDEX('CAMINHÃO', APLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('PIPA', APLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('ESCAVADEIRA', APLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('CARREGADEIRA', APLIC.DESCRICAO) > 0 THEN 'SIM'
--ELSE 'NÃO' END AS 'CONTROLA'


FROM  Engeman.Engeman.ORDSERV WITH (NOLOCK)

LEFT JOIN  Engeman.Engeman.RES_GERENCIAL_CUSTO  WITH (NOLOCK) 
ON ORDSERV.CODORD = RES_GERENCIAL_CUSTO.CODORD

LEFT JOIN  Engeman.Engeman.FILIAL  WITH (NOLOCK) 
ON ORDSERV.CODFIL=FILIAL.CODFIL

LEFT JOIN  Engeman.Engeman.TIPMANUT  WITH (NOLOCK) 
ON ORDSERV.CODTIPMAN=TIPMANUT.CODTIPMAN

LEFT JOIN  Engeman.Engeman.CENCUS  WITH (NOLOCK) 
ON ORDSERV.CODCEN=CENCUS.CODCEN

LEFT JOIN  Engeman.Engeman.SETEXE  WITH (NOLOCK) 
ON ORDSERV.CODSET=SETEXE.CODSET

LEFT JOIN Engeman.Engeman.APLIC  WITH (NOLOCK) 
ON ORDSERV.CODAPL=APLIC.CODAPL

LEFT JOIN  Engeman.Engeman.TIPAPLIC  WITH (NOLOCK) 
ON TIPAPLIC.CODTIPAPL=APLIC.CODTIPAPL

LEFT JOIN  Engeman.Engeman.CLIENTE  WITH (NOLOCK) 
ON ORDSERV.CODCLI=CLIENTE.CODCLI

LEFT JOIN Engeman.Engeman.CONTABIL   WITH (NOLOCK) 
ON ORDSERV.CODCON=CONTABIL.CODCON 

LEFT JOIN Engeman.Engeman.MOTATRA   WITH (NOLOCK) 
ON ORDSERV.CODMOTATR=MOTATRA.CODMOTATR

LEFT JOIN Engeman.Engeman.SOLICITACAO   WITH (NOLOCK)
ON ORDSERV.CODSOL =  SOLICITACAO.CODSOL 

LEFT JOIN Engeman.Engeman.EMPRESA WITH (NOLOCK)
ON ORDSERV.CODEMP = EMPRESA.CODEMP


LEFT JOIN Engeman.Engeman.FUNC SOLICITANTE   WITH (NOLOCK) ON ORDSERV.CODFUN=SOLICITANTE.CODFUN
LEFT JOIN Engeman.Engeman.FUNC RESPONSAVEL   WITH (NOLOCK) ON ORDSERV.CODFUN_RESP=RESPONSAVEL.CODFUN
LEFT JOIN Engeman.Engeman.FUNC B   WITH (NOLOCK) ON ORDSERV.CODFUN_2=B.CODFUN

LEFT JOIN Engeman.Engeman.PLAMANUT   WITH (NOLOCK) ON ORDSERV.CODPLA=PLAMANUT.CODPLA 
LEFT JOIN Engeman.Engeman.LOCAPLIC   WITH (NOLOCK) ON ORDSERV.CODLOCAPL=LOCAPLIC.CODLOCAPL            

LEFT JOIN Engeman.Engeman.PRODUTO   WITH (NOLOCK) ON ORDSERV.CODPRO=PRODUTO.CODPRO 
LEFT JOIN Engeman.Engeman.CONTATOS   WITH (NOLOCK) ON ORDSERV.CODCONTATO = CONTATOS.CODCON

LEFT JOIN  RajaMine.dbo.Equipamento WITH (NOLOCK)
ON APLIC.TAG =  Equipamento.Codigo COLLATE Latin1_General_CI_AS

LEFT JOIN VW_EQUIPAMENTOS_ENGEMAN
ON CONCAT('MIB-',APLIC.CODAPL)  = VW_EQUIPAMENTOS_ENGEMAN.[COD EQUIPAMENTO]

WHERE YEAR(ORDSERV.DATGER) >=2024



UNION ALL


SELECT 


'MML' AS 'SERVIDOR',
CASE CONCAT_WS('-',ORDSERV.CODEMP,ORDSERV.CODFIL)
WHEN '1-1'THEN 'PLANTA' 
WHEN '1-4'THEN 'LAVRA' ELSE 'VERIFICAR' END 'OPERAÇÃO',
CONCAT_WS('-',Equipamento.Id,UPPER(Equipamento.Descricao)) 'KEY EQUIPAMENTO',
Equipamento.Id AS 'ID EQUIPAMENTO RJM',
UPPER(Equipamento.Descricao) AS 'EQUIPAMENTO',
CONCAT_WS('-','MML',ORDSERV.CODEMP,ORDSERV.CODFIL,ORDSERV.CODORD ) 'KEY OS',
CONCAT_WS('-','MML',ORDSERV.CODORD) 'COD OS',
CONCAT_WS('-','MML',ORDSERV.CODEMP) 'COD EMPRESA',
EMPRESA.NOMFAN 'EMPRESA',
CONCAT_WS('-','MML',ORDSERV.CODFIL) 'COD FILIAL',
CONCAT_WS('-','MML',FILIAL.CODFIL)  'TAG FILIAL', /*##Cód. Filial,Branch Code,Cód. Sucursal##*/
CONCAT_WS('-','MIB',SOLICITACAO.CODSOL) 'COD SOLICITAÇÃO',
--NULL AS 'ID SOLICITAÇÃO RAJAMINE', 
SOLICITACAO.IdentificadorUnicoRaja 'ID SOLICITAÇÃO RAJAMINE', 
IIF(SOLICITACAO.IdentificadorUnicoRaja IS NULL , 'NÃO VINCULADA', 'VINCULADA') 'OS VINCULADA',
IIF(ORDSERV.STATORD='A' , 'ABERTA',
IIF(ORDSERV.STATORD='C' , 'CANCELADA',
IIF(ORDSERV.STATORD='F' , 'FECHADA','VERIFICAR!'))) AS  'STATUS OS', /*##Status O.S,W.O. Status,Status O.T##*/
ORDSERV.TAG 'TAG OS', /*##Cód O.S,W.O. Code,Cód O.T##*/
CONCAT_WS('-','MML',APLIC.TAG) 'TAG APLICAÇÃO', /*##Cód. Aplicação,Asset Code,Cód. Aplicación##*/
CONCAT_WS('-','MML',APLIC.CODAPL) 'COD APLICAÇÃO',
UPPER(APLIC.DESCRICAO) 'APLICAÇÃO', /*##Aplicação,Asset,Aplicación##*/
CONCAT_WS('-','MML',CLIENTE.CODCLI)	'COD CLIENTE', /*##Cód. Cliente,Customer Code,Cód. Cliente##*/
UPPER(CLIENTE.RAZSOC) 'CLIENTE', /*##Cliente,Customer,Cliente##*/
CONCAT_WS('-','MML',CENCUS.CODCEN) 'COD CR',
CENCUS.TAG 'TAG CR', /*##Cód. Centro de Custos,Cost Center Code,Cód. Centro de Costos##*/
UPPER(CENCUS.DESCRICAO) 'CENTRO DE RESULTADO', /*##Centro de Custos,Cost Center,Centro de Costos##*/
CONCAT_WS('-','MML',SETEXE.CODSET) 'COD SETOR',
SETEXE.TAG 'TAG SETOR', /*##Cód. Setor Executante,Performing Department Code,Cód. Sector Ejecutante##*/
UPPER(SETEXE.DESCRICAO) 'SETOR', /*##Setor Executante,Performing Department,Sector Ejecutante##*/
CONCAT_WS('-','MML',TIPMANUT.CODTIPMAN) 'COD TIPO MANUTENÇÃO',
TIPMANUT.TAG 'TAG TIPO MANUTENÇÃO', /*##Cód. Tipo Manutenção,Maintenance Type Code,Cód. Tipo Mantenimiento##*/
UPPER(TIPMANUT.DESCRICAO) 'TIPO MANUTENÇÃO', /*##Tipo Manutenção,Maintenance Type,Tipo Mantenimiento##*/
CONCAT_WS('-','MML',ORDSERV.CODCON) 'COD CONTA CONTÁBIL',
CONTABIL.DESCRICAO 'CONTA CONTÁBIL',
CONCAT_WS('-','MML',SOLICITANTE.CODFUN) 'COD SOLICITANTE',
CASE WHEN SOLICITANTE.TAG IS NULL THEN CONTATOS.NOME ELSE SOLICITANTE.NOME END 'SOLICITANTE',
CONCAT_WS('-','MML',RESPONSAVEL.CODFUN) 'COD RESPONSÁVAL',
RESPONSAVEL.NOME 'RESPONSÁVEL',
MOTATRA.DESCRICAO 'MOTIVO ATRASO',



--DATAS 
ORDSERV.MAQPAR 'HORA MÁQUINA PARADA',
ORDSERV.MAQFUN 'HORA MÁQUINA FUNCIONANDO',
ISNULL(CAST(ORDSERV.MAQFUN - ORDSERV.MAQPAR AS FLOAT) * 24, 0) '#TEMPO PARADA FÍSICA',
ORDSERV.DATALT  'DATA ALTERAÇÃO',             --Data de Alteração
ORDSERV.DATCAN  'DATA CANCELAMENTO',             --Data cancelamento
ORDSERV.DATENT 'DATA ENTREGA PREVISTA',             --Data da entrega prevista
ORDSERV.DATENT_ORIGINAL 'DATA ENTREGA ORIGINAL',             --Data da entrega Original
ORDSERV.DATFEC  'DATA FECHAMENTO',             --Data de fechamento
ORDSERV.DATGER  'DATA GERAÇÃO',             --Data da geração
ORDSERV.DATPRO  'DATA PROGRAMADA',             --Data Programada
ORDSERV.DATPRO_ORIGINAL  'DATA PROGRAMADA ORIGINAL',             --Data programada original
ORDSERV.DATREC  'DATA RECEBIMENTO',             --Data de recebimento
VW_EQUIPAMENTOS_ENGEMAN.PRINCIPAIS
--,CASE 
--WHEN CHARINDEX('CAMINHÃO', APLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('PIPA', APLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('ESCAVADEIRA', APLIC.DESCRICAO) > 0 THEN 'SIM'
--WHEN CHARINDEX('CARREGADEIRA', APLIC.DESCRICAO) > 0 THEN 'SIM'
--ELSE 'NÃO' END AS 'CONTROLA'


FROM  [SQLMML].[ENGEMAN].[engeman].[ORDSERV] WITH (NOLOCK)

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[RES_GERENCIAL_CUSTO]  WITH (NOLOCK) 
ON ORDSERV.CODORD = RES_GERENCIAL_CUSTO.CODORD

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[FILIAL]  WITH (NOLOCK) 
ON ORDSERV.CODFIL=FILIAL.CODFIL

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[TIPMANUT]  WITH (NOLOCK) 
ON ORDSERV.CODTIPMAN=TIPMANUT.CODTIPMAN

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[CENCUS]  WITH (NOLOCK) 
ON ORDSERV.CODCEN=CENCUS.CODCEN

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[SETEXE]  WITH (NOLOCK) 
ON ORDSERV.CODSET=SETEXE.CODSET

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[APLIC]  WITH (NOLOCK) 
ON ORDSERV.CODAPL=APLIC.CODAPL

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[TIPAPLIC]  WITH (NOLOCK) 
ON TIPAPLIC.CODTIPAPL=APLIC.CODTIPAPL

LEFT JOIN  [SQLMML].[ENGEMAN].[engeman].[CLIENTE]  WITH (NOLOCK) 
ON ORDSERV.CODCLI=CLIENTE.CODCLI

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CONTABIL]   WITH (NOLOCK) 
ON ORDSERV.CODCON=CONTABIL.CODCON 

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[MOTATRA]   WITH (NOLOCK) 
ON ORDSERV.CODMOTATR=MOTATRA.CODMOTATR


LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[SOLICITACAO]   WITH (NOLOCK)
ON ORDSERV.CODSOL =  SOLICITACAO.CODSOL 

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[EMPRESA] WITH (NOLOCK)
ON ORDSERV.CODEMP = EMPRESA.CODEMP


LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] SOLICITANTE   WITH (NOLOCK) ON ORDSERV.CODFUN=SOLICITANTE.CODFUN
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] RESPONSAVEL   WITH (NOLOCK) ON ORDSERV.CODFUN_RESP=RESPONSAVEL.CODFUN
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] B   WITH (NOLOCK) ON ORDSERV.CODFUN_2=B.CODFUN

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[PLAMANUT]   WITH (NOLOCK) ON ORDSERV.CODPLA=PLAMANUT.CODPLA 
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[LOCAPLIC]   WITH (NOLOCK) ON ORDSERV.CODLOCAPL=LOCAPLIC.CODLOCAPL            

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[PRODUTO]   WITH (NOLOCK) ON ORDSERV.CODPRO=PRODUTO.CODPRO 
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CONTATOS]   WITH (NOLOCK) ON ORDSERV.CODCONTATO = CONTATOS.CODCON


LEFT JOIN  RajaMine.dbo.Equipamento WITH (NOLOCK)
ON APLIC.TAG =  Equipamento.Codigo COLLATE Latin1_General_CI_AS


LEFT JOIN VW_EQUIPAMENTOS_ENGEMAN
ON CONCAT('MML-',APLIC.CODAPL)  = VW_EQUIPAMENTOS_ENGEMAN.[COD EQUIPAMENTO]

WHERE YEAR(ORDSERV.DATGER) >=2024
--AND VW_EQUIPAMENTOS_ENGEMAN.CONTROLA = 'SIM'
GO