SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_ESTOQUE_MOVIMENTAÇÃO] AS
SELECT
    EMPRESA.ID 'ID EMPRESA',
    UPPER(EMPRESA.DESCRICAO) 'EMPRESA',
    MOVIMENTACAO.ID 'ID MOVIMENTAÇÃO',
    MOVIMENTACAO.IDPLANTATURNO 'ID TURNO',
    UPPER(PLANTATURNO.DESCRICAO) 'TURNO',
    MOVIMENTACAO.IDTIQUETE 'ID TIQUET',
    MOVIMENTACAO.IDPILHA 'ID PILHA',
    UPPER(PILHA.DESCRICAO) 'PILHA',
    MOVIMENTACAO.IDMATERIALORIGEM 'ID MATERIAL ORIGEM',
    UPPER(MATERIAL.DESCRICAO) 'MATERIAL ORIGEM',
    MATERIAL.IDGRUPOMATERIAL 'ID GRUPO MATERIAL ORIGEM',
    UPPER(GRUPOMATERIAL.DESCRICAO) 'GRUPO MATERIAL ORIGEM',
    MOVIMENTACAO.IDMATERIALVENDA 'ID MATERIAL VENDA',
    UPPER(_MATERIAL_VENDA.DESCRICAO) 'MATERIAL VENDA',
    _MATERIAL_VENDA.IDGRUPOMATERIAL 'ID GRUPO MATERIAL VENDA',
    UPPER(_GRUPO_MATERIA_VENDA.DESCRICAO) 'GRUPO MATERIAL VENDA',
    MOVIMENTACAO.IDTRANSFERENCIA 'ID TRANSFERÊNCIA',
    MOVIMENTACAO.QUANTIDADE '#QUANTIDADE',
    IIF(MOVIMENTACAO.TIPO='S', MOVIMENTACAO.QUANTIDADE*-1, MOVIMENTACAO.QUANTIDADE) '#SALDO',
    IIF(MOVIMENTACAO.TIPO='S', 'SAÍDA', 'ENTRADA') 'TIPO MOVIMENTAÇÃO',
    MOVIMENTACAO.DATA 'DATA',
    UPPER(MOVIMENTACAO.OBSERVACAO) 'OBSERVAÇÃO',
    MOVIMENTACAO.PESAGEM 'ID PESAGEM',
    MOVIMENTACAO.EL1 '#FERRO',
    MOVIMENTACAO.EL2 '#SIO2',
    MOVIMENTACAO.EL3 '#FÓSFORO',
    MOVIMENTACAO.EL4 '#MANGANÊS'

FROM RAJAMINE.dbo.MOVIMENTACAO WITH (NOLOCK)

LEFT JOIN RAJAMINE.dbo.PLANTATURNO WITH (NOLOCK)
    ON MOVIMENTACAO.IDPLANTATURNO = PLANTATURNO.ID

LEFT JOIN RAJAMINE.dbo.EMPRESA WITH (NOLOCK)
    ON PLANTATURNO.IDEMPRESA = EMPRESA.ID

LEFT JOIN RAJAMINE.dbo.PILHA WITH (NOLOCK)
    ON MOVIMENTACAO.IDPILHA = PILHA.ID

LEFT JOIN RAJAMINE.dbo.MATERIAL WITH (NOLOCK)
    ON MOVIMENTACAO.IDMATERIALORIGEM = MATERIAL.ID

LEFT JOIN RAJAMINE.dbo.GRUPOMATERIAL WITH (NOLOCK)
    ON MATERIAL.IDGRUPOMATERIAL = GRUPOMATERIAL.ID

LEFT JOIN RAJAMINE.dbo.MATERIAL _MATERIAL_VENDA WITH (NOLOCK)
    ON MOVIMENTACAO.IDMATERIALVENDA = _MATERIAL_VENDA.ID

LEFT JOIN RAJAMINE.dbo.GRUPOMATERIAL _GRUPO_MATERIA_VENDA WITH (NOLOCK)
    ON _MATERIAL_VENDA.IDGRUPOMATERIAL = _GRUPO_MATERIA_VENDA.ID;
GO