SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_EQUIPAMENTO_CR] 
AS SELECT DISTINCT
    'MIB' AS 'SERVIDOR',
    IIF(APLIC.CODAPL IS NULL, NULL,CONCAT('MIB-',APLIC.CODEMP)) 'COD EMPRESA ENGEMAN',
    EMPRESA.NOMFAN 'EMPRESA ENGEMAN',
    IIF(APLIC.CODAPL IS NULL, NULL,CONCAT('MIB-', APLIC.CODAPL)) AS 'COD EQUIPAMENTO ENGEMAN',
    UPPER(APLIC.DESCRICAO) AS 'EQUIPAMENTO ENGEMAN',
    IIF(APLIC.CODAPL IS NULL, NULL,CONCAT_WS('-', 'MIB', APLIC.CODEMP, APLIC.CODFIL)) AS 'KEY FILIAL ENGEMAN',
    CONCAT_WS('-', 'MIB',_LINKS_CRS.[COD EMPRESA SENIOR]) 'COD EMPRESA SENIOR',
    _LINKS_CRS.[KEY CR SENIOR],
    _LINKS_CRS.[CENTRO RESULTADO SENIOR],
    IIF(APLIC.CODAPL IS NULL, NULL,COUNT(_LINKS_CRS.[KEY CR SENIOR]) OVER (PARTITION BY CONCAT('MIB-', APLIC.CODAPL))) AS 'CRS POR EQUIPAMENTO'

FROM Engeman.Engeman.APLIC WITH (NOLOCK)

LEFT JOIN Engeman.Engeman.EMPRESA
ON  APLIC.CODEMP = EMPRESA.CODEMP

LEFT JOIN Engeman.Engeman.CENCUS WITH (NOLOCK)
    ON APLIC.CODCEN = CENCUS.CODCEN
      
INNER JOIN (  
   
   SELECT 
        'MIB' AS 'BANCO',
        CODEMP AS 'COD EMPRESA ENGEMAN',
        CODCEN AS 'COD CR ENGEMAN',
        UPPER(CENCUS.DESCRICAO) AS 'CENTRO DE CUSTO ENGEMAN',
        IIF([COD EMPRESA SENIOR] IS NULL, NULL, CONCAT_WS('-', 'MIB', [COD EMPRESA SENIOR], [COD CR SENIOR])) AS 'KEY CR SENIOR',
        _SENIOR.*
    FROM Engeman.Engeman.CENCUS

    INNER JOIN (
        SELECT 
            E044CCU.CODEMP AS 'COD EMPRESA SENIOR',
            E044CCU.CODCCU AS 'COD CR SENIOR',
            UPPER(DESCCU) AS 'CENTRO RESULTADO SENIOR'
        FROM SAPIENS.SAPIENS.E044CCU WITH (NOLOCK)
        WHERE LEFT(e044ccu.CLACCU, 2) IN( 22, 24)
    ) _SENIOR 
    ON DESCRICAO = _SENIOR.[CENTRO RESULTADO SENIOR]
    AND CODEMP = 1
    AND _SENIOR.[COD EMPRESA SENIOR] = 1

) _LINKS_CRS

ON APLIC.CODEMP = _LINKS_CRS.[COD EMPRESA ENGEMAN]
AND APLIC.CODCEN = _LINKS_CRS.[COD CR ENGEMAN]


UNION ALL


   SELECT DISTINCT
    'MML' AS 'SERVIDOR',
    IIF(APLIC.CODAPL IS NULL, NULL,CONCAT('MML-',APLIC.CODEMP)) 'COD EMPRESA ENGEMAN',
    EMPRESA.NOMFAN 'EMPRESA ENGEMAN',
    IIF(APLIC.CODAPL IS NULL, NULL,CONCAT('MML-', APLIC.CODAPL)) AS 'COD EQUIPAMENTO ENGEMAN',
    UPPER(APLIC.DESCRICAO) AS 'EQUIPAMENTO ENGEMAN',
    IIF(APLIC.CODAPL IS NULL, NULL,CONCAT_WS('-', 'MML', APLIC.CODEMP, APLIC.CODFIL)) AS 'KEY FILIAL ENGEMAN',
    CONCAT_WS('-', 'MML',_LINKS_CRS.[COD EMPRESA SENIOR]) 'COD EMPRESA SENIOR',
    _LINKS_CRS.[KEY CR SENIOR],
    _LINKS_CRS.[CENTRO RESULTADO SENIOR],
    IIF(APLIC.CODAPL IS NULL, NULL,COUNT(_LINKS_CRS.[KEY CR SENIOR]) OVER (PARTITION BY CONCAT('MML-', APLIC.CODAPL))) AS 'CRS POR EQUIPAMENTO'

FROM [SQLMML].[ENGEMAN].[engeman].[APLIC] WITH (NOLOCK)

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[EMPRESA]
ON  APLIC.CODEMP = EMPRESA.CODEMP

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CENCUS] WITH (NOLOCK)
    ON APLIC.CODCEN = CENCUS.CODCEN
      
INNER JOIN (  
   
   SELECT 
        'MML' AS 'BANCO',
        CODEMP AS 'COD EMPRESA ENGEMAN',
        CODCEN AS 'COD CR ENGEMAN',
        UPPER(CENCUS.DESCRICAO) AS 'CENTRO DE CUSTO ENGEMAN',
        IIF([COD EMPRESA SENIOR] IS NULL, NULL, CONCAT_WS('-', 'MML', [COD EMPRESA SENIOR], [COD CR SENIOR])) AS 'KEY CR SENIOR',
        _SENIOR.*
    FROM [SQLMML].[ENGEMAN].[engeman].[CENCUS]

    INNER JOIN (
        SELECT 
            E044CCU.CODEMP AS 'COD EMPRESA SENIOR',
            E044CCU.CODCCU AS 'COD CR SENIOR',
            UPPER(DESCCU) AS 'CENTRO RESULTADO SENIOR'
        FROM [SQLMML].[Sapiens_Prod].[dbo].[E044CCU] WITH (NOLOCK)
        WHERE LEFT(e044ccu.CLACCU, 2) IN( 24, 26)
    ) _SENIOR 
    ON DESCRICAO = _SENIOR.[CENTRO RESULTADO SENIOR]
    AND CODEMP = 1
    AND _SENIOR.[COD EMPRESA SENIOR] = 1

) _LINKS_CRS

ON APLIC.CODEMP = _LINKS_CRS.[COD EMPRESA ENGEMAN]
AND APLIC.CODCEN = _LINKS_CRS.[COD CR ENGEMAN]
GO