SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_RATEIO_CSC_CRE] 
AS SELECT 
    'MIB' 'SERVIDOR', 
    GETDATE() AS ATUALIZACAO,
    E301TCR.CODEMP AS [COD. EMPRESA],
    NOMEMP AS [NOME EMPRESA],
    E301TCR.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL], 
    UPPER(LEFT(DATENAME(month, DATEMI), 3)) AS MES, 
    FORMAT(DATEMI, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE CRE] 
FROM SAPIENS.SAPIENS.E301TCR WITH (NOLOCK) 

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK) 
ON E301TCR.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK) 
ON E301TCR.CODEMP = E070FIL.CODEMP
AND E301TCR.CODFIL = E070FIL.CODFIL
 
WHERE DATEMI >= '01/01/2025'
GROUP BY 
    E301TCR.CODEMP,
    NOMEMP,
    E301TCR.CODFIL,
    NOMFIL,
    DATENAME(month, DATEMI),
	  FORMAT(DATEMI, 'yyyy-MM'),
    MONTH(DATEMI) -- Agrupar pelo número também garante a ordem correta

UNION ALL

SELECT  
    'MML' 'SERVIDOR',
    GETDATE() AS ATUALIZACAO,
    E301TCR.CODEMP AS [COD. EMPRESA],
    NOMEMP AS [NOME EMPRESA],
    E301TCR.CODFIL AS [COD. FILIAL],
    NOMFIL AS [NOME FILIAL], 
    UPPER(LEFT(DATENAME(month, DATEMI), 3)) AS MES, 
    FORMAT(DATEMI, 'yyyy-MM') AS [ANO-MES],
    COUNT(*) AS [TOTAL DE CRE] 
FROM [SQLMML].[Sapiens_Prod].[dbo].[E301TCR] WITH (NOLOCK)

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK) 
ON E301TCR.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070FIL] WITH (NOLOCK) 
ON E301TCR.CODEMP = E070FIL.CODEMP
AND E301TCR.CODFIL = E070FIL.CODFIL
  
WHERE DATEMI >= '01/01/2025'
GROUP BY 
    E301TCR.CODEMP,
    NOMEMP,
    E301TCR.CODFIL,
    NOMFIL,
    DATENAME(month, DATEMI),
	  FORMAT(DATEMI, 'yyyy-MM'),
    MONTH(DATEMI) -- Agrupar pelo número também garante a ordem correta

GO