SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_CUSTO_PESSOAL] 
AS SELECT 

_HORAS.*,
_EVENTOS_FOLHA.[#VALOR MÊS],
_EVENTOS_FOLHA.[#VALOR MÊS]/[#HORAS MÊS] '#VALOR HORA'


FROM(
SELECT 
        IIF(R030EMP.numemp = 1, 'MIB',
        IIF(R030EMP.numemp = 2, 'MIB',
        IIF(R030EMP.numemp = 5, 'MIB',
        IIF(R030EMP.numemp = 7, 'MML', 'VERIFICAR')))) 'EMPRESA',

CONCAT_WS('-', 
        IIF(R030EMP.numemp = 1, 'MIB-1',
        IIF(R030EMP.numemp = 2, 'MIB-3',
        IIF(R030EMP.numemp = 5, 'MIB-2',
        IIF(R030EMP.numemp = 7, 'MML-1', 'VERIFICAR')))), 
       CAST( R034FUN.NUMCAD AS INT)
    ) AS 'KEY MATRÍCULA ENGEMAN',


     R030EMP.numemp 'COD EMPRESA SENIOR', 
    R034FUN.NUMCAD  'MATRÍCULA SENIOR',
    CAST(R044CAL.PerRef AS DATE) AS 'PERÍODO BASE',
    MAX(R006ESC.HORMES) / 60 AS '#HORAS MÊS'
FROM 
    VETORH.VETORH.R034FUN (NOLOCK)
    INNER JOIN VETORH.VETORH.R044CAL (NOLOCK) 
        ON R034FUN.NumEmp = R044CAL.NumEmp
    INNER JOIN VETORH.VETORH.R006ESC (NOLOCK) 
        ON R034FUN.CodEsc = R006ESC.CodEsc
    INNER JOIN VETORH.VETORH.R030EMP (NOLOCK)
        ON R034FUN.NumEmp = R030EMP.NumEmp
WHERE   
    R044CAL.TipCal = 11 -- Considera a folha de pagamento mensal
    AND YEAR(R044CAL.PerRef) >= 2024
    AND R030EMP.numemp IN (1, 2, 5, 7)
GROUP BY
    R034FUN.NUMEMP,
    R034FUN.NUMCAD,
    R044CAL.PerRef,
    R030EMP.numemp,
    R034FUN.NUMCAD,
    IIF(R030EMP.numemp = 1, 'MIB',
        IIF(R030EMP.numemp = 2, 'MIB',
        IIF(R030EMP.numemp = 5, 'MIB',
        IIF(R030EMP.numemp = 7, 'MML', 'VERIFICAR')))),
    CONCAT_WS('-', 
        IIF(R030EMP.numemp = 1, 'MIB-1',
        IIF(R030EMP.numemp = 2, 'MIB-3',
        IIF(R030EMP.numemp = 5, 'MIB-2',
        IIF(R030EMP.numemp = 7, 'MML-1', 'VERIFICAR')))), 
        R034FUN.NUMCAD
    )

) _HORAS 

INNER JOIN (
SELECT 

[COD EMPRESA],
MATRÍCULA,
DATA,
SUM(#VALOR) '#VALOR MÊS'

FROM BI.dbo.VW_EVENTOS_FOLHA

GROUP BY
[COD EMPRESA],
MATRÍCULA,
DATA

) _EVENTOS_FOLHA

ON _HORAS.[COD EMPRESA SENIOR] = _EVENTOS_FOLHA.[COD EMPRESA]
AND _HORAS.[MATRÍCULA SENIOR] = _EVENTOS_FOLHA.MATRÍCULA
AND _HORAS.[PERÍODO BASE] = _EVENTOS_FOLHA.DATA
GO