SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_CENTROS_RESULTADO_SENIOR] 
AS SELECT 
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',E044CCU.CODEMP) 'COD EMPRESA SENIOR',
UPPER(E070EMP.sigemp) 'EMPRESA SENIOR',
CONCAT_WS('-','MIB',E044CCU.CODEMP,E044CCU.CODCCU) 'KEY CR SENIOR',
UPPER(DESCCU) AS 'CENTRO RESULTADO SENIOR'
FROM SAPIENS.SAPIENS.E044CCU WITH (NOLOCK)
LEFT JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK)
ON E044CCU.CODEMP = E070EMP.CODEMP
UNION ALL

SELECT 
'MML' AS 'SERVIDOR',
CONCAT_WS('-','MML',E044CCU.CODEMP) 'COD EMPRESA SENIOR',
UPPER(E070EMP.sigemp) 'EMPRESA SENIOR',
CONCAT_WS('-','MML',E044CCU.CODEMP,E044CCU.CODCCU) 'KEY CR SENIOR',
UPPER(DESCCU) AS 'CENTRO RESULTADO SENIOR'
FROM [SQLMML].[Sapiens_Prod].[dbo].[E044CCU] WITH (NOLOCK)
LEFT JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK)
ON E044CCU.CODEMP = E070EMP.CODEMP

GO