SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_MOVIMENTAÇÕES_EQUIPAMENTOS] 
AS SELECT
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',APLIC.CODEMP) 'KEY EMPRESA',
APLIC.CODEMP 'COD EMPRESA',
APLIC.CODFIL 'COD FILIAL',
CONCAT_WS('-','MIB',APLIC.CODEMP,APLIC.CODFIL) 'KEY FILIAL',
TIPAPLIC.DESCRICAO 'TIPO EQUIPAMENTO',
CONCAT_WS('-','MIB',MOVAPL.CODAPL ) 'COD EQUIPAMENTO',
--MOVAPL.CODAPL 'COD APLICAÇÃO',
APLIC.TAG 'TAG APLICAÇÃO',
APLIC.DESCRICAO 'APLICAÇÃO',
APLIC.MODELO 'MODELO',

MOVAPL.CODMOVAPL 'COD MOVIMENTAÇÃO',
CONCAT_WS('-','MIB',MOVAPL.CODMOVAPL) 'KEY MOVIMENTAÇÃO',

CAST(MOVAPL.DATINI AS DATE) 'DATA INSTALAÇÃO',
CAST(MOVAPL.DATFIM AS DATE) 'DATA REMOÇÃO',
MOVAPL.VALINI '#VALOR INICIAL',
MOVAPL.VALFIM '#VALOR FINAL',
IIF(MOVAPL.VALFIM IS NULL,NULL,COALESCE(MOVAPL.VALFIM ,0)-COALESCE(MOVAPL.VALINI,0) )'#VALOR MOVIMENTO',
CONCAT_WS('-','MML',MOVAPL.CODAPL_NEW) 'COD EQUIPAMENTO PAI',
_APL_PAI.TAG 'TAG EQUIPAMENTO PAI',
_APL_PAI.DESCRICAO 'EQUIPAMENTO PAI',

MOVAPL.CODFOR 'COD FORNECEDOR',
CONCAT_WS('-','MIB',MOVAPL.CODFOR) 'KEY FORNECEDOR',
FORNECEDOR.NOMFAN 'FORNECEDOR',

LOCAPLIC.CODLOCAPL 'COD LOCAL',
CONCAT_WS('-','MIB',LOCAPLIC.CODLOCAPL) 'KEY LOCAL',
LOCAPLIC.TAG 'TAG LOCAL',
LOCAPLIC.DESCRICAO 'LOCAL',
SERVICO.CODSER 'COD SERVIÇO',
CONCAT_WS('-','MIB',LOCAPLIC.CODLOCAPL) 'KEY SERVICO.CODSER',
SERVICO.TAG 'TAG SERVIÇO',
SERVICO.DESCRICAO 'SERVIÇO'


FROM ENGEMAN.ENGEMAN.MOVAPL  WITH (NOLOCK)


LEFT JOIN ENGEMAN.ENGEMAN.APLIC  WITH (NOLOCK)
  ON MOVAPL.CODAPL = APLIC.CODAPL

LEFT JOIN Engeman.Engeman.TIPAPLIC WITH (NOLOCK)
ON APLIC.CODTIPAPL = TIPAPLIC.CODTIPAPL

LEFT JOIN ENGEMAN.ENGEMAN.APLIC _APL_PAI  WITH (NOLOCK)
  ON MOVAPL.CODAPL_NEW = _APL_PAI.CODAPL

LEFT JOIN ENGEMAN.ENGEMAN.FORNECEDOR  WITH (NOLOCK)
  ON MOVAPL.CODFOR = FORNECEDOR.CODFOR

LEFT JOIN ENGEMAN.ENGEMAN.LOCAPLIC  WITH (NOLOCK)
  ON MOVAPL.CODLOCAPL_NEW = LOCAPLIC.CODLOCAPL

LEFT JOIN ENGEMAN.ENGEMAN.SERVICO  WITH (NOLOCK)
  ON MOVAPL.CODSER = SERVICO.CODSER

UNION ALL


SELECT
'MML' AS 'SERVIDOR',
CONCAT_WS('-','MML',APLIC.CODEMP) 'KEY EMPRESA',
APLIC.CODEMP 'COD EMPRESA',
APLIC.CODFIL 'COD FILIAL',
CONCAT_WS('-','MML',APLIC.CODEMP,APLIC.CODFIL) 'KEY FILIAL',
TIPAPLIC.DESCRICAO 'TIPO EQUIPAMENTO',
CONCAT_WS('-','MML',MOVAPL.CODAPL ) 'COD EQUIPAMENTO',
--MOVAPL.CODAPL 'COD APLICAÇÃO',
APLIC.TAG 'TAG APLICAÇÃO',
APLIC.DESCRICAO 'APLICAÇÃO',
APLIC.MODELO 'MODELO',

MOVAPL.CODMOVAPL 'COD MOVIMENTAÇÃO',
CONCAT_WS('-','MML',MOVAPL.CODMOVAPL) 'KEY MOVIMENTAÇÃO',

CAST(MOVAPL.DATINI AS DATE) 'DATA INSTALAÇÃO',
CAST(MOVAPL.DATFIM AS DATE) 'DATA REMOÇÃO',
MOVAPL.VALINI '#VALOR INICIAL',
MOVAPL.VALFIM '#VALOR FINAL',
IIF(MOVAPL.VALFIM IS NULL,NULL,COALESCE(MOVAPL.VALFIM ,0)-COALESCE(MOVAPL.VALINI,0) )'#VALOR MOVIMENTO',
CONCAT_WS('-','MML',MOVAPL.CODAPL_NEW) 'COD EQUIPAMENTO PAI',
_APL_PAI.TAG 'TAG EQUIPAMENTO PAI',
_APL_PAI.DESCRICAO 'EQUIPAMENTO PAI',

MOVAPL.CODFOR 'COD FORNECEDOR',
CONCAT_WS('-','MML',MOVAPL.CODFOR) 'KEY FORNECEDOR',
FORNECEDOR.NOMFAN 'FORNECEDOR',

LOCAPLIC.CODLOCAPL 'COD LOCAL',
CONCAT_WS('-','MML',LOCAPLIC.CODLOCAPL) 'KEY LOCAL',
LOCAPLIC.TAG 'TAG LOCAL',
LOCAPLIC.DESCRICAO 'LOCAL',
SERVICO.CODSER 'COD SERVIÇO',
CONCAT_WS('-','MML',LOCAPLIC.CODLOCAPL) 'KEY SERVICO.CODSER',
SERVICO.TAG 'TAG SERVIÇO',
SERVICO.DESCRICAO 'SERVIÇO'


FROM [SQLMML].[ENGEMAN].[engeman].[MOVAPL] WITH (NOLOCK)

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[APLIC]  WITH (NOLOCK)
  ON MOVAPL.CODAPL = APLIC.CODAPL

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[TIPAPLIC] WITH (NOLOCK)
ON APLIC.CODTIPAPL = TIPAPLIC.CODTIPAPL

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[APLIC] _APL_PAI  WITH (NOLOCK)
  ON MOVAPL.CODAPL_NEW = _APL_PAI.CODAPL

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FORNECEDOR]  WITH (NOLOCK)
  ON MOVAPL.CODFOR = FORNECEDOR.CODFOR

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[LOCAPLIC]  WITH (NOLOCK)
  ON MOVAPL.CODLOCAPL_NEW = LOCAPLIC.CODLOCAPL

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[SERVICO]  WITH (NOLOCK)
  ON MOVAPL.CODSER = SERVICO.CODSER
GO