SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_SOLICITAÇÕES] 
AS SELECT 
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',SOLICITACAO.CODEMP,SOLICITACAO.CODSOL) 'KEY SOLICITAÇÃO',
EMPRESA.NOMFAN 'EMPRESA',
FILIAL.RAZSOC 'FILIAL',
SOLICITACAO.IdentificadorUnicoRaja 'ID SOLICITAÇÃO RAJAMINE',
CONCAT_WS('-','MIB',SOLICITACAO.CODSOL) 'COD SOLICITAÇÃO',             --Código da solicitação
CONCAT_WS('-','MIB',SOLICITACAO.CODEMP) 'COD EMPRESA',             --Código da Empresa
CONCAT_WS('-','MIB',SOLICITACAO.CODFIL) 'COD FILIAL',             --Código da Filial
SOLICITACAO.APROVADO 'APROVADO',             --solicitação aprovada pelo solicitante- S/N
CONCAT_WS('-','MIB',SOLICITACAO.CODAPL) 'COD EQUIPAMENTO ENGEMAN',             --Código da Aplicação
IIF(SOLICITACAO.CODAPL IS NULL,'NÃO INFORMADO', UPPER(CONCAT_WS('-',SOLICITACAO.CODAPL,APLIC.TAG)))'EQUIPAMENTO ENGEMAN',
CONCAT_WS('-','MIB',SOLICITACAO.CODCEN) 'COD CR',   
UPPER(COALESCE(CENCUS.DESCRICAO, 'NÃO INFORADO')) 'CENTRO RESULTADO',          --Código do Centro de Custo
CONCAT_WS('-','MIB',SOLICITACAO.CODEMPTIPM) 'CODEMPTIPM',             --Código da Empresa
CONCAT_WS('-','MIB',SOLICITACAO.CODFUN) 'COD RESPONSÁVEL',             --Código do funcionário responsável
CONCAT_WS('-','MIB',SOLICITACAO.CODFUN_1) 'COD SOLICITANTE',             --Código do funcionário que gerou a O.S.
CONCAT_WS('-','MIB',SOLICITACAO.CODFUN_2) 'COD FUNC CANCELAMENTO',             --Código do funcionário que cancelou a S.S.
CONCAT_WS('-','MIB',SOLICITACAO.CODFUN_3) 'COD FUNC APROVAÇÃO',             --Código do funcionário que aprovou a S.S.
CONCAT_WS('-','MIB',SOLICITACAO.CODLOCAPL) 'COD LOCALIZAÇÃO APLICAÇÃO',             --Código da localização da aplicação
UPPER(COALESCE(LOCAPLIC.DESCRICAO, 'NÃO INFORADO')) 'LOCALIZAÇÃO',
SOLICITACAO.CODSET 'COD SETOR EXECUÇÃO',             --Código do setor executante
CONCAT_WS('-','MIB',SOLICITACAO.CODTIPMAN) 'COD TIPO MANUTENÇÃO',             --Código do tipo de manutenção
UPPER(COALESCE(TIPMANUT.DESCRICAO, 'NÃO INFORADO')) 'TIPO MANUTENÇÃO',
CAST(SOLICITACAO.DATALT AS DATE) 'DATA ALTERAÇÃO',             --Data de Alteração
CAST(SOLICITACAO.DATAPR AS DATE) 'DATA APROVAÇÃO',             --Data de aprovação do serviço
CAST(SOLICITACAO.DATAPRSOL AS DATE) 'DATA APROVAÇÃO OU REPROVAÇÃO',             --Data de aprovação/reprovação do solicitante
CAST(SOLICITACAO.DATCAN AS DATE) 'DATA CANCELAMENTO',             --Data cancelamento
CAST(SOLICITACAO.DATCON  AS DATE)'DATA CONSUMO',             --Data de consumo
CAST(SOLICITACAO.DATENT AS DATE) 'DATA ENTREGA PREVISTA',             --Data da entrega prevista
CAST(SOLICITACAO.DATFLUXO AS DATE) 'DATA FLUXO',             --Data em que o Fluxo foi adicionado à O.S.
CAST(SOLICITACAO.DATRECFLUXO AS DATE) 'DATA RECONHECIMENTO FLUXO',             --Data em que o Fluxo foi reconhecido
CAST(SOLICITACAO.DATSOL AS DATE) 'DATA SOLICITAÇÃO',             --Data da solicitação
SOLICITACAO.INTERFERENCIA 'INTERFERENCIA',             --Houve interferência- S/N
SOLICITACAO.NOME_APROVOU 'NOME FUNC APROVAÇÃO' ,            --Nome do usuário que aprovou a S.S.

UPPER(CASE STATUS_SS.STATUSN
WHEN 1 THEN 'Aberta Não Avaliada'
WHEN 2 THEN 'Aberta Aprovada'
WHEN 3 THEN 'Cancelada'
WHEN 4 THEN 'Concluída Não Avaliada'
WHEN 5 THEN 'Concluída Aprovada'
WHEN 6 THEN 'Concluída Aprovada'
WHEN 7 THEN 'Serviço Reprovado'
WHEN 0 THEN ''   END )   'STATUS',

UPPER(CASE STATUS_SS.STATUSN
WHEN 1 THEN 'ABERTA'
WHEN 2 THEN 'APROVADA'
WHEN 3 THEN 'CANCELADA'
WHEN 4 THEN 'CONCLUÍDA'
WHEN 5 THEN 'CONCLUÍDA'
WHEN 6 THEN 'CONCLUÍDA'
WHEN 7 THEN 'REPROVADA'
WHEN 0 THEN ''   END )   'GRUPO STATUS',
MOTCAN.DESCRICAO  'MOTIVO CANCELAMENTO',
SOLICITACAO.OBSCAN  'OBSERVAÇÃO CANCELAMENTO',
(SELECT COUNT(1)
FROM Engeman.Engeman.ORDSERV O  WITH (NOLOCK) 
WHERE O.CODSOL = SOLICITACAO.CODSOL
AND O.CODEMP = SOLICITACAO.CODEMP)  '#QUANTIDADE OS'
--IIF(VW_EQUIPAMENTOS_ENGEMAN.CONTROLA IS NULL,'NÃO',  VW_EQUIPAMENTOS_ENGEMAN.CONTROLA) 'CONTROLA'




FROM Engeman.Engeman.SOLICITACAO WITH (NOLOCK)

INNER JOIN Engeman.Engeman.FILIAL WITH (NOLOCK)    ON FILIAL.CODFIL      = SOLICITACAO.CODFIL
INNER JOIN Engeman.Engeman.STATUS_SS WITH (NOLOCK) ON STATUS_SS.CODSOL   = SOLICITACAO.CODSOL
LEFT JOIN Engeman.Engeman.APLIC WITH (NOLOCK)     ON APLIC.CODAPL       = SOLICITACAO.CODAPL
LEFT JOIN Engeman.Engeman.CENCUS WITH (NOLOCK)    ON CENCUS.CODCEN      = SOLICITACAO.CODCEN
LEFT JOIN Engeman.Engeman.CLIENTE WITH (NOLOCK)   ON CLIENTE.CODCLI     = SOLICITACAO.CODCLI
LEFT JOIN Engeman.Engeman.CONTATOS WITH (NOLOCK)  ON CONTATOS.CODCON    = SOLICITACAO.CODCON
LEFT JOIN Engeman.Engeman.FUNC A  WITH (NOLOCK)    ON A.CODFUN           = SOLICITACAO.CODFUN
LEFT JOIN Engeman.Engeman.FUNC B WITH (NOLOCK)    ON B.CODFUN           = SOLICITACAO.CODFUN_1
LEFT JOIN Engeman.Engeman.FUNC C WITH (NOLOCK)    ON C.CODFUN           = SOLICITACAO.CODFUN_2
LEFT JOIN Engeman.Engeman.LOCAPLIC WITH (NOLOCK)  ON LOCAPLIC.CODLOCAPL = SOLICITACAO.CODLOCAPL
LEFT JOIN Engeman.Engeman.MOTCAN WITH (NOLOCK)    ON MOTCAN.CODMOTCAN   = SOLICITACAO.CODMOTCAN
LEFT JOIN Engeman.Engeman.SETEXE WITH (NOLOCK)    ON SETEXE.CODSET      = SOLICITACAO.CODSET  
LEFT JOIN Engeman.Engeman.TIPMANUT WITH (NOLOCK)  ON TIPMANUT.CODTIPMAN = SOLICITACAO.CODTIPMAN
LEFT JOIN Engeman.Engeman.EMPRESA WITH (NOLOCK)  ON SOLICITACAO.CODEMP = EMPRESA.CODEMP

--LEFT JOIN VW_EQUIPAMENTOS_ENGEMAN
--ON CONCAT_WS('-','MIB',SOLICITACAO.CODAPL) = VW_EQUIPAMENTOS_ENGEMAN.[COD EQUIPAMENTO]

LEFT JOIN (SELECT COUNT(1) QTDE,
AVAXSOL.CODSOL
FROM Engeman.Engeman.AVAXSOL WITH (NOLOCK)
GROUP BY AVAXSOL.CODSOL) AVAXSOL ON SOLICITACAO.CODSOL = AVAXSOL.CODSOL
LEFT JOIN (SELECT FIL.TIPO AS TIPO 
FROM (SELECT 'S' AS TIPO FROM Engeman.Engeman.CFGGERAL WITH (NOLOCK)
UNION ALL
SELECT 'N' AS TIPO FROM Engeman.Engeman.CFGGERAL WITH (NOLOCK)) FIL
WHERE 1=3) FIL ON 'A'='A'

WHERE YEAR(SOLICITACAO.DATSOL) >=2024
--AND VW_EQUIPAMENTOS_ENGEMAN.CONTROLA = 'SIM'


UNION ALL


SELECT 
'MML' AS 'SERVIDOR',
CONCAT_WS('-','MML',SOLICITACAO.CODEMP,SOLICITACAO.CODSOL) 'KEY SOLICITAÇÃO',
EMPRESA.NOMFAN 'EMPRESA',
FILIAL.RAZSOC 'FILIAL',
SOLICITACAO.IdentificadorUnicoRaja 'ID SOLICITAÇÃO RAJAMINE',
CONCAT_WS('-','MML',SOLICITACAO.CODSOL) 'COD SOLICITAÇÃO',             --Código da solicitação
CONCAT_WS('-','MML',SOLICITACAO.CODEMP) 'COD EMPRESA',             --Código da Empresa
CONCAT_WS('-','MML',SOLICITACAO.CODFIL) 'COD FILIAL',             --Código da Filial
SOLICITACAO.APROVADO 'APROVADO',             --solicitação aprovada pelo solicitante- S/N
CONCAT_WS('-','MML',SOLICITACAO.CODAPL) 'COD EQUIPAMENTO ENGEMAN',             --Código da Aplicação
IIF(SOLICITACAO.CODAPL IS NULL,'NÃO INFORMADO', UPPER(CONCAT_WS('-',SOLICITACAO.CODAPL,APLIC.DESCRICAO))) 'EQUIPAMENTO ENGEMAN',
CONCAT_WS('-','MML',SOLICITACAO.CODCEN) 'COD CR',             --Código do Centro de Custo
UPPER(COALESCE(CENCUS.DESCRICAO, 'NÃO INFORADO')) 'CENTRO RESULTADO',
CONCAT_WS('-','MML',SOLICITACAO.CODEMPTIPM) 'CODEMPTIPM',             --Código da Empresa
CONCAT_WS('-','MML',SOLICITACAO.CODFUN) 'COD RESPONSÁVEL',             --Código do funcionário responsável
CONCAT_WS('-','MML',SOLICITACAO.CODFUN_1) 'COD SOLICITANTE',             --Código do funcionário que gerou a O.S.
CONCAT_WS('-','MML',SOLICITACAO.CODFUN_2) 'COD FUNC CANCELAMENTO',             --Código do funcionário que cancelou a S.S.
CONCAT_WS('-','MML',SOLICITACAO.CODFUN_3) 'COD FUNC APROVAÇÃO',             --Código do funcionário que aprovou a S.S.
CONCAT_WS('-','MML',SOLICITACAO.CODLOCAPL) 'COD LOCALIZAÇÃO APLICAÇÃO',             --Código da localização da aplicação
UPPER(COALESCE(LOCAPLIC.DESCRICAO, 'NÃO INFORADO')) 'LOCALIZAÇÃO',

SOLICITACAO.CODSET 'COD SETOR EXECUÇÃO',             --Código do setor executante
CONCAT_WS('-','MML',SOLICITACAO.CODTIPMAN) 'COD TIPO MANUTENÇÃO',             --Código do tipo de manutenção
UPPER(COALESCE(TIPMANUT.DESCRICAO, 'NÃO INFORADO')) 'TIPO MANUTENÇÃO',
CAST(SOLICITACAO.DATALT AS DATE) 'DATA ALTERAÇÃO',             --Data de Alteração
CAST(SOLICITACAO.DATAPR AS DATE) 'DATA APROVAÇÃO',             --Data de aprovação do serviço
CAST(SOLICITACAO.DATAPRSOL AS DATE) 'DATA APROVAÇÃO OU REPROVAÇÃO',             --Data de aprovação/reprovação do solicitante
CAST(SOLICITACAO.DATCAN AS DATE) 'DATA CANCELAMENTO',             --Data cancelamento
CAST(SOLICITACAO.DATCON  AS DATE)'DATA CONSUMO',             --Data de consumo
CAST(SOLICITACAO.DATENT AS DATE) 'DATA ENTREGA PREVISTA',             --Data da entrega prevista
CAST(SOLICITACAO.DATFLUXO AS DATE) 'DATA FLUXO',             --Data em que o Fluxo foi adicionado à O.S.
CAST(SOLICITACAO.DATRECFLUXO AS DATE) 'DATA RECONHECIMENTO FLUXO',             --Data em que o Fluxo foi reconhecido
CAST(SOLICITACAO.DATSOL AS DATE) 'DATA SOLICITAÇÃO',
SOLICITACAO.INTERFERENCIA 'INTERFERENCIA',             --Houve interferência- S/N
SOLICITACAO.NOME_APROVOU 'NOME FUNC APROVAÇÃO' ,            --Nome do usuário que aprovou a S.S.

UPPER(CASE STATUS_SS.STATUSN
WHEN 1 THEN 'Aberta Não Avaliada'
WHEN 2 THEN 'Aberta Aprovada'
WHEN 3 THEN 'Cancelada'
WHEN 4 THEN 'Concluída Não Avaliada'
WHEN 5 THEN 'Concluída Aprovada'
WHEN 6 THEN 'Concluída Aprovada'
WHEN 7 THEN 'Serviço Reprovado'
WHEN 0 THEN ''   END )   'STATUS',

UPPER(CASE STATUS_SS.STATUSN
WHEN 1 THEN 'ABERTA'
WHEN 2 THEN 'APROVADA'
WHEN 3 THEN 'CANCELADA'
WHEN 4 THEN 'CONCLUÍDA'
WHEN 5 THEN 'CONCLUÍDA'
WHEN 6 THEN 'CONCLUÍDA'
WHEN 7 THEN 'REPROVADA'
WHEN 0 THEN ''   END )   'GRUPO STATUS',
MOTCAN.DESCRICAO  'MOTIVO CANCELAMENTO',
SOLICITACAO.OBSCAN  'OBSERVAÇÃO CANCELAMENTO',
(SELECT COUNT(1)
FROM [SQLMML].[ENGEMAN].[engeman].[ORDSERV] O  WITH (NOLOCK) 
WHERE O.CODSOL = SOLICITACAO.CODSOL
AND O.CODEMP = SOLICITACAO.CODEMP)  '#QUANTIDADE OS'--,
--IIF(VW_EQUIPAMENTOS_ENGEMAN.CONTROLA IS NULL,'NÃO',  VW_EQUIPAMENTOS_ENGEMAN.CONTROLA) 'CONTROLA'  




FROM [SQLMML].[ENGEMAN].[engeman].[SOLICITACAO] WITH (NOLOCK)

INNER JOIN [SQLMML].[ENGEMAN].[engeman].[FILIAL] WITH (NOLOCK)    ON FILIAL.CODFIL      = SOLICITACAO.CODFIL
INNER JOIN [SQLMML].[ENGEMAN].[engeman].[STATUS_SS] WITH (NOLOCK) ON STATUS_SS.CODSOL   = SOLICITACAO.CODSOL
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[APLIC] WITH (NOLOCK)     ON APLIC.CODAPL       = SOLICITACAO.CODAPL
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CENCUS] WITH (NOLOCK)    ON CENCUS.CODCEN      = SOLICITACAO.CODCEN
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CLIENTE] WITH (NOLOCK)   ON CLIENTE.CODCLI     = SOLICITACAO.CODCLI
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CONTATOS] WITH (NOLOCK)  ON CONTATOS.CODCON    = SOLICITACAO.CODCON
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] A  WITH (NOLOCK)    ON A.CODFUN           = SOLICITACAO.CODFUN
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] B WITH (NOLOCK)    ON B.CODFUN           = SOLICITACAO.CODFUN_1
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] C WITH (NOLOCK)    ON C.CODFUN           = SOLICITACAO.CODFUN_2
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[LOCAPLIC] WITH (NOLOCK)  ON LOCAPLIC.CODLOCAPL = SOLICITACAO.CODLOCAPL
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[MOTCAN] WITH (NOLOCK)    ON MOTCAN.CODMOTCAN   = SOLICITACAO.CODMOTCAN
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[SETEXE] WITH (NOLOCK)    ON SETEXE.CODSET      = SOLICITACAO.CODSET  
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[TIPMANUT] WITH (NOLOCK)  ON TIPMANUT.CODTIPMAN = SOLICITACAO.CODTIPMAN
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[EMPRESA] WITH (NOLOCK)  ON SOLICITACAO.CODEMP = EMPRESA.CODEMP

--LEFT JOIN VW_EQUIPAMENTOS_ENGEMAN
--ON CONCAT_WS('-','MML',SOLICITACAO.CODAPL) = VW_EQUIPAMENTOS_ENGEMAN.[COD EQUIPAMENTO]

LEFT JOIN (SELECT COUNT(1) QTDE,
AVAXSOL.CODSOL
FROM [SQLMML].[ENGEMAN].[engeman].[AVAXSOL] WITH (NOLOCK)
GROUP BY AVAXSOL.CODSOL) AVAXSOL ON SOLICITACAO.CODSOL = AVAXSOL.CODSOL
LEFT JOIN (SELECT FIL.TIPO AS TIPO 
FROM (SELECT 'S' AS TIPO FROM [SQLMML].[ENGEMAN].[engeman].[CFGGERAL] WITH (NOLOCK)
UNION ALL
SELECT 'N' AS TIPO FROM [SQLMML].[ENGEMAN].[engeman].[CFGGERAL] WITH (NOLOCK)) FIL
WHERE 1=3) FIL ON 'A'='A'

WHERE YEAR(SOLICITACAO.DATSOL) >=2024
--AND VW_EQUIPAMENTOS_ENGEMAN.CONTROLA = 'SIM'
GO