SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_TIPO_MANUTENÇÃO] 
AS SELECT 
CODEMP 'COD EMPRESA',
CODTIPMAN 'COD TIPO MANUTENÇÃO',
TIPMANUT.TAG + ' - ' + TIPMANUT.DESCRICAO 'TIPO',
PRIORIDADE 'PRIORIDADE',             
TAG 'TAG',
DESCRICAO 'TIPO MANUTENÇÃO'

FROM Engeman.Engeman.TIPMANUT WITH (NOLOCK)
GO