SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_PREVISÃO_MANUTENÇÃO] AS


  SELECT
    'MIB' AS 'SERVIDOR'
   ,E.CODEMP 'COD EMPRESA'
   ,E.RAZSOC 'EMPRESA'
   ,F.CODFIL 'COD FILIAL'
   ,F.RAZSOC 'FILIAL'
   ,A.TAG 'TAG EQUIPAMENTO'
   ,A.DESCRICAO 'EQUIPAMENTO'
   ,UPPER(CAST('Planos Periódicos' AS VARCHAR(30))) AS 'TIPO PLANO'
   ,PM.TAG + ' - ' + PM.DESCRICAO AS 'PLANO MANUTENCAO'
   ,CAST(PP.PERPLA AS DECIMAL(18, 2)) AS '#LIMITE'
   ,CAST(PP.DATULTMAN AS DATE) AS 'DATA ÚLTIMA MANUTENÇÃO'
   ,CAST(Engeman.Engeman.PROXPLAPER(
    PP.DATULTMAN,
    CAST(PP.PERPLA AS NUMERIC(18, 0)),
    PP.DATINI,
    PP.DATFIM
    ) AS DATE) AS 'DATA PRÓXIMA MANUTENÇÃO'
  FROM Engeman.Engeman.PLAPER PP WITH (NOLOCK)
  INNER JOIN Engeman.Engeman.APLIC A WITH (NOLOCK)
    ON A.CODAPL = PP.CODAPL
  INNER JOIN Engeman.Engeman.PLAMANUT PM WITH (NOLOCK)
    ON PM.CODPLA = PP.CODPLA
  INNER JOIN Engeman.Engeman.EMPRESA E WITH (NOLOCK)
    ON E.CODEMP = A.CODEMP
  INNER JOIN Engeman.Engeman.FILIAL F WITH (NOLOCK)
    ON F.CODFIL = A.CODFIL
    AND F.CODEMP = A.CODEMP
  WHERE PP.DATULTMAN IS NOT NULL
  AND EXISTS (SELECT
      1
    FROM Engeman.Engeman.PLAXSET PS WITH (NOLOCK)
    INNER JOIN Engeman.Engeman.SETEXE SE WITH (NOLOCK)
      ON SE.CODSET = PS.CODSET
    WHERE PS.CODPLA = PP.CODPLA)

  UNION ALL

  -- Planos Acumulativos
  SELECT
    'MIB' AS 'SERVIDOR'
   ,E.CODEMP 'COD EMPRESA'
   ,E.RAZSOC 'EMPRESA'
   ,F.CODFIL 'COD FILIAL'
   ,F.RAZSOC 'FILIAL'
   ,A.TAG 'TAG EQUIPAMENTO'
   ,A.DESCRICAO 'EQUIPAMENTO'
   ,CAST('Planos Acumulativos' AS VARCHAR(30)) AS 'TIPO PLANO'
   ,PM.TAG + ' - ' + PM.DESCRICAO AS 'PLANO MANUTENCAO'
   ,CAST(PA.VALOR AS DECIMAL(18, 2)) AS '#LIMITE'
   ,CAST(PA.DATULTMAN AS DATE) AS 'DATA ÚLTIMA MANUTENÇÃO'
   ,CAST(PA.DATPROXMAN AS DATE) AS 'DATA PRÓXIMA MANUTENÇÃO'
  FROM Engeman.Engeman.PLAACU PA WITH (NOLOCK)
  INNER JOIN Engeman.Engeman.PONCONACU PC WITH (NOLOCK)
    ON PC.CODAPL = PA.CODAPL
    AND PC.CODPONACU = PA.CODPONACU
  INNER JOIN Engeman.Engeman.APLIC A WITH (NOLOCK)
    ON A.CODAPL = PC.CODAPL
  INNER JOIN Engeman.Engeman.PLAMANUT PM WITH (NOLOCK)
    ON PM.CODPLA = PA.CODPLA
  INNER JOIN Engeman.Engeman.EMPRESA E WITH (NOLOCK)
    ON E.CODEMP = A.CODEMP
  INNER JOIN Engeman.Engeman.FILIAL F WITH (NOLOCK)
    ON F.CODFIL = A.CODFIL
    AND F.CODEMP = A.CODEMP
  WHERE PA.DATULTMAN IS NOT NULL
  AND EXISTS (SELECT
      1
    FROM Engeman.Engeman.PLAXSET PS WITH (NOLOCK)
    INNER JOIN Engeman.Engeman.SETEXE SE WITH (NOLOCK)
      ON SE.CODSET = PS.CODSET
    WHERE PS.CODPLA = PA.CODPLA)


UNION ALL


  SELECT
    'MML' AS 'SERVIDOR'
   ,E.CODEMP 'COD EMPRESA'
   ,E.RAZSOC 'EMPRESA'
   ,F.CODFIL 'COD FILIAL'
   ,F.RAZSOC 'FILIAL'
   ,A.TAG 'TAG EQUIPAMENTO'
   ,A.DESCRICAO 'EQUIPAMENTO'
   ,CAST('Planos Periódicos' AS VARCHAR(30)) AS 'TIPO PLANO'
   ,PM.TAG + ' - ' + PM.DESCRICAO AS 'PLANO MANUTENCAO'
   ,CAST(PP.PERPLA AS DECIMAL(18, 2)) AS '#LIMITE'
   ,CAST(PP.DATULTMAN AS DATE) AS 'DATA ÚLTIMA MANUTENÇÃO'
   ,CAST(Engeman.engeman.PROXPLAPER(
    PP.DATULTMAN,
    CAST(PP.PERPLA AS NUMERIC(18, 0)),
    PP.DATINI,
    PP.DATFIM
    ) AS DATE) AS 'DATA PRÓXIMA MANUTENÇÃO'
  FROM [SQLMML].[ENGEMAN].[engeman].PLAPER PP WITH (NOLOCK)
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].APLIC A WITH (NOLOCK)
    ON A.CODAPL = PP.CODAPL
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].PLAMANUT PM WITH (NOLOCK)
    ON PM.CODPLA = PP.CODPLA
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].EMPRESA E WITH (NOLOCK)
    ON E.CODEMP = A.CODEMP
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].FILIAL F WITH (NOLOCK)
    ON F.CODFIL = A.CODFIL
    AND F.CODEMP = A.CODEMP
  WHERE PP.DATULTMAN IS NOT NULL
  AND EXISTS (SELECT
      1
    FROM [SQLMML].[ENGEMAN].[engeman].PLAXSET PS WITH (NOLOCK)
    INNER JOIN [SQLMML].[ENGEMAN].[engeman].SETEXE SE WITH (NOLOCK)
      ON SE.CODSET = PS.CODSET
    WHERE PS.CODPLA = PP.CODPLA)

  UNION ALL

  -- Planos Acumulativos
  SELECT
    'MML' AS 'SERVIDOR'
   ,E.CODEMP 'COD EMPRESA'
   ,E.RAZSOC 'EMPRESA'
   ,F.CODFIL 'COD FILIAL'
   ,F.RAZSOC 'FILIAL'
   ,A.TAG 'TAG EQUIPAMENTO'
   ,A.DESCRICAO 'EQUIPAMENTO'
   ,UPPER(CAST('Planos Acumulativos' AS VARCHAR(30))) AS 'TIPO PLANO'
   ,PM.TAG + ' - ' + PM.DESCRICAO AS 'PLANO MANUTENCAO'
   ,CAST(PA.VALOR AS DECIMAL(18, 2)) AS '#LIMITE'
   ,CAST(PA.DATULTMAN AS DATE) AS 'DATA ÚLTIMA MANUTENÇÃO'
   ,CAST(PA.DATPROXMAN AS DATE) AS 'DATA PRÓXIMA MANUTENÇÃO'
  FROM [SQLMML].[ENGEMAN].[engeman].PLAACU PA WITH (NOLOCK)
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].PONCONACU PC WITH (NOLOCK)
    ON PC.CODAPL = PA.CODAPL
    AND PC.CODPONACU = PA.CODPONACU
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].APLIC A WITH (NOLOCK)
    ON A.CODAPL = PC.CODAPL
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].PLAMANUT PM WITH (NOLOCK)
    ON PM.CODPLA = PA.CODPLA
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].EMPRESA E WITH (NOLOCK)
    ON E.CODEMP = A.CODEMP
  INNER JOIN [SQLMML].[ENGEMAN].[engeman].FILIAL F WITH (NOLOCK)
    ON F.CODFIL = A.CODFIL
    AND F.CODEMP = A.CODEMP
  WHERE PA.DATULTMAN IS NOT NULL
  AND EXISTS (SELECT
      1
    FROM [SQLMML].[ENGEMAN].[engeman].PLAXSET PS WITH (NOLOCK)
    INNER JOIN [SQLMML].[ENGEMAN].[engeman].SETEXE SE WITH (NOLOCK)
      ON SE.CODSET = PS.CODSET
    WHERE PS.CODPLA = PA.CODPLA)










GO