SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_CUSTO_HH_OS] 
AS SELECT
_DADOS.*,
ROUND(CAST(VW_CUSTO_PESSOAL.[#VALOR HORA] AS FLOAT),2) '#VALOR HH BASE',
ROUND(COALESCE(_DADOS.[#HORAS],0)*VW_CUSTO_PESSOAL.[#VALOR HORA],2) '#CUSTO HH'
FROM(

SELECT
CONCAT_WS('-', 'MIB',ORDXFUN.CODORD) 'COD OS', 
CONCAT_WS('-', 'MIB',ORDXFUN.CODEMP) 'COD EMPRESA',
CONCAT('MIB-', ORDSERV.CODAPL) AS 'COD EQUIPAMENTO ENGEMAN',
CONCAT_WS('-', 'MIB',ORDXFUN.CODEMP, CAST(FUNC.TAG AS INT)) 'KEY MATRÍCULA',
UPPER(FUNC.NOME) 'FUNCIONÁRIO',
CAST(DATEADD(month, DATEDIFF(month, 0, DATHORFIM), 0) AS DATE) 'PERÍODO BASE', 
CONCAT_WS('-', 'MIB',ORDXFUN.CODFUN) 'COD FUNCIONÁRIO',
ROUND(SUM(ISNULL(CAST(ORDXFUN.DATHORFIM - ORDXFUN.DATHORINI AS FLOAT), 0) * 24),2) '#HORAS'


FROM Engeman.Engeman.ORDXFUN WITH (NOLOCK)
INNER JOIN Engeman.Engeman.FUNC WITH (NOLOCK)
ON ORDXFUN.CODFUN = FUNC.CODFUN

INNER JOIN Engeman.Engeman.ORDSERV WITH (NOLOCK)
ON ORDXFUN.CODORD = ORDSERV.CODORD

WHERE ORDXFUN.PREVISTO = 'R'
AND YEAR( DATHORFIM) >= 2024
AND CHARINDEX('.', FUNC.TAG) < 1
AND ISNUMERIC(FUNC.TAG) =1
GROUP BY 
ORDXFUN.CODORD,
ORDXFUN.CODEMP,
ORDXFUN.CODFUN,
FUNC.NOME,
CAST(DATEADD(month, DATEDIFF(month, 0, DATHORFIM), 0) AS DATE),
CONCAT_WS('-', 'MIB',ORDXFUN.CODEMP, CAST(FUNC.TAG AS INT)),
CONCAT('MIB-', ORDSERV.CODAPL)

UNION ALL

SELECT
CONCAT_WS('-', 'MML',ORDXFUN.CODORD) 'COD OS',
CONCAT_WS('-', 'MML',ORDXFUN.CODEMP) 'COD EMPRESA',
CONCAT('MML-', ORDSERV.CODAPL) AS 'COD EQUIPAMENTO ENGEMAN',
CONCAT_WS('-', 'MML',ORDXFUN.CODEMP, CAST(FUNC.TAG AS INT)) 'KEY MATRÍCULA',
UPPER(FUNC.NOME) 'FUNCIONÁRIO',
CAST(DATEADD(month, DATEDIFF(month, 0, DATHORFIM), 0) AS DATE) 'PERÍODO BASE', 
CONCAT_WS('-', 'MML',ORDXFUN.CODFUN) 'COD FUNCIONÁRIO',
ROUND(SUM(ISNULL(CAST(ORDXFUN.DATHORFIM - ORDXFUN.DATHORINI AS FLOAT), 0) * 24),2) '#HORAS'


FROM [SQLMML].[ENGEMAN].[engeman].[ORDXFUN] WITH (NOLOCK)
INNER JOIN [SQLMML].[ENGEMAN].[engeman].[FUNC] WITH (NOLOCK)
ON ORDXFUN.CODFUN = FUNC.CODFUN


INNER JOIN [SQLMML].[ENGEMAN].[engeman].[ORDSERV] WITH (NOLOCK)
ON ORDXFUN.CODORD = ORDSERV.CODORD

WHERE ORDXFUN.PREVISTO = 'R'
AND YEAR( DATHORFIM) >= 2024
AND CHARINDEX('.', FUNC.TAG) < 1
AND ISNUMERIC(FUNC.TAG) =1
GROUP BY 
ORDXFUN.CODORD,
ORDXFUN.CODEMP,
ORDXFUN.CODFUN,
FUNC.NOME,
CAST(DATEADD(month, DATEDIFF(month, 0, DATHORFIM), 0) AS DATE),
CONCAT_WS('-', 'MML',ORDXFUN.CODEMP, CAST(FUNC.TAG AS INT)),
CONCAT('MML-', ORDSERV.CODAPL)

) _DADOS

LEFT JOIN VW_CUSTO_PESSOAL
ON _DADOS.[KEY MATRÍCULA] = VW_CUSTO_PESSOAL.[KEY MATRÍCULA ENGEMAN]
AND _DADOS.[PERÍODO BASE] = VW_CUSTO_PESSOAL.[PERÍODO BASE]
GO