SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_FILIAIS] 
AS SELECT
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',FILIAL.CODEMP,FILIAL.CODFIL) 'KEY FILIAL'
,CONCAT('MIB-',EMPRESA.CODEMP) 'COD EMPRESA'
,EMPRESA.RAZSOC  'RAZÃO SOCIAL'
,EMPRESA.NOMFAN 'EMPRESA'
,CONCAT('MIB-',FILIAL.CODFIL) 'COD FILIAL'
,FILIAL.RAZSOC 'FILIAL'


FROM Engeman.Engeman.FILIAL  WITH (NOLOCK)

INNER JOIN Engeman.Engeman.EMPRESA WITH (NOLOCK)
ON FILIAL.CODEMP = EMPRESA.CODEMP


UNION ALL

SELECT
'MML' AS 'SERVIDOR',
CONCAT_WS('-','MML',FILIAL.CODEMP,FILIAL.CODFIL) 'KEY FILIAL'
,CONCAT('MML-',EMPRESA.CODEMP) 'COD EMPRESA'
,EMPRESA.RAZSOC  'RAZÃO SOCIAL'
,EMPRESA.NOMFAN 'EMPRESA'
,CONCAT('MML-',FILIAL.CODFIL) 'COD FILIAL'
,FILIAL.RAZSOC 'FILIAL'


FROM [SQLMML].[ENGEMAN].[engeman].[FILIAL]  WITH (NOLOCK)

INNER JOIN [SQLMML].[ENGEMAN].[engeman].[EMPRESA] WITH (NOLOCK)
ON FILIAL.CODEMP = EMPRESA.CODEMP
GO