SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_MATERIAIS_ENGEMAN] 
AS SELECT
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',MATERIAL.CODEMP) 'COD EMPRESA',
CONCAT_WS('-','MIB',MATERIAL.CODMAT) 'COD MATERIAL',
UPPER(MATERIAL.DESCRICAO) 'MATERIAL',
UNIDADE.TAG 'COD UNIDADE',
UNIDADE.DESCRICAO 'UNIDADE',
CONCAT_WS('-','MIB',MATERIAL.CODGRUMAT) 'COD GRUPO MATERIAL',
COALESCE(GRUMAT.DESCRICAO, 'NÃO CLASSIFICADO') 'GRUPO MATERIAL',
CONCAT_WS('-','MIB',MATERIAL.CODCLAMAT) 'COD CLASSE MATERIAL',
COALESCE(CLAMAT.DESCRICAO, 'NÃO CLASSIFICADO') 'CLASSE MATERIAL'


FROM Engeman.Engeman.MATERIAL WITH (NOLOCK)
LEFT JOIN Engeman.Engeman.GRUMAT WITH (NOLOCK)
  ON MATERIAL.CODGRUMAT = GRUMAT.CODGRUMAT
LEFT JOIN Engeman.Engeman.UNIDADE WITH (NOLOCK)
  ON MATERIAL.CODUNI = UNIDADE.CODUNI
LEFT JOIN Engeman.Engeman.CLAMAT WITH (NOLOCK)
  ON MATERIAL.CODCLAMAT = CLAMAT.CODCLAMAT


UNION ALL


SELECT
'MML' AS 'SERVIDOR',
CONCAT_WS('-','MML',MATERIAL.CODEMP) 'COD EMPRESA',
CONCAT_WS('-','MML',MATERIAL.CODMAT) 'COD MATERIAL',
UPPER(MATERIAL.DESCRICAO) 'MATERIAL',
UNIDADE.TAG 'COD UNIDADE',
UNIDADE.DESCRICAO 'UNIDADE',
CONCAT_WS('-','MML',MATERIAL.CODGRUMAT) 'COD GRUPO MATERIAL',
COALESCE(GRUMAT.DESCRICAO, 'NÃO CLASSIFICADO') 'GRUPO MATERIAL',
CONCAT_WS('-','MML',MATERIAL.CODCLAMAT) 'COD CLASSE MATERIAL',
COALESCE(CLAMAT.DESCRICAO, 'NÃO CLASSIFICADO') 'CLASSE MATERIAL'


FROM [SQLMML].[ENGEMAN].[engeman].[MATERIAL] WITH (NOLOCK)
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[GRUMAT] WITH (NOLOCK)
  ON MATERIAL.CODGRUMAT = GRUMAT.CODGRUMAT
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[UNIDADE] WITH (NOLOCK)
  ON MATERIAL.CODUNI = UNIDADE.CODUNI
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CLAMAT] WITH (NOLOCK)
  ON MATERIAL.CODCLAMAT = CLAMAT.CODCLAMAT
GO