SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_MOVIMENTO_BALANÇO] 
AS SELECT
  GETDATE() AS 'DATA HORA ATUALIZAÇÃO'
 ,CONVERT(VARCHAR(10), GETDATE(), 103) 'DATA ATUALIZAÇÃO'
 ,'MIB' AS 'SERVIDOR'
 ,E650SAL.codemp 'COD EMPRESA'
 ,UPPER(EMP.SIGEMP) 'EMPRESA'
 ,E650SAL.codfil 'COD FILIAL'
 ,E650SAL.ctared 'COD REDUZIDO CONTA CONTÁBIL'
 ,PLA.CLACTA  'COD CONTA CONTÁBIL'
 ,UPPER(PLA.descta) 'CONTA CONTÁBIL'
 ,E650SAL.mesano 'DATA'
 ,E650SAL.DEBMES '#DÉBITO'
 ,E650SAL.CREMES '#CRÉDITO'
 --,ABS(E650SAL.salmes) '#SALDO'

 ,ABS(E650SAL.salmes)*
 
 IIF(E650SAL.salmes<0,
 IIF(PLA.NATCTA = 'D',  1,
     IIF(PLA.NATCTA = 'C', 1, -1)),
 IIF(PLA.NATCTA = 'D', -1,
 IIF(PLA.NATCTA = 'C',  -1, 1))) '#SALDO'
 ,CONCAT_WS('-', 'MIB', E650SAL.codemp, PLA.CLACTA) 'KEY CONTA CONTÁBIL'




FROM SAPIENS.SAPIENS.E650SAL WITH (NOLOCK)

-- JOIN: INFORMAÇÕES DA EMPRESA (HASH JOIN PARA PARALELISMO)
LEFT JOIN SAPIENS.SAPIENS.E070EMP EMP WITH (NOLOCK)
  ON E650SAL.CODEMP = EMP.CODEMP

-- JOIN: PLANO DE CONTAS
LEFT JOIN SAPIENS.SAPIENS.E045PLA PLA WITH (NOLOCK)
  ON E650SAL.CODEMP = PLA.CODEMP
    AND E650SAL.CTARED = PLA.CTARED


WHERE E650SAL.ANASIN = 'A'

UNION ALL

SELECT
  GETDATE() AS 'DATA HORA ATUALIZAÇÃO'
 ,CONVERT(VARCHAR(10), GETDATE(), 103) 'DATA ATUALIZAÇÃO'
 ,'MML' AS 'SERVIDOR'
 ,E650SAL.codemp 'COD EMPRESA'
 ,UPPER(EMP.SIGEMP) 'EMPRESA'
 ,E650SAL.codfil 'COD FILIAL'
 ,E650SAL.ctared 'COD REDUZIDO CONTA CONTÁBIL'
 ,PLA.CLACTA  'COD CONTA CONTÁBIL'
 ,UPPER(PLA.descta) 'CONTA CONTÁBIL'
 ,E650SAL.mesano 'DATA'
 ,E650SAL.DEBMES '#DÉBITO'
 ,E650SAL.CREMES '#CRÉDITO'
 --,ABS(E650SAL.salmes) '#SALDO'

 ,ABS(E650SAL.salmes)*
 
 IIF(E650SAL.salmes<0,
 IIF(PLA.NATCTA = 'D',  1,
     IIF(PLA.NATCTA = 'C', 1, -1)),
 IIF(PLA.NATCTA = 'D', -1,
 IIF(PLA.NATCTA = 'C',  -1, 1))) '#SALDO'
 ,CONCAT_WS('-', 'MML', E650SAL.codemp, PLA.CLACTA) 'KEY CONTA CONTÁBIL'




FROM [SQLMML].[Sapiens_Prod].[dbo].[E650SAL] WITH (NOLOCK)

-- JOIN: INFORMAÇÕES DA EMPRESA (HASH JOIN PARA PARALELISMO)
LEFT JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] EMP WITH (NOLOCK)
  ON E650SAL.CODEMP = EMP.CODEMP

-- JOIN: PLANO DE CONTAS
LEFT JOIN [SQLMML].[Sapiens_Prod].[dbo].[E045PLA] PLA WITH (NOLOCK)
  ON E650SAL.CODEMP = PLA.CODEMP
    AND E650SAL.CTARED = PLA.CTARED


WHERE E650SAL.ANASIN = 'A'
GO