SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_CUSTO_OS] 
AS SELECT

--CUSTOS
_DADOS.[DATA GERAÇÃO OS] 'DATA GERAÇÃO OS',
_DADOS.[DATA FECHAMENTO OS] 'DATA FECHAMENTO',
CONCAT_WS('-','MIB', _DADOS.[KEY OS]) 'KEY OS',
CONCAT_WS('-','MIB', _DADOS.CODORD) 'COD OS',
CONCAT_WS('-','MIB', _DADOS.CODEMP) 'COD EMPRESA',
CONCAT_WS('-','MIB', _DADOS.CODFIL) 'COD FILIAL',
_DADOS.[KEY EQUIPAMENTO] 'KEY EQUIPAMENTO',
CONCAT_WS('-','MML', _DADOS.[COD APLICAÇÃO]) 'COD APLICAÇÃO',
_DADOS.[APLICAÇÃO] 'APLICAÇÃO',
ROUND(ISNULL(_DADOS.CUSHHTPRE,0),2) '#CUSTO HH PREVISÃO', /*##HH Previsto,Expected HR,HH Previsto##*/
ROUND(ISNULL(_DADOS.CUSHHTREA,0),2) '#CUSTO HH REAL', /*##HH Real,Actual HR,HH Real##*/
ROUND(ISNULL(_DADOS.CUSINTPRE,0),2) '#CUSTO INTERFERÊNCIA PREVISTO', /*##Interf. Previsto,Expected Interf.,Interf. Previsto##*/
ROUND(ISNULL(_DADOS.CUSINTREA,0),2) '#CUSTO INTERFERÊNCIA REAL', /*##Interf. Real,Actual Interf.,Interf. Real##*/
ROUND(ISNULL(_DADOS.CUSMATPRE,0),2) '#CUSTO MATERIAL PREVISTO', /*##Material Previsto,Expected Material,Material Previsto##*/
ROUND(ISNULL(_DADOS.CUSMATREA,0),2) '#CUSTO MATERIAL REAL', /*##Material Real,Actual Material,Material Real##*/
ROUND(ISNULL(_DADOS.CUSSERPRE,0),2) '#CUSTO SERVIÇO PREVISTO', /*##Serviço Previsto,Expected Service,Servicio Previsto##*/
ROUND(ISNULL(_DADOS.CUSSERREA,0),2) '#CUSTO SERVIÇO REAL', /*##Serviço Real,Actual Service,Servicio Real##*/
ROUND((ISNULL(_DADOS.CUSHHTPRE,0) + ISNULL(_DADOS.CUSINTPRE,0) +  ISNULL(_DADOS.CUSMATPRE,0) + ISNULL(_DADOS.CUSSERPRE,0)),2) '#CUSTO PREVISTO', /*##Total Previsto,Expected Total,Total Previsto##*/
ROUND((ISNULL(_DADOS.CUSHHTREA,0) + ISNULL(_DADOS.CUSINTREA,0) +  ISNULL(_DADOS.CUSMATREA,0) + ISNULL(_DADOS.CUSSERREA,0)),2) '#CUSTO REAL' /*##Total Real,Actual Total,Total Real##*/

FROM (
SELECT 
CONCAT_WS('-',O.CODEMP,O.CODFIL,O.CODORD ) 'KEY OS',
O.CODAPL 'COD APLICAÇÃO',
UPPER(APLIC.DESCRICAO) 'APLICAÇÃO',
CAST(O.DATGER AS DATE) 'DATA GERAÇÃO OS',
CAST(O.DATFEC AS DATE) 'DATA FECHAMENTO OS',  
CONCAT_WS('-',Equipamento.Id,UPPER(Equipamento.Descricao)) 'KEY EQUIPAMENTO',

O.CODEMP, O.CODORD, O.CODFIL, O.TAG,
  /*RESUMO GERENCIAL - CUSTO PREVISTO DE MATERIAIS*/
   CASE G.COTACAO_MOEDA WHEN 'S' THEN
  (ISNULL((SELECT SUM(ISNULL(R1.QTDE*R1.VALOR*M1.FATOR,0) * CASE WHEN R1.FATORX IS NULL THEN 1 ELSE R1.FATORX END) FROM Engeman.Engeman.REGSERV R1, Engeman.Engeman.MOEDA M1
    WHERE R1.CODMOE=M1.CODMOE AND R1.PLANEJADO='S' AND R1.CODORD=O.CODORD AND R1.CODEMP=O.CODEMP),0)
  +         
  ISNULL((SELECT SUM(ISNULL(RXM2.QTDEPRE*RXM2.VALORPRE*M2.FATOR,0)* 
    CASE WHEN RXM2.FATORX IS NULL THEN 1 ELSE RXM2.FATORX END) FROM Engeman.Engeman.REGSERV R2, Engeman.Engeman.MOEDA M2, Engeman.Engeman.REGSERVXMAT RXM2
    WHERE R2.CODORD=RXM2.CODORD AND R2.CODEMP=RXM2.CODEMP AND R2.CODREGSER=RXM2.CODREGSER
      AND R2.CODMOE=M2.CODMOE AND R2.PLANEJADO='S' AND R2.CODORD=O.CODORD AND R2.CODEMP=O.CODEMP),0))/MO.FATOR 
  ELSE 
  (ISNULL((SELECT SUM(ISNULL(R1.QTDE*R1.VALOR*M1.FATOR,0)) FROM Engeman.Engeman.REGSERV R1, Engeman.Engeman.MOEDA M1
    WHERE R1.CODMOE=M1.CODMOE AND R1.PLANEJADO='S' AND R1.CODORD=O.CODORD AND R1.CODEMP=O.CODEMP),0)
  +         
  ISNULL((SELECT SUM(ISNULL(RXM2.QTDEPRE*RXM2.VALORPRE*M2.FATOR,0)) FROM Engeman.Engeman.REGSERV R2, Engeman.Engeman.MOEDA M2, Engeman.Engeman.REGSERVXMAT RXM2
    WHERE R2.CODORD=RXM2.CODORD AND R2.CODEMP=RXM2.CODEMP AND R2.CODREGSER=RXM2.CODREGSER
      AND R2.CODMOE=M2.CODMOE AND R2.PLANEJADO='S' AND R2.CODORD=O.CODORD AND R2.CODEMP=O.CODEMP),0))/MO.FATOR 
  END CUSMATPRE, 
  /*RESUMO GERENCIAL - CUSTO REAL DE MATERIAIS*/
  CASE G.COTACAO_MOEDA WHEN 'S' THEN
  (ISNULL((SELECT SUM(ISNULL(R3.QTDEREA*R3.VALOR*M3.FATOR,0) * CASE WHEN R3.FATORX IS NULL THEN 1 ELSE R3.FATORX END) FROM Engeman.Engeman.REGSERV R3, Engeman.Engeman.MOEDA M3
    WHERE R3.CODMOE=M3.CODMOE AND R3.EXECUTADO='S' AND R3.CODORD=O.CODORD AND R3.CODEMP=O.CODEMP),0)
  + 
  ISNULL((SELECT SUM(ISNULL(RXM4.QTDEREA*RXM4.VALORREA*M4.FATOR,0) * 
    CASE WHEN RXM4.FATORX IS NULL THEN 1 ELSE RXM4.FATORX END) FROM Engeman.Engeman.REGSERV R4, Engeman.Engeman.MOEDA M4, Engeman.Engeman.REGSERVXMAT RXM4
    WHERE R4.CODORD=RXM4.CODORD AND R4.CODEMP=RXM4.CODEMP AND R4.CODREGSER=RXM4.CODREGSER
      AND R4.CODMOE=M4.CODMOE AND R4.EXECUTADO='S' AND R4.CODORD=O.CODORD AND R4.CODEMP=O.CODEMP),0))/MO.FATOR 
  ELSE
  (ISNULL((SELECT SUM(ISNULL(R3.QTDEREA*R3.VALOR*M3.FATOR,0)) FROM Engeman.Engeman.REGSERV R3, Engeman.Engeman.MOEDA M3
    WHERE R3.CODMOE=M3.CODMOE AND R3.EXECUTADO='S' AND R3.CODORD=O.CODORD AND R3.CODEMP=O.CODEMP),0)
  + 
  ISNULL((SELECT SUM(ISNULL(RXM4.QTDEREA*RXM4.VALORREA*M4.FATOR,0)) FROM Engeman.Engeman.REGSERV R4, Engeman.Engeman.MOEDA M4, Engeman.Engeman.REGSERVXMAT RXM4
    WHERE R4.CODORD=RXM4.CODORD AND R4.CODEMP=RXM4.CODEMP AND R4.CODREGSER=RXM4.CODREGSER
      AND R4.CODMOE=M4.CODMOE AND R4.EXECUTADO='S' AND R4.CODORD=O.CODORD AND R4.CODEMP=O.CODEMP),0))/MO.FATOR 
  END CUSMATREA,
  /*RESUMO GERENCIAL - CUSTO PREVISTO DE MÃO-DE-OBRA*/
  CASE G.COTACAO_MOEDA WHEN 'S' THEN
    ISNULL(O.CUSHHTPRE,0)* CASE WHEN O.FATORX IS NULL THEN 1 ELSE O.FATORX END 
  ELSE
    ISNULL(O.CUSHHTPRE,0) 
  END CUSHHTPRE,
  /*RESUMO GERENCIAL - CUSTO REAL DE MÃO-DE-OBRA*/
  CASE G.COTACAO_MOEDA WHEN 'S' THEN
    ISNULL((SELECT SUM((ISNULL(CAST(OXF.DATHORFIM-OXF.DATHORINI AS FLOAT),0) * 24 * ISNULL(OXF.VENDA_HORA, 0)+
    (((ISNULL(CAST(OXF.DATHORFIM-OXF.DATHORINI AS FLOAT),0) * 24) * ISNULL(OXF.VENDA_HORA, 0))*
    ISNULL(OXF.HEXTRA,0)/100))* CASE WHEN OXF.FATORX IS NULL THEN 1 ELSE OXF.FATORX END) FROM Engeman.Engeman.ORDXFUN OXF
    WHERE OXF.CODORD = O.CODORD AND OXF.CODEMP=O.CODEMP AND OXF.PREVISTO='R'),0) 
  ELSE
    ISNULL((SELECT SUM(ISNULL(CAST(OXF.DATHORFIM-OXF.DATHORINI AS FLOAT),0) * 24 * ISNULL(OXF.VENDA_HORA, 0)+
    (((ISNULL(CAST(OXF.DATHORFIM-OXF.DATHORINI AS FLOAT),0) * 24) * ISNULL(OXF.VENDA_HORA, 0))*
    ISNULL(OXF.HEXTRA,0)/100)) FROM Engeman.Engeman.ORDXFUN OXF
    WHERE OXF.CODORD = O.CODORD AND OXF.CODEMP=O.CODEMP AND OXF.PREVISTO='R'),0) 
  END CUSHHTREA, 
  /*RESUMO GERENCIAL - CUSTO PREVISTO DE SERVIÇO*/  
  CASE G.COTACAO_MOEDA WHEN 'S' THEN
  ISNULL((SELECT SUM(ISNULL(R5.CUSTOPRE,0) * CASE WHEN R5.FATORX IS NULL THEN 1 ELSE R5.FATORX END) FROM Engeman.Engeman.REGSERV R5
    WHERE R5.CODORD=O.CODORD AND R5.CODEMP=O.CODEMP),0)
  ELSE
  ISNULL((SELECT SUM(ISNULL(R5.CUSTOPRE,0)) FROM Engeman.Engeman.REGSERV R5
    WHERE R5.CODORD=O.CODORD AND R5.CODEMP=O.CODEMP),0)
  END CUSSERPRE,
  /*RESUMO GERENCIAL - CUSTO REAL DE SERVIÇO*/  
  CASE G.COTACAO_MOEDA WHEN 'S' THEN
  ISNULL((SELECT SUM(ISNULL(R6.CUSTOREA,0)* CASE WHEN R6.FATORX IS NULL THEN 1 ELSE R6.FATORX END) FROM Engeman.Engeman.REGSERV R6
    WHERE R6.EXECUTADO='S' AND R6.CODORD=O.CODORD AND R6.CODEMP=O.CODEMP),0)
  ELSE
  ISNULL((SELECT SUM(ISNULL(R6.CUSTOREA,0)) FROM Engeman.Engeman.REGSERV R6
    WHERE R6.EXECUTADO='S' AND R6.CODORD=O.CODORD AND R6.CODEMP=O.CODEMP),0)
  END CUSSERREA,
  /*RESUMO GERENCIAL - CUSTO PREVISTO DE INTERFERÊNCIA*/
  ISNULL(O.CUSINTPRE,0) AS CUSINTPRE,
  /*RESUMO GERENCIAL - CUSTO REAL DE INTERFERÊNCIA*/
  ISNULL(O.CUSINTREA,0) AS CUSINTREA
FROM Engeman.Engeman.ORDSERV O 
INNER JOIN Engeman.Engeman.CFGGERAL G ON 1=1
INNER JOIN Engeman.Engeman.MOEDA mo ON O.CODMOE=MO.CODMOE

LEFT JOIN Engeman.Engeman.APLIC  WITH (NOLOCK) 
ON O.CODAPL=APLIC.CODAPL

LEFT JOIN  RajaMine.dbo.Equipamento WITH (NOLOCK)
ON APLIC.TAG =  Equipamento.Codigo COLLATE Latin1_General_CI_AS

--WHERE YEAR(O.DATGER) >=2024

)

_DADOS
GO