SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_CENTROS_RESULTADO] AS

SELECT 
'MIB' AS 'SERVIDOR',
CONCAT_WS('-','MIB',E044CCU.CODEMP) 'KEY EMPRESA',
UPPER(E070EMP.sigemp) 'EMPRESA',
CONCAT_WS('-','MIB',E044CCU.CODEMP,E044CCU.CODCCU) 'KEY CR',
UPPER(E044CCU.DESCCU) AS 'CENTRO RESULTADO',
UPPER(_GRUPO_1.DESCCU) AS 'GRUPO 1',
UPPER(IIF(_GRUPO_2.DESCCU IS NULL,_GRUPO_1.DESCCU,_GRUPO_2.DESCCU )) AS 'GRUPO 2',
UPPER(IIF(_GRUPO_3.DESCCU IS NULL,IIF(_GRUPO_2.DESCCU IS NULL,_GRUPO_1.DESCCU,_GRUPO_2.DESCCU ),_GRUPO_3.DESCCU)) AS 'GRUPO 3'
FROM SAPIENS.SAPIENS.E044CCU WITH (NOLOCK)

LEFT JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK) ON E044CCU.CODEMP = E070EMP.CODEMP

LEFT JOIN SAPIENS.SAPIENS.E044CCU _GRUPO_1 WITH (NOLOCK)
ON E044CCU.CCUPAI = _GRUPO_1.CODCCU
AND E044CCU.CODEMP = _GRUPO_1.CODEMP

LEFT JOIN SAPIENS.SAPIENS.E044CCU _GRUPO_2 WITH (NOLOCK)
ON _GRUPO_1.CCUPAI = _GRUPO_2.CODCCU
AND _GRUPO_1.CODEMP = _GRUPO_2.CODEMP

LEFT JOIN SAPIENS.SAPIENS.E044CCU _GRUPO_3 WITH (NOLOCK)
ON _GRUPO_2.CCUPAI = _GRUPO_3.CODCCU
AND _GRUPO_2.CODEMP = _GRUPO_3.CODEMP

WHERE E044CCU.TIPCCU = 1
GO