SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE VIEW [dbo].[MK_MEDICOES_CSC_CTR] 
AS SELECT 
    'MIB' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E460CTR.CODEMP AS [COD. EMPRESA],
    E070EMP.NOMEMP AS [NOME EMPRESA],
    E460CTR.CODFIL AS [COD. FILIAL],
    E070FIL.NOMFIL AS [NOME FILIAL],
    USU_TCTRINF.USU_NUMSOL AS [N° SOLICITACAO],
    E460CTR.NUMCTR AS [N° CONTRATO],
    E460CTR.CODFOR AS [COD. FORNECEDOR],
    E095FOR.NOMFOR AS [NOME FORNECEDOR],
    E460CTR.OBJCTR AS [OBSERVACAO CONTRATO],
    E460CCS.CODSER AS [COD. SERVICO],
    E080SER.DESSER AS [DESCRICAO SERVICO],
    E460CCP.CODPRO AS [COD. PRODUTO],
    E075PRO.DESPRO AS [DESCRICAO PRODUTO],
    E460CTR.VLRTOT AS [VALOR TOTAL CONTRATO],
    Convert(varchar(10), E460CTR.INIVIG,103) AS [INICIO VIGENCIA CONTRATO],
    Convert(varchar(10), E460CTR.FIMVIG,103) AS [FINAL VIGENCIA CONTRATO],
    DATEDIFF(DAY, E460CTR.INIVIG, E460CTR.FIMVIG) AS [QTD. VIGENCIA DIAS],
    DATEDIFF(DAY, GETDATE(), E460CTR.FIMVIG) AS [DIAS PARA VENCIMENTO],

    CASE 
        WHEN DATEDIFF(DAY, GETDATE(), E460CTR.FIMVIG) < 0 THEN 'Vencido'
        ELSE 'Vigente'
    END AS [SITUACAO],

    USU_TCTRINF.USU_USUGES AS [COD. GESTOR CONTRATO],
    GES.NOMUSU AS [NOME GESTOR CONTRATO],
    USU_TCTRUSU.USU_CODUSU AS [COD. MEDIDOR CONTRATO],
    MED.NOMUSU AS [NOME MEDIDOR CONTRATO],
    E460CTR.CODCPG AS [COD. CONDICAO PAGAMENTO CONTRATO],
    E028CPG.DESCPG AS [DESCRICAO CONDICAO PAGAMENTO CONTRATO]

FROM SAPIENS.SAPIENS.E460CTR WITH (NOLOCK) 

LEFT OUTER JOIN SAPIENS.SAPIENS.E070EMP WITH (NOLOCK)
ON E460CTR.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN SAPIENS.SAPIENS.E070FIL WITH (NOLOCK)
ON E460CTR.CODEMP = E070FIL.CODEMP
AND E460CTR.CODFIL = E070FIL.CODFIL

LEFT OUTER JOIN SAPIENS.SAPIENS.E095FOR WITH (NOLOCK)
ON E460CTR.CODFOR = E095FOR.CODFOR

LEFT OUTER JOIN SAPIENS.SAPIENS.E460CCS WITH (NOLOCK) 
ON E460CTR.CODEMP = E460CCS.CODEMP 
AND E460CTR.CODFIL = E460CCS.CODFIL 
AND E460CTR.NUMCTR = E460CCS.NUMCTR
AND E460CCS.SEQCCS = 1

LEFT OUTER JOIN SAPIENS.SAPIENS.E080SER WITH (NOLOCK) 
ON E460CCS.CODEMP = E080SER.CODEMP 
AND E460CCS.CODSER = E080SER.CODSER 

LEFT OUTER JOIN SAPIENS.SAPIENS.E460CCP WITH (NOLOCK) 
ON E460CTR.CODEMP = E460CCP.CODEMP 
AND E460CTR.CODFIL = E460CCP.CODFIL 
AND E460CTR.NUMCTR = E460CCP.NUMCTR
AND E460CCP.SEQCCP = 1

LEFT OUTER JOIN SAPIENS.SAPIENS.E075PRO WITH (NOLOCK) 
ON E460CCP.CODEMP = E075PRO.CODEMP 
AND E460CCP.CODPRO = E075PRO.CODPRO 

LEFT OUTER JOIN SAPIENS.SAPIENS.E028CPG WITH (NOLOCK) 
ON E460CTR.CODEMP = E028CPG.CODEMP 
AND E460CTR.CODCPG = E028CPG.CODCPG 

LEFT OUTER JOIN SAPIENS.SAPIENS.USU_TCTRINF WITH (NOLOCK) 
ON E460CTR.CODEMP = USU_TCTRINF.USU_CODEMP 
AND E460CTR.CODFIL = USU_TCTRINF.USU_CODFIL 
AND E460CTR.NUMCTR = USU_TCTRINF.USU_NUMCTR

LEFT OUTER JOIN SAPIENS.SAPIENS.R999USU GES WITH (NOLOCK) 
ON USU_TCTRINF.USU_USUGES = GES.CODUSU 

LEFT OUTER JOIN SAPIENS.SAPIENS.USU_TCTRUSU WITH (NOLOCK) 
ON USU_TCTRINF.USU_CODEMP = USU_TCTRUSU.USU_CODEMP 
AND USU_TCTRINF.USU_CODFIL = USU_TCTRUSU.USU_CODFIL 
AND USU_TCTRINF.USU_NUMCTR = USU_TCTRUSU.USU_NUMCTR

LEFT OUTER JOIN SAPIENS.SAPIENS.R999USU MED WITH (NOLOCK) 
ON USU_TCTRUSU.USU_CODUSU = MED.CODUSU 

WHERE E460CTR.TIPCTR IN (1,2)
AND E460CTR.SITCTR = 'A'

UNION ALL

SELECT 
    'MML' AS SERVIDOR, 
    GETDATE() AS ATUALIZACAO,
    E460CTR.CODEMP AS [COD. EMPRESA],
    E070EMP.NOMEMP AS [NOME EMPRESA],
    E460CTR.CODFIL AS [COD. FILIAL],
    E070FIL.NOMFIL AS [NOME FILIAL],
    USU_TCTRINF.USU_NUMSOL AS [N° SOLICITACAO],
    E460CTR.NUMCTR AS [N° CONTRATO],
    E460CTR.CODFOR AS [COD. FORNECEDOR],
    E095FOR.NOMFOR AS [NOME FORNECEDOR],
    E460CTR.OBJCTR AS [OBSERVACAO CONTRATO],
    E460CCS.CODSER AS [COD. SERVICO],
    E080SER.DESSER AS [DESCRICAO SERVICO],
    E460CCP.CODPRO AS [COD. PRODUTO],
    E075PRO.DESPRO AS [DESCRICAO PRODUTO],
    E460CTR.VLRTOT AS [VALOR TOTAL CONTRATO],
    Convert(varchar(10), E460CTR.INIVIG,103) AS [INICIO VIGENCIA CONTRATO],
    Convert(varchar(10), E460CTR.FIMVIG,103) AS [FINAL VIGENCIA CONTRATO],
    DATEDIFF(DAY, E460CTR.INIVIG, E460CTR.FIMVIG) AS [QTD. VIGENCIA DIAS],
    DATEDIFF(DAY, GETDATE(), E460CTR.FIMVIG) AS [DIAS PARA VENCIMENTO],

    CASE 
        WHEN DATEDIFF(DAY, GETDATE(), E460CTR.FIMVIG) < 0 THEN 'Vencido'
        ELSE 'Vigente'
    END AS [SITUACAO],

    USU_TCTRINF.USU_USUGES AS [COD. GESTOR CONTRATO],
    GES.NOMUSU AS [NOME GESTOR CONTRATO],
    USU_TCTRUSU.USU_CODUSU AS [COD. MEDIDOR CONTRATO],
    MED.NOMUSU AS [NOME MEDIDOR CONTRATO],
    E460CTR.CODCPG AS [COD. CONDICAO PAGAMENTO CONTRATO],
    E028CPG.DESCPG AS [DESCRICAO CONDICAO PAGAMENTO CONTRATO]

FROM [SQLMML].[Sapiens_Prod].[dbo].[E460CTR] WITH (NOLOCK) 

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070EMP] WITH (NOLOCK)
ON E460CTR.CODEMP = E070EMP.CODEMP

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E070FIL] WITH (NOLOCK)
ON E460CTR.CODEMP = E070FIL.CODEMP
AND E460CTR.CODFIL = E070FIL.CODFIL

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E095FOR] WITH (NOLOCK)
ON E460CTR.CODFOR = E095FOR.CODFOR

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E460CCS] WITH (NOLOCK) 
ON E460CTR.CODEMP = E460CCS.CODEMP 
AND E460CTR.CODFIL = E460CCS.CODFIL 
AND E460CTR.NUMCTR = E460CCS.NUMCTR
AND E460CCS.SEQCCS = 1

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E080SER] WITH (NOLOCK) 
ON E460CCS.CODEMP = E080SER.CODEMP 
AND E460CCS.CODSER = E080SER.CODSER 

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E460CCP] WITH (NOLOCK) 
ON E460CTR.CODEMP = E460CCP.CODEMP 
AND E460CTR.CODFIL = E460CCP.CODFIL 
AND E460CTR.NUMCTR = E460CCP.NUMCTR
AND E460CCP.SEQCCP = 1

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E075PRO] WITH (NOLOCK) 
ON E460CCP.CODEMP = E075PRO.CODEMP 
AND E460CCP.CODPRO = E075PRO.CODPRO 

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[E028CPG] WITH (NOLOCK) 
ON E460CTR.CODEMP = E028CPG.CODEMP 
AND E460CTR.CODCPG = E028CPG.CODCPG 

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[USU_TCTRINF] WITH (NOLOCK) 
ON E460CTR.CODEMP = USU_TCTRINF.USU_CODEMP 
AND E460CTR.CODFIL = USU_TCTRINF.USU_CODFIL 
AND E460CTR.NUMCTR = USU_TCTRINF.USU_NUMCTR

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[R999USU] GES WITH (NOLOCK) 
ON USU_TCTRINF.USU_USUGES = GES.CODUSU 

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[USU_TCTRUSU] WITH (NOLOCK) 
ON USU_TCTRINF.USU_CODEMP = USU_TCTRUSU.USU_CODEMP 
AND USU_TCTRINF.USU_CODFIL = USU_TCTRUSU.USU_CODFIL 
AND USU_TCTRINF.USU_NUMCTR = USU_TCTRUSU.USU_NUMCTR

LEFT OUTER JOIN [SQLMML].[Sapiens_Prod].[dbo].[R999USU] MED WITH (NOLOCK) 
ON USU_TCTRUSU.USU_CODUSU = MED.CODUSU 

WHERE E460CTR.TIPCTR IN (1,2)
AND E460CTR.SITCTR = 'A'

GO