SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[WH_ESTOQUE_ATUAL] 
AS SELECT
    EMPRESA.ID 'ID EMPRESA',
    UPPER(EMPRESA.DESCRICAO) 'EMPRESA',
    PILHA.ID 'ID PILHA',
    UPPER(PILHA.DESCRICAO) 'PILHA',
    MATERIAL.ID 'ID MATERIAL',
    UPPER(MATERIAL.DESCRICAO) 'MATERIAL',
    UPPER(GRUPOMATERIAL.DESCRICAO) 'GRUPO MATERIAL',
    SUM(
        IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE)
    ) '#ESTOQUE ATUAL',
    
    -- TEORES MÉDIOS PONDERADOS PELO ESTOQUE ATUAL
    CASE 
        WHEN SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE)) > 0 THEN
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', 
                    MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL1, 0), 
                    -MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL1, 0)
                )) / 
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE))
        ELSE 0
    END '#TEOR FERRO MÉDIO',
    
    CASE 
        WHEN SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE)) > 0 THEN
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', 
                    MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL2, 0), 
                    -MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL2, 0)
                )) / 
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE))
        ELSE 0
    END '#TEOR SIO2 MÉDIO',
    
    CASE 
        WHEN SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE)) > 0 THEN
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', 
                    MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL3, 0), 
                    -MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL3, 0)
                )) / 
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE))
        ELSE 0
    END '#TEOR FÓSFORO MÉDIO',
    
    CASE 
        WHEN SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE)) > 0 THEN
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', 
                    MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL4, 0), 
                    -MOVIMENTACAO.QUANTIDADE * ISNULL(MOVIMENTACAO.EL4, 0)
                )) / 
            SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE))
        ELSE 0
    END '#TEOR MANGANÊS MÉDIO',
    
    COUNT(*) '#QAUANTIDADE MOVIMENTAÇÕES',
    MAX(MOVIMENTACAO.DATA) 'ULTIMA MOVIMENTAÇÃO'

FROM RAJAMINE.dbo.MOVIMENTACAO WITH (NOLOCK)

INNER JOIN RAJAMINE.dbo.PILHA WITH (NOLOCK)
    ON MOVIMENTACAO.IDPILHA = PILHA.ID

INNER JOIN RAJAMINE.dbo.MATERIAL WITH (NOLOCK)
    ON MOVIMENTACAO.IDMATERIALORIGEM = MATERIAL.ID

INNER JOIN RAJAMINE.dbo.GRUPOMATERIAL WITH (NOLOCK)
    ON MATERIAL.IDGRUPOMATERIAL = GRUPOMATERIAL.ID

INNER JOIN RAJAMINE.dbo.PLANTATURNO WITH (NOLOCK)
    ON MOVIMENTACAO.IDPLANTATURNO = PLANTATURNO.ID

INNER JOIN RAJAMINE.dbo.EMPRESA WITH (NOLOCK)
    ON PLANTATURNO.IDEMPRESA = EMPRESA.ID

GROUP BY
    EMPRESA.ID,
    EMPRESA.DESCRICAO,
    PILHA.ID,
    PILHA.DESCRICAO,
    MATERIAL.ID,
    MATERIAL.DESCRICAO,
    GRUPOMATERIAL.DESCRICAO

HAVING 
    SUM(IIF(MOVIMENTACAO.TIPO = 'E', MOVIMENTACAO.QUANTIDADE, -MOVIMENTACAO.QUANTIDADE)) > 0
GO