SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE VIEW [dbo].[VW_FUNCIONÁRIOS] 
AS SELECT
'MIB' AS 'SERVIDOR',
--CONCAT_WS('-', 'MIB',FUNC.CODEMP, FUNC.TAG) 'KEY MATRÍCULA',
CONCAT_WS('-','MIB', FUNC.CODEMP) 'COD EMPRESA',
CONCAT_WS('-','MIB',FUNC.CODFIL) 'COD FILIAL',
CONCAT_WS('-','MIB',CODFUN) 'COD FUNNCIONÁRIO',
UPPER(NOME) 'FUNCIONÁRIO',
UPPER(CARGO.DESCRICAO) 'CARGO',
VENDA_HORA 'VALOR HORA',
CPF 'CPF',
ATIVO 'ATIVO',
--FUNC.TAG 'MATRÍCULA'
CONCAT_WS('-', 'MIB',FUNC.CODEMP, 
IIF(ISNUMERIC(FUNC.TAG) =1, CAST(FUNC.TAG AS INT),NULL)) 'KEY MATRÍCULA' 

FROM Engeman.Engeman.FUNC WITH (NOLOCK)

LEFT JOIN Engeman.Engeman.CARGO  WITH (NOLOCK)
ON FUNC.CODCAR = CARGO.CODCAR

WHERE CHARINDEX('.', FUNC.TAG) < 1

UNION ALL


SELECT
'MML' AS 'SERVIDOR',
--CONCAT_WS('-', 'MML',FUNC.CODEMP, FUNC.TAG) 'KEY MATRÍCULA',
CONCAT_WS('-','MML', FUNC.CODEMP) 'COD EMPRESA',
CONCAT_WS('-','MML',FUNC.CODFIL) 'COD FILIAL',
CONCAT_WS('-','MML',CODFUN) 'COD FUNNCIONÁRIO',
UPPER(NOME) 'FUNCIONÁRIO',
UPPER(CARGO.DESCRICAO) 'CARGO',
VENDA_HORA 'VALOR HORA',
CPF 'CPF',
ATIVO 'ATIVO',
--FUNC.TAG 'MATRÍCULA'
CONCAT_WS('-', 'MML',FUNC.CODEMP, 
IIF(ISNUMERIC(FUNC.TAG) =1, CAST(FUNC.TAG AS INT),NULL)) 'KEY MATRÍCULA' 

FROM [SQLMML].[ENGEMAN].[engeman].[FUNC] WITH (NOLOCK)

LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CARGO]  WITH (NOLOCK)
ON FUNC.CODCAR = CARGO.CODCAR

WHERE CHARINDEX('.', FUNC.TAG) < 1
GO