SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SP_HORÍMETO_GERAL] AS

-- Create temporary table for _HORÍMETRO_RAJAMINE
SELECT
  VW_CALENDÁRIO.DATA 'DATA',
  VW_EQUIPAMENTOS_ENGEMAN.[ID RAJAMINE] 'ID EQUIPAMENTO RJM',
  VW_EQUIPAMENTOS_ENGEMAN.[COD EQUIPAMENTO] 'COD EQUIPAMENTO ENGEMAN',
  VW_EQUIPAMENTOS_ENGEMAN.EQUIPAMENTO,
  SUM( IIF(HorimetroKM.DataFim IS NULL, NULL,
  IIF(HorimetroKM.DataIni IS NULL, NULL, 
  ROUND(DATEDIFF(SECOND, CAST(HorimetroKM.DataIni AS DATETIME), CAST(HorimetroKM.DataFim AS DATETIME)) / 3600.0, 2)))) 'HORAS',
  SUM(HorimetroKM.KmFim-HorimetroKM.KmIni) 'KM'
INTO #HORIMETRO_RAJAMINE -- Temporary table
FROM VW_CALENDÁRIO WITH (NOLOCK)
INNER JOIN VW_EQUIPAMENTOS_ENGEMAN WITH (NOLOCK)
  ON VW_CALENDÁRIO.ANO >= 2024
  AND VW_EQUIPAMENTOS_ENGEMAN.CONTROLA = 'SIM'
  AND VW_EQUIPAMENTOS_ENGEMAN.[ID RAJAMINE] IS NOT NULL
LEFT JOIN RajaMine.dbo.HorimetroKM WITH (NOLOCK)
  ON VW_CALENDÁRIO.DATA = CAST(HorimetroKM.DataFim AS DATE) 
  AND VW_EQUIPAMENTOS_ENGEMAN.[ID RAJAMINE] = HorimetroKM.IdEquipamento
GROUP BY
  VW_CALENDÁRIO.DATA,
  VW_EQUIPAMENTOS_ENGEMAN.[ID RAJAMINE],
  VW_EQUIPAMENTOS_ENGEMAN.[COD EQUIPAMENTO],
  VW_EQUIPAMENTOS_ENGEMAN.EQUIPAMENTO;

-- Create temporary table for _HORIMETRO_ENGEMAN_MIB
SELECT 
  'MIB' AS 'SERVIDOR',
  CONCAT('MIB-', APLIC.CODAPL) AS 'COD EQUIPAMENTO ENGEMAN',
  CONCAT_WS('-', Aplic.CodApl,APLIC.TAG)'EQUIPAMENTO ENGEMAN',
  Aplic.CodApl AS COD_EQUIPAMENTO,
  CAST(ColAcu.DatHor  AS DATE) 'DATA',
  Aplic.CodEmp 'COD EMPRESA',
  MAX(IIF(PonConAcu.CodTipPon = 3, ColAcu.Valor, 0)) AS 'KILOMETRAGEM FINAL',
  MAX(IIF(PonConAcu.CodTipPon = 1, ColAcu.Valor, 0)) AS 'HORIMETRO FINAL',
  MAX(IIF(PonConAcu.CodTipPon = 3, ColAcu.Valor, 0)) - LAG(MAX(IIF(PonConAcu.CodTipPon = 3, ColAcu.Valor, 0)), 1, 0) 
    OVER (PARTITION BY Aplic.CodApl ORDER BY CAST(ColAcu.DatHor AS DATE)) AS '#KM',
  MAX(IIF(PonConAcu.CodTipPon = 1, ColAcu.Valor, 0)) - LAG(MAX(IIF(PonConAcu.CodTipPon = 1, ColAcu.Valor, 0)), 1, 0) 
    OVER (PARTITION BY Aplic.CodApl ORDER BY CAST(ColAcu.DatHor AS DATE)) AS '#HORAS'
INTO #HORIMETRO_ENGEMAN_MIB -- Temporary table
FROM Engeman.Engeman.Aplic WITH (NOLOCK)
LEFT JOIN Engeman.Engeman.CenCus WITH (NOLOCK) ON Aplic.CodCen = CenCus.CodCen
LEFT JOIN Engeman.Engeman.ColAcu WITH (NOLOCK) ON Aplic.CodApl = ColAcu.CodApl
JOIN Engeman.Engeman.PonConAcu WITH (NOLOCK) ON Aplic.CodApl = PonConAcu.CodApl AND PonConAcu.CodPonAcu = ColAcu.CodPonAcu
WHERE ColAcu.DatHor >= '20240101' 
GROUP BY Aplic.CodApl, CAST( ColAcu.DatHor AS DATE), Aplic.CodEmp, Aplic.TAG;

-- Create temporary table for _HORIMETRO_ENGEMAN_MML
SELECT 
  'MML' AS 'SERVIDOR',
  CONCAT('MML-', APLIC.CODAPL) AS 'COD EQUIPAMENTO ENGEMAN',
  CONCAT_WS('-', Aplic.CodApl,APLIC.TAG)'EQUIPAMENTO ENGEMAN',
  Aplic.CodApl AS COD_EQUIPAMENTO,
  CAST(ColAcu.DatHor  AS DATE) 'DATA',
  Aplic.CodEmp 'COD EMPRESA',
  MAX(IIF(PonConAcu.CodTipPon = 3, ColAcu.Valor, 0)) AS 'KILOMETRAGEM FINAL',
  MAX(IIF(PonConAcu.CodTipPon = 1, ColAcu.Valor, 0)) AS 'HORIMETRO FINAL',
  MAX(IIF(PonConAcu.CodTipPon = 3, ColAcu.Valor, 0)) - LAG(MAX(IIF(PonConAcu.CodTipPon = 3, ColAcu.Valor, 0)), 1, 0) 
    OVER (PARTITION BY Aplic.CodApl ORDER BY CAST(ColAcu.DatHor AS DATE)) AS '#KM',
  MAX(IIF(PonConAcu.CodTipPon = 1, ColAcu.Valor, 0)) - LAG(MAX(IIF(PonConAcu.CodTipPon = 1, ColAcu.Valor, 0)), 1, 0) 
    OVER (PARTITION BY Aplic.CodApl ORDER BY CAST(ColAcu.DatHor AS DATE)) AS '#HORAS'
INTO #HORIMETRO_ENGEMAN_MML -- Temporary table
FROM [SQLMML].[ENGEMAN].[engeman].[Aplic] WITH (NOLOCK)
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[CenCus] WITH (NOLOCK) ON Aplic.CodCen = CenCus.CodCen
LEFT JOIN [SQLMML].[ENGEMAN].[engeman].[ColAcu] WITH (NOLOCK) ON Aplic.CodApl = ColAcu.CodApl
JOIN [SQLMML].[ENGEMAN].[engeman].[PonConAcu] WITH (NOLOCK) ON Aplic.CodApl = PonConAcu.CodApl AND PonConAcu.CodPonAcu = ColAcu.CodPonAcu
WHERE ColAcu.DatHor >= '20240101' 
GROUP BY Aplic.CodApl, CAST( ColAcu.DatHor AS DATE), Aplic.CodEmp, Aplic.TAG;

-- Main query using temporary tables
SELECT
  HR.DATA ,
  HR.[ID EQUIPAMENTO RJM],
  HR.[COD EQUIPAMENTO ENGEMAN],
  HR.EQUIPAMENTO,

  HR.KM '#KM RAJAMINE',

 COALESCE(
      HEM_MIB.[#KM],
      HEM_MML.[#KM]
    )  '#KM ENGEMAN',

  IIF(HR.KM IS NULL, 'ENGEMAN','RAJAMINE') 'FOTE KM',
  COALESCE(HR.KM,
    COALESCE(
      HEM_MIB.[#KM],
      HEM_MML.[#KM]
    )
  ) '#KM',

  HR.HORAS '#HORAS RAJAMINE',
 COALESCE(
      HEM_MIB.[#HORAS],
      HEM_MML.[#HORAS]
    ) '#HORAS ENGEMAN',

  IIF(HR.HORAS IS NULL, 'ENGEMAN','RAJAMINE') 'FOTE HS',
  COALESCE(HR.HORAS ,
    COALESCE(
      HEM_MIB.[#HORAS],
      HEM_MML.[#HORAS]
    )
  ) '#HORAS'
FROM #HORIMETRO_RAJAMINE HR
LEFT JOIN #HORIMETRO_ENGEMAN_MIB HEM_MIB
  ON HR.DATA = HEM_MIB.DATA
  AND HR.[COD EQUIPAMENTO ENGEMAN] = HEM_MIB.[COD EQUIPAMENTO ENGEMAN]
LEFT JOIN #HORIMETRO_ENGEMAN_MML HEM_MML
  ON HR.DATA = HEM_MML.DATA
  AND HR.[COD EQUIPAMENTO ENGEMAN] = HEM_MML.[COD EQUIPAMENTO ENGEMAN]
WHERE 
  COALESCE(
    COALESCE(HR.HORAS ,
      COALESCE(
        HEM_MIB.[#HORAS],
        HEM_MML.[#HORAS]
      )
    ),
    COALESCE(HR.HORAS ,
      COALESCE(
        HEM_MIB.[#HORAS],
        HEM_MML.[#HORAS]
      )
    )
  ) > 0;

-- Drop temporary tables
DROP TABLE #HORIMETRO_RAJAMINE;
DROP TABLE #HORIMETRO_ENGEMAN_MIB;
DROP TABLE #HORIMETRO_ENGEMAN_MML;

GO