SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[SP_PROGRAMACAO_EQUIPAMENTOS] @EMPRESA VARCHAR(10), @DATA_INICIAL DATE, @DATA_FINAL AS DATE
AS 

SELECT

VW_UTILIZAÇÃO.*--,

--UPPER(IIF(RIGHT(Equipamento.Descricao COLLATE SQL_Latin1_General_CP1_CI_AS, 5) = '(TSL)', Equipamento.Descricao COLLATE SQL_Latin1_General_CP1_CI_AS, COALESCE( VW_EQUIPAMENTOS.EQUIPAMENTO COLLATE SQL_Latin1_General_CP1_CI_AS ,'EQUIPAMENTO NÃO VINCULADO!'))) AS 'EQUIPAMENTO',

--IIF(RIGHT(Equipamento.Descricao COLLATE SQL_Latin1_General_CP1_CI_AS, 5) = '(TSL)', 'EQUIPAMENTO DE TERCEIROS', COALESCE( VW_EQUIPAMENTOS.TIPO COLLATE SQL_Latin1_General_CP1_CI_AS ,'EQUIPAMENTO NÃO VINCULADO!')) AS 'TIPO',

--VW_EQUIPAMENTOS.TAG



FROM VW_UTILIZAÇÃO

--LEFT JOIN VW_EQUIPAMENTOS WITH (NOLOCK)
--ON VW_UTILIZAÇÃO.[COD EQUIPAMENTO] = VW_EQUIPAMENTOS.[COD EQUIPAMENTO]

--LEFT JOIN  RajaMine.dbo.Equipamento WITH (NOLOCK)
--ON VW_UTILIZAÇÃO.[ID EQUIPAMENTO RJM] =  Equipamento.Id

WHERE VW_UTILIZAÇÃO.EMPRESA = @EMPRESA
AND VW_UTILIZAÇÃO.DATA BETWEEN @DATA_INICIAL AND @DATA_FINAL
GO